// generate with  kv generator 

"building_unit_boss" {
	"building_boss_kingkong" {
		"UnitLabel" "Boss"
		"vscripts" "npc/units/boss/npc_unit_building_boss"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lone_druid/true_form/tarzan_and_kingkong_trueform/tarzan_and_kingkong_trueform.vmdl"
		"ModelScale" "3.5"
		"MinimapIcon" "minimap_tower90"
		"MinimapIconSize" "320"
		"VisionDaytimeRange" "1500"
		"VisionNighttimeRange" "1500"
		"SoundSet" "Hero_LoneDruid"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "250"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_lone_druid.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_lone_druid.vsndevts"
		"Ability1" "kingkong_1"
		"Ability2" "kingkong_2"
		"Ability3" "kingkong_3"
		"Ability4" "kingkong_4"
		"Ability5" "kingkong_5"
		"Ability6" "kingkong_6"
		"Ability7" "kingkong_7"
		"Ability8" "kingkong_8"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"ArmorPhysical" "250"
		"ArmorMagical" "250"
		"StatusHealth" "100000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "80"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "600"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"ConsideredHero" "1"
		"RingRadius" "250"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}
		"IsValid" "1"

	}
	"building_boss_knight" {
		"UnitLabel" "Boss"
		"vscripts" "npc/units/boss/npc_unit_building_boss"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/omniknight/omniknight.vmdl"
		"ModelScale" "3.5"
		"MinimapIcon" "minimap_tower90"
		"MinimapIconSize" "320"
		"VisionDaytimeRange" "1500"
		"VisionNighttimeRange" "1500"
		"SoundSet" "Hero_Omniknight"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "250"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_omniknight.vsndevts"
		"Ability1" "omniknight_1"
		"Ability2" "omniknight_2"
		"Ability3" "omniknight_3"
		"Ability4" "omniknight_4"
		"Ability5" "omniknight_5"
		"Ability6" "omniknight_6"
		"Ability7" "omniknight_7"
		"Ability8" "omniknight_8"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"ArmorPhysical" "500"
		"ArmorMagical" "500"
		"StatusHealth" "450000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "400"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.433"
		"AttackRange" "512"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"ConsideredHero" "1"
		"RingRadius" "250"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "12168"

				}
				"2" {
					"ItemDef" "9556"

				}
				"3" {
					"ItemDef" "9244"

				}
				"4" {
					"ItemDef" "9245"

				}
				"5" {
					"ItemDef" "9246"

				}
				"6" {
					"ItemDef" "9555"

				}

			}

		}
		"IsValid" "1"

	}
	"building_boss_sand_king" {
		"UnitLabel" "Boss"
		"vscripts" "npc/units/boss/npc_unit_building_boss"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/sand_king/sand_king.vmdl"
		"ModelScale" "3.5"
		"MinimapIcon" "minimap_tower90"
		"MinimapIconSize" "320"
		"VisionDaytimeRange" "1500"
		"VisionNighttimeRange" "1500"
		"SoundSet" "Hero_SandKing"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "200"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_sandking.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_sandking.vsndevts"
		"Ability1" "sk_1"
		"Ability2" "sk_2"
		"Ability3" "sk_3"
		"Ability4" "sk_4"
		"Ability5" "sk_5"
		"Ability6" "sk_6"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"ArmorPhysical" "800"
		"ArmorMagical" "800"
		"StatusHealth" "1150000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "1000"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.46"
		"AttackRange" "512"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"ConsideredHero" "1"
		"RingRadius" "200"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "12820"

				}
				"2" {
					"ItemDef" "12815"

				}
				"3" {
					"ItemDef" "12817"

				}
				"4" {
					"ItemDef" "12818"

				}
				"5" {
					"ItemDef" "12816"

				}
				"6" {
					"ItemDef" "12819"

				}

			}

		}
		"IsValid" "1"

	}
	"building_boss_jakiro" {
		"UnitLabel" "Boss"
		"vscripts" "npc/units/boss/npc_unit_building_boss"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/jakiro/jakiro.vmdl"
		"ModelScale" "3.5"
		"MinimapIcon" "minimap_tower90"
		"MinimapIconSize" "320"
		"VisionDaytimeRange" "1500"
		"VisionNighttimeRange" "1500"
		"SoundSet" "Hero_Jakiro"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "350"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_jakiro.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_jakiro.vsndevts"
		"Ability1" "jakiro_1"
		"Ability2" "jakiro_2"
		"Ability3" "jakiro_3"
		"Ability4" "jakiro_4"
		"Ability5" "jakiro_5"
		"Ability6" "jakiro_6"
		"Ability7" "jakiro_7"
		"Ability8" "jakiro_8"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"ArmorPhysical" "1200"
		"ArmorMagical" "1200"
		"StatusHealth" "2250000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "800"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.4"
		"AttackRange" "2000"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/boss/jakiro/base_attack.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"ConsideredHero" "1"
		"RingRadius" "350"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "9298"

				}
				"3" {
					"ItemDef" "9297"

				}
				"4" {
					"ItemDef" "9262"

				}

			}

		}
		"IsValid" "1"

	}
	"building_boss_nian" {
		"UnitLabel" "Boss"
		"vscripts" "npc/units/boss/npc_unit_building_boss"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/nian/nian_creep.vmdl"
		"ModelScale" "2"
		"MinimapIcon" "minimap_tower90"
		"MinimapIconSize" "320"
		"VisionDaytimeRange" "1500"
		"VisionNighttimeRange" "1500"
		"SoundSet" "cny_beast"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "500"
		"Ability1" "nian_1"
		"Ability2" "nian_2"
		"Ability3" "nian_3"
		"Ability4" "nian_4"
		"Ability5" "nian_5"
		"Ability6" "nian_6"
		"Ability7" "nian_7"
		"Ability8" "nian_8"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"ArmorPhysical" "1200"
		"ArmorMagical" "1200"
		"StatusHealth" "5000000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "1000"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "512"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"ConsideredHero" "1"
		"RingRadius" "500"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}
		"IsValid" "1"

	}
	"building_boss_tidehunter" {
		"UnitLabel" "Boss"
		"vscripts" "npc/units/boss/npc_unit_building_boss"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/tidehunter/tidehunter.vmdl"
		"ModelScale" "3.5"
		"MinimapIcon" "minimap_tower90"
		"MinimapIconSize" "320"
		"VisionDaytimeRange" "1500"
		"VisionNighttimeRange" "1500"
		"SoundSet" "Hero_TideHunter"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "350"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_tide_hunter.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_tide_hunter.vsndevts"
		"Ability1" "tide_1"
		"Ability2" "tide_2"
		"Ability3" "tide_3"
		"Ability4" "tide_4"
		"Ability5" "tide_5"
		"Ability6" "tide_6"
		"Ability7" "tide_7"
		"Ability8" "tide_8"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"ArmorPhysical" "1200"
		"ArmorMagical" "1200"
		"StatusHealth" "5000000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "1000"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "512"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"ConsideredHero" "1"
		"RingRadius" "500"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "14138"

				}
				"2" {
					"ItemDef" "14139"

				}
				"3" {
					"ItemDef" "9632"

				}
				"4" {
					"ItemDef" "14141"

				}
				"5" {
					"ItemDef" "14142"

				}
				"6" {
					"ItemDef" "14143"

				}

			}

		}
		"IsValid" "1"

	}
	"building_boss_skywrath" {
		"UnitLabel" "Boss"
		"vscripts" "npc/units/boss/npc_unit_building_boss"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/skywrath_mage/skywrath_mage.vmdl"
		"ModelScale" "2"
		"MinimapIcon" "minimap_tower90"
		"MinimapIconSize" "320"
		"VisionDaytimeRange" "1500"
		"VisionNighttimeRange" "1500"
		"SoundSet" "Hero_SkywrathMage"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"BoundsHullRadius" "40"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_skywrath_mage.vsndevts"
		"Ability1" "skywrath_boss_1"
		"Ability2" "skywrath_boss_2"
		"Ability3" "skywrath_boss_3"
		"Ability4" "skywrath_boss_4"
		"Ability5" "skywrath_boss_5"
		"Ability6" "skywrath_boss_6"
		"Ability7" "skywrath_boss_7"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"ArmorPhysical" "1200"
		"ArmorMagical" "1200"
		"StatusHealth" "5000000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "777"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.4"
		"AttackRange" "2000"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_skywrath_mage/skywrath_mage_base_attack.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"ConsideredHero" "1"
		"RingRadius" "500"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "6974"

				}
				"2" {
					"ItemDef" "6973"

				}
				"3" {
					"ItemDef" "13568"

				}
				"4" {
					"ItemDef" "6972"

				}
				"5" {
					"ItemDef" "6734"

				}
				"6" {
					"ItemDef" "6733"

				}

			}

		}
		"IsValid" "1"

	}
	"building_boss_vengeful" {
		"UnitLabel" "Boss"
		"vscripts" "npc/units/boss/npc_unit_building_boss"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/vengeful/vengeful.vmdl"
		"ModelScale" "2.7"
		"MinimapIcon" "minimap_tower90"
		"MinimapIconSize" "320"
		"VisionDaytimeRange" "1500"
		"VisionNighttimeRange" "1500"
		"SoundSet" "Hero_VengefulSpirit"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"BoundsHullRadius" "40"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_vengeful_spirit.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_vengeful_spirit.vsndevts"
		"Ability1" "vengeful_boss_1"
		"Ability2" "vengeful_boss_2"
		"Ability3" "vengeful_boss_3"
		"Ability4" "vengeful_boss_4"
		"Ability5" "vengeful_boss_5"
		"Ability6" "vengeful_boss_6"
		"Ability7" "vengeful_boss_7"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "550"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"ArmorPhysical" "1200"
		"ArmorMagical" "1200"
		"StatusHealth" "5000000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "777"
		"AttackRate" "0.8"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"ConsideredHero" "1"
		"RingRadius" "500"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "7510"

				}
				"2" {
					"ItemDef" "8617"

				}
				"3" {
					"ItemDef" "7799"

				}
				"4" {
					"ItemDef" "7796"

				}
				"5" {
					"ItemDef" "9485"

				}
				"6" {
					"ItemDef" "9486"

				}

			}

		}
		"IsValid" "1"

	}
	"chest1" {
		"UnitLabel" "gold"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/courier/flopjaw/flopjaw.vmdl"
		"ModelScale" "2.3"
		"SoundSet" "n_creep_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"BoundsHullRadius" "10"
		"AbilityLayout" "1"
		"HealthBarOffset" "300"
		"MovementSpeed" "100"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "700"
		"MagicalArmor" "700"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamage" "0"
		"AttackRate" "3"
		"AttackAnimationPoint" "0"
		"AttackRange" "1400"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"chest2" {
		"UnitLabel" "gold"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/courier/flopjaw/flopjaw.vmdl"
		"ModelScale" "2.3"
		"SoundSet" "n_creep_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"BoundsHullRadius" "10"
		"AbilityLayout" "1"
		"HealthBarOffset" "300"
		"MovementSpeed" "100"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "700"
		"MagicalArmor" "700"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamage" "0"
		"AttackRate" "3"
		"AttackAnimationPoint" "0"
		"AttackRange" "1400"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"chest3" {
		"UnitLabel" "gold"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/courier/flopjaw/flopjaw.vmdl"
		"ModelScale" "2.3"
		"SoundSet" "n_creep_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"BoundsHullRadius" "10"
		"AbilityLayout" "1"
		"HealthBarOffset" "300"
		"MovementSpeed" "100"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "700"
		"MagicalArmor" "700"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamage" "0"
		"AttackRate" "3"
		"AttackAnimationPoint" "0"
		"AttackRange" "1400"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"chest4" {
		"UnitLabel" "gold"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/courier/flopjaw/flopjaw.vmdl"
		"ModelScale" "2.3"
		"SoundSet" "n_creep_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"BoundsHullRadius" "10"
		"AbilityLayout" "1"
		"HealthBarOffset" "300"
		"MovementSpeed" "100"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "2000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "700"
		"MagicalArmor" "700"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamage" "0"
		"AttackRate" "3"
		"AttackAnimationPoint" "0"
		"AttackRange" "1400"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"kingkong_beasts_boar" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/beastmaster/boar/ti9_cache_beastmaster_king_of_beasts_boar/ti9_cache_beastmaster_king_of_beasts_boar.vmdl"
		"ModelScale" "2"
		"SoundSet" "n_creep_Ranged"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "4000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "200"
		"MagicalArmor" "200"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "120"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "768"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/neutral_fx/gnoll_base_attack.vpcf"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"kingkong_telepathy_beast" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/beastmaster/boar/ti9_cache_beast_master_dinosaurs_telepathy_beast/ti9_cache_beast_master_dinosaurs_telepathy_beast.vmdl"
		"ModelScale" "2"
		"SoundSet" "n_creep_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "4000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "200"
		"MagicalArmor" "200"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "80"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "768"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/neutral_fx/gnoll_base_attack.vpcf"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"knight_skeleton" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_troll_skeleton/n_creep_skeleton_melee.vmdl"
		"ModelScale" "4"
		"SoundSet" "n_creep_Ranged"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "20000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "300"
		"MagicalArmor" "300"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "250"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "256"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"dragon_egg_ice" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/phoenix/ultimate/blazing_wing_blazing_egg/blazing_wing_blazing_egg.vmdl"
		"ModelScale" "2"
		"SoundSet" "n_creep_Ranged"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "30000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "1500"
		"MagicalArmor" "1500"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "500"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "256"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"dragon_egg_fire" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/phoenix/ultimate/blazing_wing_blazing_egg/blazing_wing_blazing_egg.vmdl"
		"ModelScale" "2"
		"SoundSet" "n_creep_Ranged"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "30000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "1500"
		"MagicalArmor" "1500"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "500"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "256"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"naturecaller_summon" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/furion/treant.vmdl"
		"SoundSet" "n_creep_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "0"
		"Ability1" "naturecaller_summon_1"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "400"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "30"
		"MagicalArmor" "30"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "150"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"little_enigma" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/enigma/eidolon/enigma_seer_of_infinity_space_eidolon/enigma_seer_of_infinity_space_eidolon.vmdl"
		"ModelScale" "1"
		"SoundSet" "n_creep_Ranged"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"AbilityLayout" "4"
		"HealthBarOffset" "180"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "0"
		"AttackRate" "1.3"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "1200"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/econ/items/enigma/enigma_geodesic/enigma_base_attack_eidolon_geodesic.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"undying_zombie" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/undying/idol_of_ruination/ruin_wight_minion_gold.vmdl"
		"ModelScale" "1.5"
		"SoundSet" "n_creep_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "180"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "500"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "150"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"abyss_devil" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/undying/flesh_golem/incurable_pestilence_golem/incurable_pestilence_golem.vmdl"
		"ModelScale" "1.25"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"AbilityLayout" "4"
		"HealthBarOffset" "180"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "2000"
		"StatusHealthRegen" "5"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "300"
		"MagicalArmor" "300"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "350"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "200"
		"AttackAcquisitionRange" "3000"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"spell_tower" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_tower"
		"Model" "models/props_structures/tower_good3_dest_lvl1.vmdl"
		"ModelScale" "1.15"
		"SoundSet" "n_creep_Ranged"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "0"
		"HealthBarOffset" "180"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "0"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "1258"
		"AttackAcquisitionRange" "1800"
		"ProjectileModel" "particles/econ/events/ti9/rock_golem_tower/dire_tower_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"king_of_tower" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/rattletrap/ti9_cache_clock_living_calendar_sun_idol/ti9_cache_clock_living_calendar_sun_idol.vmdl"
		"ModelScale" "1.25"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackRate" "0"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"chicken_house" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/rattletrap/ti9_cache_clock_living_calendar_sun_idol/ti9_cache_clock_living_calendar_sun_idol.vmdl"
		"ModelScale" "0.46"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackRate" "0"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"sucide_chicken" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/gyrocopter/gyro_ti10_immortal_missile/gyro_ti10_immortal_missile.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"AbilityLayout" "0"
		"HealthBarOffset" "300"
		"MovementSpeed" "450"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamage" "0"
		"AttackRate" "0"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "450"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/ti9_chameleon_radiant/ti9_chameleon_radiant_melee.vmdl"
		"ModelScale" "1.65"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "625"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "4"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_2" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/ti9_chameleon_radiant/ti9_chameleon_radiant_ranged_mega.vmdl"
		"ModelScale" "1.65"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "250"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1042"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "20"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/base_attacks/ranged_badguy.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_2_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/ti9_chameleon_radiant/ti9_chameleon_radiant_melee_mega.vmdl"
		"ModelScale" "1.65"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1042"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "5"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_3" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee_mega.vmdl"
		"ModelScale" "1.55"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ignite"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1458"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "20"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_3_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_bad_ranged/lane_dire_ranged_mega.vmdl"
		"ModelScale" "1.65"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "150"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1458"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "20"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/base_attacks/ranged_badguy.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_4" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_bad_ranged/lane_dire_ranged_mega.vmdl"
		"ModelScale" "1.8"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ignite"
		"Ability2" "enemy_irritable"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1875"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "20"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/items2_fx/necronomicon_archer_projectile.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_5" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/ogre_1/boss_ogre.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"Ability1" "enemy_ignite"
		"Ability2" "enemy_explosion"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "220"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "10000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "200"
		"MagicalArmor" "200"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "30"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "50"
		"Creature" {

		}

	}
	"tui3_6" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee_mega.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ignite"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "2708"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "8"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_6_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/invoker/forge_spirit.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_blasting"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "2708"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "20"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_7" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/clinkz/clinkz_archer.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ignite"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3125"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "20"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/econ/items/clinkz/clinkz_maraxiform/clinkz_maraxiform_searing_arrow.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_7_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/furion/treant/the_ancient_guardian_the_ancient_treants/the_ancient_guardian_the_ancient_treants.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_bubbleshiled"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "300"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3125"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "10"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_8" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee_mega.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ignite"
		"Ability2" "enemy_healthrecovery"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3542"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "15"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_9" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee.vmdl"
		"ModelScale" "1.45"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3958"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "25"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_10" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_radiant_hulk/creep_radiant_ancient_hulk.vmdl"
		"ModelScale" "1.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "74974"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "30"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_11" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_ghost_b/n_creep_ghost_b.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fireball"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "4287"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "25"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/ghost_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_12" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_furbolg/n_creep_furbolg_disrupter.vmdl"
		"ModelScale" "1.7"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_knockback"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "5561"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "35"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_12_2" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_ghost_b/n_creep_ghost_b.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fireball"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "5561"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "56"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/ghost_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_13" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_ghost_b/n_creep_ghost_frost.vmdl"
		"ModelScale" "2.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fireball"
		"Ability2" "enemy_irritable"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "6934"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "56"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/ghost_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_13_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_beast/n_creep_beast.vmdl"
		"ModelScale" "1.2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_knockback"
		"Ability2" "enemy_bubbleshiled"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "6934"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "17"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_14" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_ghost_a/n_creep_ghost_a.vmdl"
		"ModelScale" "2.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_explosion"
		"Ability2" "enemy_irritable"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8396"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "80"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/ghost_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_14_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_ghost_b/n_creep_ghost_red.vmdl"
		"ModelScale" "3"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fireball"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8396"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "80"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/ghost_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_15" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_dire_hulk/creep_dire_diretide_ancient_hulk.vmdl"
		"ModelScale" "1.8"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"Ability1" "enemy_fire_shield"
		"Ability2" "enemy_crush"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "220"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "35000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "1000"
		"MagicalArmor" "1000"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "80"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_15_2" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_dire_hulk/creep_dire_diretide_ancient_hulk.vmdl"
		"ModelScale" "1.8"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"Ability1" "enemy_firechain"
		"Ability2" "enemy_crush"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "220"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "35000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "1000"
		"MagicalArmor" "1000"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "80"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_16" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/ti9_crocodilian_dire/ti9_crocodilian_dire_melee.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fireblow"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "11556"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "25"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_17" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/ti9_crocodilian_dire/ti9_crocodilian_dire_melee.vmdl"
		"ModelScale" "1.8"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ignite"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "13245"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "55"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_17_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_thunder_lizard/n_creep_thunder_lizard_small.vmdl"
		"ModelScale" "1.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_blasting"
		"Ability2" "enemy_atk"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "13245"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "55"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "600"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/gnoll_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_18" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/slardar/slardar.vmdl"
		"ModelScale" "1.7"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ravage"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "15004"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "108"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "8790"

				}
				"2" {
					"ItemDef" "8792"

				}
				"3" {
					"ItemDef" "722"

				}
				"4" {
					"ItemDef" "8789"

				}
				"5" {
					"ItemDef" "512"

				}
				"6" {
					"ItemDef" "8791"

				}

			}

		}

	}
	"tui3_18_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_black_dragon/n_creep_black_dragon.vmdl"
		"ModelScale" "1.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ignite"
		"Ability2" "split_attack"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "15004"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "108"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "600"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_obsidian_destroyer/obsidian_destroyer_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_19" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee.vmdl"
		"ModelScale" "1.08"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "16832"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "101"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_20" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_radiant_hulk/creep_radiant_ancient_hulk.vmdl"
		"ModelScale" "1.1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "449575"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "113"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_21" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_vulture_a/n_creep_vulture_a.vmdl"
		"ModelScale" "2.2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_ignite"
		"Ability2" "enemy_fireball"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "20709"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "200"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "1200"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_obsidian_destroyer/obsidian_destroyer_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_22" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/beastmaster/boar/ti9_cache_beast_master_dinosaurs_telepathy_beast/ti9_cache_beast_master_dinosaurs_telepathy_beast.vmdl"
		"ModelScale" "1.3"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fireblow"
		"Ability2" "enemy_slaughter"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "22768"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "280"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_23" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lone_druid/bear/spirit_of_anger/spirit_of_anger.vmdl"
		"ModelScale" "1.3"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fire_shield"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "24919"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "343"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_24" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lone_druid/bear/iron_claw_spirit_bear/iron_claw_spirit_bear.vmdl"
		"ModelScale" "1.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fire_shield"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "27171"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "370"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_24_2" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/batrider/ti9_cache_batrider_exploerer_magic_jungle_mount/ti9_cache_batrider_exploerer_magic_jungle_mount.vmdl"
		"ModelScale" "1.2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_firebottle"
		"Ability2" "enemy_blasting"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "27171"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "225"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_batrider/batrider_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_25" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"Ability1" "enemy_lavashield"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "85000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "750"
		"MagicalArmor" "150"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "1300"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "200"
		"AttackAcquisitionRange" "800"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_25_2" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/medusa/medusa.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"Ability1" "enemy_explosion"
		"Ability2" "split_attack"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "220"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "85000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "150"
		"MagicalArmor" "750"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "417"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "750"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" "particles/units/heroes/hero_medusa/medusa_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "5004"

				}
				"2" {
					"ItemDef" "5005"

				}
				"3" {
					"ItemDef" "7911"

				}
				"4" {
					"ItemDef" "531"

				}
				"5" {
					"ItemDef" "13778"

				}
				"6" {
					"ItemDef" "5007"

				}

			}

		}

	}
	"tui3_26" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_satyr_b/n_creep_satyr_b.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fireregen"
		"Ability2" "enemy_ignite"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "32032"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "430"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.7"
		"AttackRange" "500"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/base_attacks/ranged_badguy.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_27" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_dragonspawn_b/n_creep_dragonspawn_b.vmdl"
		"ModelScale" "1.24"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_firechain"
		"Ability2" "enemy_slaughter"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "34672"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "456"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_28" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/mega_greevil/mega_greevil.vmdl"
		"ModelScale" "2.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_fireblow"
		"Ability2" "enemy_ice"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "37476"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "490"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_29" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee.vmdl"
		"ModelScale" "2.75"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "40464"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "512"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_30" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_radiant_hulk/creep_radiant_ancient_hulk.vmdl"
		"ModelScale" "2.8"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1047834"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "547"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_31" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/rubick/rubick.vmdl"
		"ModelScale" "1.8"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_firecircle"
		"Ability2" "enemy_firecurse"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "47087"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "171"
		"AttackRate" "2"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_rubick/rubick_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "13265"

				}
				"2" {
					"ItemDef" "13267"

				}
				"3" {
					"ItemDef" "13266"

				}
				"4" {
					"ItemDef" "13268"

				}
				"5" {
					"ItemDef" "674"

				}

			}

		}

	}
	"tui3_32" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lone_druid/bear/iron_claw_spirit_bear/iron_claw_spirit_bear.vmdl"
		"ModelScale" "1.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_burning"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "50774"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "567"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_32_2" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/batrider/batrider.vmdl"
		"ModelScale" "1.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_firebottle"
		"Ability2" "enemy_firecurse"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "50774"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "567"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_batrider/batrider_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "7013"

				}
				"2" {
					"ItemDef" "7015"

				}
				"3" {
					"ItemDef" "7012"

				}
				"4" {
					"ItemDef" "7014"

				}

			}

		}

	}
	"tui3_33" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/courier/grim_wolf/grim_wolf.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_crush"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "54747"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "650"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_33_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/rubick/rubick.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_firecircle"
		"Ability2" "enemy_firecurse"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "54747"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "650"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_rubick/rubick_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "13265"

				}
				"2" {
					"ItemDef" "13267"

				}
				"3" {
					"ItemDef" "13266"

				}
				"4" {
					"ItemDef" "13268"

				}
				"5" {
					"ItemDef" "674"

				}

			}

		}

	}
	"tui3_34" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/warlock/warlock_fourleg_demon.vmdl"
		"ModelScale" "1.3"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_lavashield"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "59040"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "683"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_34_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/warlock/warlock.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_explosion"
		"Ability2" "enemy_knockback"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "59040"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "794"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "640"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_warlock/warlock_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "8079"

				}
				"2" {
					"ItemDef" "8080"

				}
				"3" {
					"ItemDef" "8077"

				}
				"4" {
					"ItemDef" "8082"

				}
				"5" {
					"ItemDef" "8078"

				}
				"6" {
					"ItemDef" "8076"

				}
				"7" {
					"ItemDef" "8083"

				}

			}

		}

	}
	"tui3_35" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/invoker/invoker.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"Ability1" "enemy_skyfire"
		"Ability2" "enemy_firecurse"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "220"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "165000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "1250"
		"MagicalArmor" "2500"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "1275"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "1250"
		"AttackAcquisitionRange" "1250"
		"ProjectileModel" "particles/units/heroes/hero_invoker/invoker_base_attack.vpcf"
		"ProjectileSpeed" "1200"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "8743"

				}
				"2" {
					"ItemDef" "98"

				}
				"3" {
					"ItemDef" "8373"

				}
				"4" {
					"ItemDef" "8744"

				}
				"5" {
					"ItemDef" "8372"

				}
				"6" {
					"ItemDef" "8745"

				}

			}

		}

	}
	"tui3_35_2" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/doom/doom.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"Ability1" "enemy_fireinhibit"
		"Ability2" "enemy_lavashield"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "220"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "215000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "2500"
		"MagicalArmor" "1250"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "1275"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "500"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "6501"

				}
				"2" {
					"ItemDef" "6502"

				}
				"3" {
					"ItemDef" "6504"

				}
				"4" {
					"ItemDef" "6505"

				}
				"5" {
					"ItemDef" "6507"

				}
				"6" {
					"ItemDef" "6506"

				}
				"7" {
					"ItemDef" "6503"

				}

			}

		}

	}
	"tui3_36" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/warlock/warlock_demon.vmdl"
		"ModelScale" "1.3"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_lavashield"
		"Ability2" "enemy_block"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "68713"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "721"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_37" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/warlock/warlock_demon.vmdl"
		"ModelScale" "1.6"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_lavashield"
		"Ability2" "enemy_fire_shield"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "74166"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "721"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"tui3_37_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/phoenix/phoenix_bird.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_melting"
		"Ability2" "enemy_firecircle"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "74166"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "721"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_phoenix/phoenix_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "535"

				}
				"2" {
					"ItemDef" "9524"

				}
				"3" {
					"ItemDef" "9525"

				}
				"4" {
					"ItemDef" "9523"

				}

			}

		}

	}
	"tui3_38" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/chaos_knight/chaos_knight.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_melting"
		"Ability2" "enemy_firecircle"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "80081"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "648"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "18458"

				}
				"2" {
					"ItemDef" "18457"

				}
				"3" {
					"ItemDef" "18460"

				}
				"4" {
					"ItemDef" "18459"

				}
				"5" {
					"ItemDef" "18461"

				}

			}

		}

	}
	"tui3_38_1" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/phoenix/phoenix_bird.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"Ability1" "enemy_burning"
		"Ability2" "enemy_melting"
		"AbilityLayout" "4"
		"HealthBarOffset" "300"
		"MovementSpeed" "200"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "80081"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "998"
		"AttackRate" "0.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_phoenix/phoenix_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "535"

				}
				"2" {
					"ItemDef" "9524"

				}
				"3" {
					"ItemDef" "9525"

				}
				"4" {
					"ItemDef" "9523"

				}

			}

		}

	}
	"worg_small" {
		"UnitLabel" "creep"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_worg_small/n_creep_worg_small.vmdl"
		"ModelScale" "0.9"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "720"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "14"
		"AttackRate" "1.45"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"worg_large" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_worg_large/n_creep_worg_large.vmdl"
		"ModelScale" "0.9"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "160"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1668"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "30"
		"AttackRate" "1.35"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"boar" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/beastmaster/boar/beast_heart_marauder_beast_heart_marauder_warhound/beast_heart_marauder_beast_heart_marauder_warhound.vmdl"
		"ModelScale" "0.65"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "125"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "840"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "23"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.633"
		"AttackRange" "512"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/base_attacks/ranged_goodguy.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"forest_troll_high_priest" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_forest_trolls/n_creep_forest_troll_high_priest.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1908"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "29"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "640"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/base_attacks/ranged_goodguy.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"forest_troll_berserker" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_forest_trolls/n_creep_forest_troll_berserker.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_kobold_b" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_kobold/kobold_b/n_creep_kobold_b.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_kobold_c" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_kobold/kobold_c/n_creep_kobold_c.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_gnoll" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_gnoll/n_creep_gnoll.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "640"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/neutral_fx/gnoll_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_ogre_lrg" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_ogre_lrg/n_creep_ogre_lrg.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_ogre_med" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_ogre_med/n_creep_ogre_med.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"large_ogre" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/ogre_1/large_ogre.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_furbolg_disrupter" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_furbolg/n_creep_furbolg_disrupter.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_beast" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_beast/n_creep_beast.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_harpy_b" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_harpy_b/n_creep_harpy_b.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "896"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/neutral_fx/gnoll_base_attack.vpcf"
		"ProjectileSpeed" "1600"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_harpy_a" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_harpy_a/n_creep_harpy_a.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "896"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/neutral_fx/gnoll_base_attack.vpcf"
		"ProjectileSpeed" "1600"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_troll_dark_b" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_troll_dark_b/n_creep_troll_dark_b.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "768"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" "particles/neutral_fx/gnoll_base_attack.vpcf"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"creep_troll_dark_a" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/neutral_creeps/n_creep_troll_dark_a/n_creep_troll_dark_a.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "130"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "3108"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "65"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"unit_test" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/courier/doom_demihero_courier/doom_demihero_courier.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "175"
		"MovementSpeed" "240"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"wave_unicorn_1" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/courier/defense4_dire/defense4_dire.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "200"
		"MovementSpeed" "300"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"wave_unicorn_2" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/courier/butch_pudge_dog/butch_pudge_dog.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "200"
		"MovementSpeed" "400"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"wave_unicorn_3" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/courier/kanyu_shark/kanyu_shark_flying.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "200"
		"MovementSpeed" "400"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"wave_unicorn_4" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/courier/nexon_turtle_11_blue/nexon_turtle_11_blue.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "200"
		"MovementSpeed" "220"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"wave_unicorn_3_1" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/courier/kanyu_shark/kanyu_shark.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "200"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"roshan_gift" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/courier/trapjaw/trapjaw_flying.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "200"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"roshan_accompany_physical" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/courier/baby_rosh/babyroshan_elemental_flying.vmdl"
		"ModelScale" "1.35"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "350"
		"MovementSpeed" "250"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "500"
		"MagicalArmor" "500"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackRange" "300"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"roshan_accompany_magical" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/courier/baby_rosh/babyroshan_elemental_flying.vmdl"
		"ModelScale" "1.35"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"HealthBarOffset" "350"
		"MovementSpeed" "250"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "107"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.66"
		"AttackAcquisitionRange" "500"
		"Creature" {

		}

	}
	"test_single" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee.vmdl"
		"ModelScale" "1"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "200"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "24000000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "2"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"test_42" {
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/creeps/lane_creeps/creep_radiant_hulk/creep_radiant_ancient_hulk.vmdl"
		"ModelScale" "1.2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"AbilityLayout" "4"
		"HealthBarOffset" "200"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "99999999"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "1"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "500"
		"HasInventory" "0"
		"RingRadius" "90"
		"Creature" {

		}

	}
	"contract_shadow_furion" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/furion/furion.vmdl"
		"ModelScale" "2"
		"SoundSet" "Hero_Furion"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "100"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_furion.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_furion.vsndevts"
		"Ability1" "contract_shadow_guardian"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8183"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "100"
		"MagicalArmor" "100"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "100"
		"AttackRate" "0.8"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "14278"

				}
				"2" {
					"ItemDef" "14276"

				}
				"3" {
					"ItemDef" "14277"

				}
				"4" {
					"ItemDef" "14281"

				}
				"5" {
					"ItemDef" "14280"

				}
				"6" {
					"ItemDef" "14275"

				}
				"7" {
					"ItemDef" "14279"

				}

			}

		}

	}
	"contract_stars" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/wisp/wisp.vmdl"
		"ModelScale" "2.5"
		"SoundSet" "Hero_Wisp"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "200"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_wisp.vsndevts"
		"Ability1" "contract_star_core"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "425"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "5294"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "100"
		"MagicalArmor" "100"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "54"
		"AttackRate" "1.3"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "300"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "9235"

				}

			}

		}

	}
	"contract_taunt" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/pugna/ward/draining_wight/draining_wight.vmdl"
		"ModelScale" "2.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "100"
		"Ability1" "contract_totems"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "150"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8400"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "0"
		"MagicalArmor" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "50"
		"AttackRate" "0.2"
		"AttackAnimationPoint" "0"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {

		}

	}
	"contract_silencer" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/bane/bane.vmdl"
		"ModelScale" "2"
		"SoundSet" "Hero_Bane"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "50"
		"Ability1" "contract_seal_stone"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8183"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "150"
		"MagicalArmor" "150"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "120"
		"AttackRate" "0.8"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_bane/bane_projectile.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "8549"

				}
				"2" {
					"ItemDef" "8548"

				}
				"3" {
					"ItemDef" "8547"

				}
				"4" {
					"ItemDef" "8550"

				}
				"5" {
					"ItemDef" "503"

				}

			}

		}

	}
	"contract_assassin" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/bounty_hunter/bounty_hunter.vmdl"
		"ModelScale" "2.5"
		"SoundSet" "Hero_BountyHunter"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "100"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_bounty_hunter.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_bounty_hunter.vsndevts"
		"Ability1" "contract_hermit"
		"AbilityLayout" "4"
		"HealthBarOffset" "350"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "6429"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "50"
		"MagicalArmor" "50"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "100"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "300"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "8951"

				}
				"2" {
					"ItemDef" "8950"

				}
				"3" {
					"ItemDef" "8953"

				}
				"4" {
					"ItemDef" "8952"

				}
				"5" {
					"ItemDef" "8949"

				}
				"6" {
					"ItemDef" "8948"

				}
				"7" {
					"ItemDef" "564"

				}

			}

		}

	}
	"contract_priests" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/shadow_demon/shadow_demon.vmdl"
		"ModelScale" "2"
		"SoundSet" "Hero_ShadowDemon"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "100"
		"Ability1" "contract_priesthood"
		"AbilityLayout" "4"
		"HealthBarOffset" "400"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8183"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "100"
		"MagicalArmor" "100"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "120"
		"AttackRate" "0.6"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "14370"

				}
				"2" {
					"ItemDef" "14368"

				}
				"3" {
					"ItemDef" "14369"

				}
				"4" {
					"ItemDef" "14371"

				}

			}

		}

	}
	"contract_dark_tower" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "100"
		"Ability1" "contract_dark_tower"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "100"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8250"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "100"
		"MagicalArmor" "100"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "67"
		"AttackRate" "0.6"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "4000"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/econ/world/towers/ti10_dire_tower/ti10_dire_tower_attack.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"RingRadius" "250"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "6996"

				}
				"2" {
					"ItemDef" "488"

				}
				"3" {
					"ItemDef" "486"

				}

			}

		}

	}
	"contract_gladiator" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/mars/mars.vmdl"
		"ModelScale" "1.5"
		"SoundSet" "Hero_Mars"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "100"
		"Ability1" "contract_wrestle"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "6429"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "150"
		"MagicalArmor" "150"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "88"
		"AttackRate" "0.8"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "672"

				}
				"2" {
					"ItemDef" "671"

				}
				"3" {
					"ItemDef" "658"

				}
				"4" {
					"ItemDef" "670"

				}
				"5" {
					"ItemDef" "673"

				}

			}

		}

	}
	"contract_angle" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/skywrath_mage/skywrath_mage.vmdl"
		"ModelScale" "1.5"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "100"
		"Ability1" "contract_neutral_angle"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8183"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "200"
		"MagicalArmor" "200"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "75"
		"AttackRate" "0.8"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_skywrath_mage/skywrath_mage_base_attack.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "422"

				}
				"2" {
					"ItemDef" "420"

				}
				"3" {
					"ItemDef" "424"

				}
				"4" {
					"ItemDef" "421"

				}
				"5" {
					"ItemDef" "423"

				}
				"6" {
					"ItemDef" "425"

				}

			}

		}

	}
	"contract_beastboss" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/spirit_breaker/spirit_breaker.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "50"
		"Ability1" "contract_monster_commander"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "400"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "5625"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "200"
		"MagicalArmor" "200"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "70"
		"AttackRate" "1"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "250"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "18419"

				}
				"2" {
					"ItemDef" "106"

				}
				"3" {
					"ItemDef" "18418"

				}
				"4" {
					"ItemDef" "18400"

				}
				"5" {
					"ItemDef" "18398"

				}
				"6" {
					"ItemDef" "18416"

				}
				"7" {
					"ItemDef" "18399"

				}

			}

		}

	}
	"contract_deathmagician" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/undying/flesh_golem/ti9_cache_undying_carnivorous_parasitism_golem/ti9_cache_undying_carnivorous_parasitism_golem.vmdl"
		"ModelScale" "1.8"
		"SoundSet" "Hero_Undying"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "50"
		"Ability1" "contract_judge"
		"AbilityLayout" "4"
		"HealthBarOffset" "400"
		"MovementSpeed" "150"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "10000"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "50"
		"MagicalArmor" "50"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamage" "63"
		"AttackRate" "0.8"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1500"
		"HasInventory" "0"
		"RingRadius" "100"
		"Creature" {

		}

	}
	"contract_deadwings" {
		"UnitLabel" "elite"
		"vscripts" "npc/units/enemy/npc_unit_building_enemy"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/dragon_knight/aurora_warrior_set_dragon_style2_aurora_warrior_set/aurora_warrior_set_dragon_style2_aurora_warrior_set.vmdl"
		"ModelScale" "2"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"BoundsHullRadius" "100"
		"Ability1" "contract_death_wing"
		"AbilityLayout" "4"
		"HealthBarOffset" "500"
		"MovementSpeed" "275"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"StatusHealth" "8183"
		"StatusHealthRegen" "0"
		"StatusMana" "1000"
		"StatusManaRegen" "0"
		"PhysicalArmor" "100"
		"MagicalArmor" "100"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamage" "79"
		"AttackRate" "0.7"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_dragon_knight/dragon_knight_elder_dragon_attack_black.vpcf"
		"ProjectileSpeed" "1500"
		"HasInventory" "0"
		"RingRadius" "150"
		"Creature" {

		}

	}

}
