// generate with PIPIXIA's kv generator 

"building_unit_tower" {
	"building_hero_ember_spirit" {
		"CardName" "item_building_hero_ember_spirit"
		"HeroId" "103002"
		"vscripts" "npc/units/building/tower/building_hero_ember_spirit"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "spirits_2"
		"Relation_2" "flame_2"
		"level_upgrades" "16"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.4"
		"RingRadius" "70"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1150"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "129.6"
		"AttributeBaseAgility1" "133.2"
		"AttributeBaseIntelligence1" "108"
		"AttributeBaseStrength2" "195.84"
		"AttributeBaseAgility2" "201.28"
		"AttributeBaseIntelligence2" "163.2"
		"AttributeBaseStrength3" "248.832"
		"AttributeBaseAgility3" "255.744"
		"AttributeBaseIntelligence3" "207.36"
		"AttributeBaseStrength4" "315.072"
		"AttributeBaseAgility4" "323.824"
		"AttributeBaseIntelligence4" "262.56"
		"AttributeBaseStrength5" "401.184"
		"AttributeBaseAgility5" "412.328"
		"AttributeBaseIntelligence5" "334.32"
		"AttributeBaseStrength6" "1201.184"
		"AttributeBaseAgility6" "1212.328"
		"AttributeBaseIntelligence6" "1134.32"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_EmberSpirit"
		"HeroSelectSoundEffect" "Hero_EmberSpirit.Pick"
		"particle_folder" "particles/units/heroes/hero_ember_spirit"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_ember_spirit.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.6"
		"HasAggressiveStance" "1"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"AmbientModifiers" "modifier_ember_spirit_attack_sound"
		"Model" "models/heroes/ember_spirit/ember_spirit.vmdl"
		"ModelScale" "1.4"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "474"

				}
				"2" {
					"ItemDef" "473"

				}
				"3" {
					"ItemDef" "462"

				}
				"4" {
					"ItemDef" "472"

				}
				"5" {
					"ItemDef" "471"

				}
				"6" {
					"ItemDef" "469"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_lina" {
		"CardName" "item_building_hero_lina"
		"HeroId" "103004"
		"vscripts" "npc/units/building/tower/building_hero_lina"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "princess_3"
		"Relation_2" "fire_1"
		"level_upgrades" "13"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "50"
		"AttackDamageMax" "56"
		"AttackRate" "1.6"
		"AttackAnimationPoint" "0.65"
		"RingRadius" "70"
		"AttackRange" "1000"
		"AttackAcquisitionRange" "1900"
		"ProjectileModel" "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
		"ProjectileSpeed" "1000"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "111.6"
		"AttributeBaseAgility1" "118.8"
		"AttributeBaseIntelligence1" "133.2"
		"AttributeBaseStrength2" "168.64"
		"AttributeBaseAgility2" "179.52"
		"AttributeBaseIntelligence2" "201.28"
		"AttributeBaseStrength3" "214.272"
		"AttributeBaseAgility3" "228.096"
		"AttributeBaseIntelligence3" "255.744"
		"AttributeBaseStrength4" "271.312"
		"AttributeBaseAgility4" "288.816"
		"AttributeBaseIntelligence4" "323.824"
		"AttributeBaseStrength5" "345.464"
		"AttributeBaseAgility5" "367.752"
		"AttributeBaseIntelligence5" "412.328"
		"AttributeBaseStrength6" "1145.464"
		"AttributeBaseAgility6" "1167.752"
		"AttributeBaseIntelligence6" "1212.328"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Lina"
		"HeroSelectSoundEffect" "Hero_Lina.Pick"
		"particle_folder" "particles/units/heroes/hero_lina"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_lina.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_lina.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/lina/lina.vmdl"
		"ModelScale" "1.01"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "14251"

				}
				"2" {
					"ItemDef" "14250"

				}
				"3" {
					"ItemDef" "14248"

				}
				"4" {
					"ItemDef" "14247"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_axe" {
		"CardName" "item_building_hero_axe"
		"HeroId" "103005"
		"vscripts" "npc/units/building/tower/building_hero_axe"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "berserker_1"
		"Relation_2" "madman_1"
		"level_upgrades" "6"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "650"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "133.2"
		"AttributeBaseAgility1" "118.8"
		"AttributeBaseIntelligence1" "126"
		"AttributeBaseStrength2" "201.28"
		"AttributeBaseAgility2" "179.52"
		"AttributeBaseIntelligence2" "190.4"
		"AttributeBaseStrength3" "255.744"
		"AttributeBaseAgility3" "228.096"
		"AttributeBaseIntelligence3" "241.92"
		"AttributeBaseStrength4" "323.824"
		"AttributeBaseAgility4" "288.816"
		"AttributeBaseIntelligence4" "306.32"
		"AttributeBaseStrength5" "412.328"
		"AttributeBaseAgility5" "367.752"
		"AttributeBaseIntelligence5" "390.04"
		"AttributeBaseStrength6" "1212.328"
		"AttributeBaseAgility6" "1167.752"
		"AttributeBaseIntelligence6" "1190.04"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Axe"
		"HeroSelectSoundEffect" "Hero_Axe.Pick"
		"particle_folder" "particles/units/heroes/hero_axe"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_axe.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_axe.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"AmbientModifiers" "modifier_axe_attack_sound"
		"Model" "models/heroes/axe/axe.vmdl"
		"ModelScale" "1.2"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "9649"

				}
				"2" {
					"ItemDef" "5675"

				}
				"3" {
					"ItemDef" "9647"

				}
				"4" {
					"ItemDef" "9646"

				}
				"5" {
					"ItemDef" "9645"

				}
				"6" {
					"ItemDef" "12954"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_tinker" {
		"CardName" "item_building_hero_tinker"
		"HeroId" "103006"
		"vscripts" "npc/units/building/tower/building_hero_tinker"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "warframe_1"
		"Relation_2" "engineer_2"
		"level_upgrades" "15"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "77"
		"AttackDamageMax" "83"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.35"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_tinker/tinker_base_attack.vpcf"
		"ProjectileSpeed" "1200"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "111.6"
		"AttributeBaseAgility1" "111.6"
		"AttributeBaseIntelligence1" "136.8"
		"AttributeBaseStrength2" "168.64"
		"AttributeBaseAgility2" "168.64"
		"AttributeBaseIntelligence2" "206.72"
		"AttributeBaseStrength3" "214.272"
		"AttributeBaseAgility3" "214.272"
		"AttributeBaseIntelligence3" "262.656"
		"AttributeBaseStrength4" "271.312"
		"AttributeBaseAgility4" "271.312"
		"AttributeBaseIntelligence4" "332.576"
		"AttributeBaseStrength5" "345.464"
		"AttributeBaseAgility5" "345.464"
		"AttributeBaseIntelligence5" "423.472"
		"AttributeBaseStrength6" "1145.464"
		"AttributeBaseAgility6" "1145.464"
		"AttributeBaseIntelligence6" "1223.472"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Tinker"
		"HeroSelectSoundEffect" "Hero_Tinker.Pick"
		"particle_folder" "particles/units/heroes/hero_tinker"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_tinker.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_tinker.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.6"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/tinker/tinker.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "14067"

				}
				"2" {
					"ItemDef" "14066"

				}
				"3" {
					"ItemDef" "14065"

				}
				"4" {
					"ItemDef" "14064"

				}
				"5" {
					"ItemDef" "14063"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_sniper" {
		"CardName" "item_building_hero_sniper"
		"HeroId" "103010"
		"vscripts" "npc/units/building/tower/building_hero_sniper"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "gunner_1"
		"Relation_2" "dwarf_2"
		"level_upgrades" "4"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "120"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "262"
		"AttackDamageMax" "268"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.17"
		"RingRadius" "70"
		"AttackRange" "1150"
		"AttackAcquisitionRange" "1900"
		"ProjectileModel" "particles/units/heroes/hero_sniper/sniper_base_attack.vpcf"
		"ProjectileSpeed" "3000"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "115.2"
		"AttributeBaseAgility1" "140.4"
		"AttributeBaseIntelligence1" "122.4"
		"AttributeBaseStrength2" "174.08"
		"AttributeBaseAgility2" "212.16"
		"AttributeBaseIntelligence2" "184.96"
		"AttributeBaseStrength3" "221.184"
		"AttributeBaseAgility3" "269.568"
		"AttributeBaseIntelligence3" "235.008"
		"AttributeBaseStrength4" "280.064"
		"AttributeBaseAgility4" "341.328"
		"AttributeBaseIntelligence4" "297.568"
		"AttributeBaseStrength5" "356.608"
		"AttributeBaseAgility5" "434.616"
		"AttributeBaseIntelligence5" "378.896"
		"AttributeBaseStrength6" "1156.608"
		"AttributeBaseAgility6" "1234.616"
		"AttributeBaseIntelligence6" "1178.896"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Sniper"
		"HeroSelectSoundEffect" "Hero_Sniper.Pick"
		"particle_folder" "particles/units/heroes/hero_sniper"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_sniper.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"AmbientModifiers" "modifier_ambient_sniper | modifier_ambient_sniper_attack_speed"
		"Model" "models/heroes/sniper/sniper.vmdl"
		"ModelScale" "1.04"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "5040"

				}
				"2" {
					"ItemDef" "5041"

				}
				"3" {
					"ItemDef" "5038"

				}
				"4" {
					"ItemDef" "5039"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_storm_spirit" {
		"CardName" "item_building_hero_storm_spirit"
		"HeroId" "103015"
		"vscripts" "npc/units/building/tower/building_hero_storm_spirit"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "spirits_1"
		"Relation_2" "storm_1"
		"level_upgrades" "13"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" "particles/units/heroes/hero_stormspirit/stormspirit_base_attack.vpcf"
		"ProjectileSpeed" "1100"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "108"
		"AttributeBaseAgility1" "126"
		"AttributeBaseIntelligence1" "135"
		"AttributeBaseStrength2" "163.2"
		"AttributeBaseAgility2" "190.4"
		"AttributeBaseIntelligence2" "204"
		"AttributeBaseStrength3" "207.36"
		"AttributeBaseAgility3" "241.92"
		"AttributeBaseIntelligence3" "259.2"
		"AttributeBaseStrength4" "262.56"
		"AttributeBaseAgility4" "306.32"
		"AttributeBaseIntelligence4" "328.2"
		"AttributeBaseStrength5" "334.32"
		"AttributeBaseAgility5" "390.04"
		"AttributeBaseIntelligence5" "417.9"
		"AttributeBaseStrength6" "1134.32"
		"AttributeBaseAgility6" "1190.04"
		"AttributeBaseIntelligence6" "1217.9"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_StormSpirit"
		"HeroSelectSoundEffect" "Hero_StormSpirit.Pick"
		"particle_folder" "particles/units/heroes/hero_stormspirit"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_stormspirit.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_stormspirit.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/storm_spirit/storm_spirit.vmdl"
		"ModelScale" "1.35"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "308"

				}
				"2" {
					"ItemDef" "309"

				}
				"3" {
					"ItemDef" "310"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_death_prophet" {
		"CardName" "item_building_hero_death_prophet"
		"HeroId" "103025"
		"vscripts" "npc/units/building/tower/building_hero_death_prophet"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "god_2"
		"Relation_2" "furion_2"
		"level_upgrades" "12"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "84"
		"AttackDamageMax" "90"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.56"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_death_prophet/death_prophet_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "118.8"
		"AttributeBaseAgility1" "118.8"
		"AttributeBaseIntelligence1" "129.6"
		"AttributeBaseStrength2" "179.52"
		"AttributeBaseAgility2" "179.52"
		"AttributeBaseIntelligence2" "195.84"
		"AttributeBaseStrength3" "228.096"
		"AttributeBaseAgility3" "228.096"
		"AttributeBaseIntelligence3" "248.832"
		"AttributeBaseStrength4" "288.816"
		"AttributeBaseAgility4" "288.816"
		"AttributeBaseIntelligence4" "315.072"
		"AttributeBaseStrength5" "367.752"
		"AttributeBaseAgility5" "367.752"
		"AttributeBaseIntelligence5" "401.184"
		"AttributeBaseStrength6" "1167.752"
		"AttributeBaseAgility6" "1167.752"
		"AttributeBaseIntelligence6" "1201.184"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_DeathProphet"
		"HeroSelectSoundEffect" "Hero_DeathProphet.Pick"
		"particle_folder" "particles/units/heroes/hero_death_prophet"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_shadowshaman.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/death_prophet/death_prophet.vmdl"
		"ModelScale" "1.13"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "17847"

				}
				"2" {
					"ItemDef" "17846"

				}
				"3" {
					"ItemDef" "17845"

				}
				"4" {
					"ItemDef" "17844"

				}
				"5" {
					"ItemDef" "17843"

				}
				"6" {
					"ItemDef" "17842"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_luna" {
		"CardName" "item_building_hero_luna"
		"HeroId" "103026"
		"vscripts" "npc/units/building/tower/building_hero_luna"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "envoy_1"
		"Relation_2" "moonvalley_2"
		"level_upgrades" "8"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "217"
		"AttackDamageMax" "223"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.46"
		"RingRadius" "70"
		"AttackRange" "1000"
		"AttackAcquisitionRange" "1300"
		"ProjectileModel" "particles/units/heroes/hero_luna/luna_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "111.6"
		"AttributeBaseAgility1" "133.2"
		"AttributeBaseIntelligence1" "115.2"
		"AttributeBaseStrength2" "168.64"
		"AttributeBaseAgility2" "201.28"
		"AttributeBaseIntelligence2" "174.08"
		"AttributeBaseStrength3" "214.272"
		"AttributeBaseAgility3" "255.744"
		"AttributeBaseIntelligence3" "221.184"
		"AttributeBaseStrength4" "271.312"
		"AttributeBaseAgility4" "323.824"
		"AttributeBaseIntelligence4" "280.064"
		"AttributeBaseStrength5" "345.464"
		"AttributeBaseAgility5" "412.328"
		"AttributeBaseIntelligence5" "356.608"
		"AttributeBaseStrength6" "1145.464"
		"AttributeBaseAgility6" "1212.328"
		"AttributeBaseIntelligence6" "1156.608"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Luna"
		"HeroSelectSoundEffect" "Hero_Luna.Pick"
		"particle_folder" "particles/units/heroes/hero_luna"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_luna.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_luna.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.6"
		"HasAggressiveStance" "1"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/luna/luna.vmdl"
		"ModelScale" "0.94"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "6147"

				}
				"2" {
					"ItemDef" "6148"

				}
				"3" {
					"ItemDef" "6149"

				}
				"4" {
					"ItemDef" "6150"

				}
				"5" {
					"ItemDef" "6151"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_juggernaut" {
		"CardName" "item_building_hero_juggernaut"
		"HeroId" "103035"
		"vscripts" "npc/units/building/tower/building_hero_juggernaut"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "swordman_1"
		"Relation_2" "faceles_island_1"
		"level_upgrades" "8"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.33"
		"RingRadius" "70"
		"AttackRange" "750"
		"AttackAcquisitionRange" "1300"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "122.4"
		"AttributeBaseAgility1" "136.8"
		"AttributeBaseIntelligence1" "118.8"
		"AttributeBaseStrength2" "184.96"
		"AttributeBaseAgility2" "206.72"
		"AttributeBaseIntelligence2" "179.52"
		"AttributeBaseStrength3" "235.008"
		"AttributeBaseAgility3" "262.656"
		"AttributeBaseIntelligence3" "228.096"
		"AttributeBaseStrength4" "297.568"
		"AttributeBaseAgility4" "332.576"
		"AttributeBaseIntelligence4" "288.816"
		"AttributeBaseStrength5" "378.896"
		"AttributeBaseAgility5" "423.472"
		"AttributeBaseIntelligence5" "367.752"
		"AttributeBaseStrength6" "1178.896"
		"AttributeBaseAgility6" "1223.472"
		"AttributeBaseIntelligence6" "1167.752"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Juggernaut"
		"HeroSelectSoundEffect" "Hero_Juggernaut.Pick"
		"particle_folder" "particles/units/heroes/hero_juggernaut"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_juggernaut.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_juggernaut.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.6"
		"HasAggressiveStance" "1"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/juggernaut/juggernaut.vmdl"
		"ModelScale" "1.05"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "12770"

				}
				"2" {
					"ItemDef" "12769"

				}
				"3" {
					"ItemDef" "12768"

				}
				"4" {
					"ItemDef" "12767"

				}
				"5" {
					"ItemDef" "12766"

				}
				"6" {
					"ItemDef" "12765"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_lycan" {
		"CardName" "item_building_hero_lycan"
		"HeroId" "102046"
		"vscripts" "npc/units/building/tower/building_hero_lycan"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "wolf_1"
		"Relation_2" "former_1"
		"level_upgrades" "7"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.55"
		"RingRadius" "70"
		"AttackRange" "750"
		"AttackAcquisitionRange" "1300"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "151.2"
		"AttributeBaseAgility1" "111.6"
		"AttributeBaseIntelligence1" "115.2"
		"AttributeBaseStrength2" "228.48"
		"AttributeBaseAgility2" "168.64"
		"AttributeBaseIntelligence2" "174.08"
		"AttributeBaseStrength3" "290.304"
		"AttributeBaseAgility3" "214.272"
		"AttributeBaseIntelligence3" "221.184"
		"AttributeBaseStrength4" "367.584"
		"AttributeBaseAgility4" "271.312"
		"AttributeBaseIntelligence4" "280.064"
		"AttributeBaseStrength5" "468.048"
		"AttributeBaseAgility5" "345.464"
		"AttributeBaseIntelligence5" "356.608"
		"AttributeBaseStrength6" "1268.048"
		"AttributeBaseAgility6" "1145.464"
		"AttributeBaseIntelligence6" "1156.608"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Lycan"
		"HeroSelectSoundEffect" "Hero_Lycan.Pick"
		"particle_folder" "particles/units/heroes/hero_lycan"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_lycan.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_lycan.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/lycan/lycan.vmdl"
		"ModelScale" "1.05"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "210"

				}
				"2" {
					"ItemDef" "8660"

				}
				"3" {
					"ItemDef" "209"

				}
				"4" {
					"ItemDef" "206"

				}
				"5" {
					"ItemDef" "8649"

				}
				"6" {
					"ItemDef" "208"

				}
				"7" {
					"ItemDef" "207"

				}
				"8" {
					"ItemDef" "8369"

				}
				"9" {
					"ItemDef" "8369"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_venomancer" {
		"CardName" "item_building_hero_venomancer"
		"HeroId" "103054"
		"vscripts" "npc/units/building/tower/building_hero_venomancer"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "poison_2"
		"Relation_2" "warlock_1"
		"level_upgrades" "6"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "950"
		"AttackAcquisitionRange" "1800"
		"ProjectileModel" "particles/units/heroes/hero_venomancer/venomancer_base_attack.vpcf"
		"ProjectileSpeed" "1200"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "108"
		"AttributeBaseAgility1" "133.2"
		"AttributeBaseIntelligence1" "122.4"
		"AttributeBaseStrength2" "163.2"
		"AttributeBaseAgility2" "201.28"
		"AttributeBaseIntelligence2" "184.96"
		"AttributeBaseStrength3" "207.36"
		"AttributeBaseAgility3" "255.744"
		"AttributeBaseIntelligence3" "235.008"
		"AttributeBaseStrength4" "262.56"
		"AttributeBaseAgility4" "323.824"
		"AttributeBaseIntelligence4" "297.568"
		"AttributeBaseStrength5" "334.32"
		"AttributeBaseAgility5" "412.328"
		"AttributeBaseIntelligence5" "378.896"
		"AttributeBaseStrength6" "1134.32"
		"AttributeBaseAgility6" "1212.328"
		"AttributeBaseIntelligence6" "1178.896"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Venomancer"
		"HeroSelectSoundEffect" "Hero_Venomancer.Pick"
		"particle_folder" "particles/units/heroes/hero_venomancer"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_venomancer.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/venomancer/venomancer.vmdl"
		"ModelScale" "1.05"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "291"

				}
				"2" {
					"ItemDef" "293"

				}
				"3" {
					"ItemDef" "292"

				}
				"4" {
					"ItemDef" "295"

				}
				"5" {
					"ItemDef" "294"

				}
				"6" {
					"ItemDef" "518"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_disruptor" {
		"CardName" "item_building_hero_disruptor"
		"HeroId" "103064"
		"vscripts" "npc/units/building/tower/building_hero_disruptor"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "electricity_1"
		"Relation_2" "warlock_2"
		"level_upgrades" "5"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "950"
		"AttackAcquisitionRange" "1300"
		"ProjectileModel" "particles/units/heroes/hero_disruptor/disruptor_base_attack.vpcf"
		"ProjectileSpeed" "1200"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "113.4"
		"AttributeBaseAgility1" "113.4"
		"AttributeBaseIntelligence1" "135"
		"AttributeBaseStrength2" "171.36"
		"AttributeBaseAgility2" "171.36"
		"AttributeBaseIntelligence2" "204"
		"AttributeBaseStrength3" "217.728"
		"AttributeBaseAgility3" "217.728"
		"AttributeBaseIntelligence3" "259.2"
		"AttributeBaseStrength4" "275.688"
		"AttributeBaseAgility4" "275.688"
		"AttributeBaseIntelligence4" "328.2"
		"AttributeBaseStrength5" "351.036"
		"AttributeBaseAgility5" "351.036"
		"AttributeBaseIntelligence5" "417.9"
		"AttributeBaseStrength6" "1151.036"
		"AttributeBaseAgility6" "1151.036"
		"AttributeBaseIntelligence6" "1217.9"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Disruptor"
		"HeroSelectSoundEffect" "Hero_Disruptor.Pick"
		"particle_folder" "particles/units/heroes/hero_disruptor"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_disruptor.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_disruptor.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/disruptor/disruptor.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "142"

				}
				"2" {
					"ItemDef" "143"

				}
				"3" {
					"ItemDef" "144"

				}
				"4" {
					"ItemDef" "145"

				}
				"5" {
					"ItemDef" "146"

				}
				"6" {
					"ItemDef" "147"

				}
				"7" {
					"ItemDef" "525"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_chaos_knight" {
		"CardName" "item_building_hero_chaos_knight"
		"HeroId" "103102"
		"vscripts" "npc/units/building/tower/building_hero_chaos_knight"
		"Rarity" "SSR"
		"Population" "3"
		"level_upgrades" "6"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "750"
		"AttackAcquisitionRange" "1000"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "131.4"
		"AttributeBaseAgility1" "108"
		"AttributeBaseIntelligence1" "124.2"
		"AttributeBaseStrength2" "198.56"
		"AttributeBaseAgility2" "163.2"
		"AttributeBaseIntelligence2" "187.68"
		"AttributeBaseStrength3" "252.288"
		"AttributeBaseAgility3" "207.36"
		"AttributeBaseIntelligence3" "238.464"
		"AttributeBaseStrength4" "319.448"
		"AttributeBaseAgility4" "262.56"
		"AttributeBaseIntelligence4" "301.944"
		"AttributeBaseStrength5" "406.756"
		"AttributeBaseAgility5" "334.32"
		"AttributeBaseIntelligence5" "384.468"
		"AttributeBaseStrength6" "1206.756"
		"AttributeBaseAgility6" "1134.32"
		"AttributeBaseIntelligence6" "1184.468"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_ChaosKnight"
		"HeroSelectSoundEffect" "Hero_ChaosKnight.Pick"
		"particle_folder" "particles/units/heroes/hero_chaos_knight"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_chaos_knight.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_chaos_knight.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/chaos_knight/chaos_knight.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "181"

				}
				"2" {
					"ItemDef" "183"

				}
				"3" {
					"ItemDef" "184"

				}
				"4" {
					"ItemDef" "185"

				}
				"5" {
					"ItemDef" "186"

				}

			}

		}
		"IsShow" "0"

	}
	"building_hero_winter_wyvern" {
		"CardName" "item_building_hero_winter_wyvern"
		"HeroId" "103103"
		"vscripts" "npc/units/building/tower/building_hero_winter_wyvern"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "dragon_1"
		"Relation_2" "frostfield_1"
		"level_upgrades" "6"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "262"
		"AttackDamageMax" "268"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.25"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" "particles/units/heroes/hero_winter_wyvern/winter_wyvern_base_attack.vpcf"
		"ProjectileSpeed" "700"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "108"
		"AttributeBaseAgility1" "126"
		"AttributeBaseIntelligence1" "135"
		"AttributeBaseStrength2" "163.2"
		"AttributeBaseAgility2" "190.4"
		"AttributeBaseIntelligence2" "204"
		"AttributeBaseStrength3" "207.36"
		"AttributeBaseAgility3" "241.92"
		"AttributeBaseIntelligence3" "259.2"
		"AttributeBaseStrength4" "262.56"
		"AttributeBaseAgility4" "306.32"
		"AttributeBaseIntelligence4" "328.2"
		"AttributeBaseStrength5" "334.32"
		"AttributeBaseAgility5" "390.04"
		"AttributeBaseIntelligence5" "417.9"
		"AttributeBaseStrength6" "1134.32"
		"AttributeBaseAgility6" "1190.04"
		"AttributeBaseIntelligence6" "1217.9"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Winter_Wyvern"
		"HeroSelectSoundEffect" "Hero_Winter_Wyvern.Pick"
		"particle_folder" "particles/units/heroes/hero_winter_wyvern"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_winter_wyvern.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_winter_wyvern.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/winterwyvern/winterwyvern.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "551"

				}
				"2" {
					"ItemDef" "552"

				}
				"3" {
					"ItemDef" "553"

				}
				"4" {
					"ItemDef" "7291"

				}
				"5" {
					"ItemDef" "7292"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_lone_druid" {
		"CardName" "item_building_hero_lone_druid"
		"HeroId" "103104"
		"vscripts" "npc/units/building/tower/building_hero_lone_druid"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "former_2"
		"Relation_2" "forest_2"
		"level_upgrades" "8"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.2"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/units/heroes/hero_lone_druid/lone_druid_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "126"
		"AttributeBaseAgility1" "135"
		"AttributeBaseIntelligence1" "108"
		"AttributeBaseStrength2" "190.4"
		"AttributeBaseAgility2" "204"
		"AttributeBaseIntelligence2" "163.2"
		"AttributeBaseStrength3" "241.92"
		"AttributeBaseAgility3" "259.2"
		"AttributeBaseIntelligence3" "207.36"
		"AttributeBaseStrength4" "306.32"
		"AttributeBaseAgility4" "328.2"
		"AttributeBaseIntelligence4" "262.56"
		"AttributeBaseStrength5" "390.04"
		"AttributeBaseAgility5" "417.9"
		"AttributeBaseIntelligence5" "334.32"
		"AttributeBaseStrength6" "1190.04"
		"AttributeBaseAgility6" "1217.9"
		"AttributeBaseIntelligence6" "1134.32"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_LoneDruid"
		"HeroSelectSoundEffect" "Hero_LoneDruid.Pick"
		"particle_folder" "particles/units/heroes/hero_lone_druid"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_lone_druid.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_lone_druid.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/lone_druid/lone_druid.vmdl"
		"ModelScale" "0.79"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "108"

				}
				"2" {
					"ItemDef" "109"

				}
				"3" {
					"ItemDef" "110"

				}
				"4" {
					"ItemDef" "8368"

				}
				"5" {
					"ItemDef" "219"

				}
				"6" {
					"ItemDef" "8648"

				}
				"7" {
					"ItemDef" "107"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_alchemist" {
		"CardName" "item_building_hero_alchemist"
		"HeroId" "103105"
		"vscripts" "npc/units/building/tower/building_hero_alchemist"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "goblin_1"
		"Relation_2" "fat_3"
		"level_upgrades" "8"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.2"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1100"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "140.4"
		"AttributeBaseAgility1" "129.6"
		"AttributeBaseIntelligence1" "99"
		"AttributeBaseStrength2" "212.16"
		"AttributeBaseAgility2" "195.84"
		"AttributeBaseIntelligence2" "149.6"
		"AttributeBaseStrength3" "269.568"
		"AttributeBaseAgility3" "248.832"
		"AttributeBaseIntelligence3" "190.08"
		"AttributeBaseStrength4" "341.328"
		"AttributeBaseAgility4" "315.072"
		"AttributeBaseIntelligence4" "240.68"
		"AttributeBaseStrength5" "434.616"
		"AttributeBaseAgility5" "401.184"
		"AttributeBaseIntelligence5" "306.46"
		"AttributeBaseStrength6" "1234.616"
		"AttributeBaseAgility6" "1201.184"
		"AttributeBaseIntelligence6" "1106.46"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/alchemist/alchemist.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "117"

				}
				"2" {
					"ItemDef" "118"

				}
				"3" {
					"ItemDef" "119"

				}
				"4" {
					"ItemDef" "120"

				}
				"5" {
					"ItemDef" "121"

				}
				"6" {
					"ItemDef" "122"

				}
				"7" {
					"ItemDef" "123"

				}
				"8" {
					"ItemDef" "124"

				}
				"9" {
					"ItemDef" "125"

				}
				"10" {
					"ItemDef" "738"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_templar_assassin" {
		"CardName" "item_building_hero_templar_assassin"
		"HeroId" "103106"
		"vscripts" "npc/units/building/tower/building_hero_templar_assassin"
		"Rarity" "SSR"
		"Population" "3"
		"Relation_1" "templar_1"
		"Relation_2" "assassin_1"
		"level_upgrades" "14"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "600"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/units/heroes/hero_templar_assassin/templar_assassin_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "133.2"
		"AttributeBaseAgility1" "136.8"
		"AttributeBaseIntelligence1" "100.8"
		"AttributeBaseStrength2" "201.28"
		"AttributeBaseAgility2" "206.72"
		"AttributeBaseIntelligence2" "152.32"
		"AttributeBaseStrength3" "255.744"
		"AttributeBaseAgility3" "262.656"
		"AttributeBaseIntelligence3" "193.536"
		"AttributeBaseStrength4" "323.824"
		"AttributeBaseAgility4" "332.576"
		"AttributeBaseIntelligence4" "245.056"
		"AttributeBaseStrength5" "412.328"
		"AttributeBaseAgility5" "423.472"
		"AttributeBaseIntelligence5" "312.032"
		"AttributeBaseStrength6" "1212.328"
		"AttributeBaseAgility6" "1223.472"
		"AttributeBaseIntelligence6" "1112.032"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_TemplarAssassin"
		"HeroSelectSoundEffect" "Hero_TemplarAssassin.Pick"
		"particle_folder" "particles/units/heroes/hero_templar_assassin"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_templar_assassin.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/lanaya/lanaya.vmdl"
		"ModelScale" "0.88"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "175"

				}
				"2" {
					"ItemDef" "174"

				}
				"3" {
					"ItemDef" "173"

				}
				"4" {
					"ItemDef" "603"

				}
				"5" {
					"ItemDef" "514"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_furion" {
		"CardName" "item_building_hero_furion"
		"HeroId" "102001"
		"vscripts" "npc/units/building/tower/building_hero_furion"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "forest_1"
		"Relation_2" "furion_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.4"
		"AttackAnimationPoint" "0.4"
		"RingRadius" "70"
		"AttackRange" "1000"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
		"ProjectileSpeed" "600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "74.8"
		"AttributeBaseAgility1" "68.2"
		"AttributeBaseIntelligence1" "82.5"
		"AttributeBaseStrength2" "113.56"
		"AttributeBaseAgility2" "103.54"
		"AttributeBaseIntelligence2" "125.25"
		"AttributeBaseStrength3" "144.568"
		"AttributeBaseAgility3" "131.812"
		"AttributeBaseIntelligence3" "159.45"
		"AttributeBaseStrength4" "183.328"
		"AttributeBaseAgility4" "167.152"
		"AttributeBaseIntelligence4" "202.2"
		"AttributeBaseStrength5" "233.716"
		"AttributeBaseAgility5" "213.094"
		"AttributeBaseIntelligence5" "257.775"
		"AttributeBaseStrength6" "733.716"
		"AttributeBaseAgility6" "713.094"
		"AttributeBaseIntelligence6" "757.775"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Furion"
		"HeroSelectSoundEffect" "Hero_Furion.Pick"
		"particle_folder" "particles/units/heroes/hero_furion"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_furion.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_furion.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.6"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/furion/furion.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "0.79"

				}
				"2" {
					"ItemDef" "33"

				}
				"3" {
					"ItemDef" "49"

				}
				"4" {
					"ItemDef" "30"

				}
				"5" {
					"ItemDef" "32"

				}
				"6" {
					"ItemDef" "8364"

				}
				"7" {
					"ItemDef" "31"

				}
				"8" {
					"ItemDef" "29"

				}
				"9" {
					"ItemDef" "29"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_shredder" {
		"CardName" "item_building_hero_shredder"
		"HeroId" "102008"
		"vscripts" "npc/units/building/tower/building_hero_shredder"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "warframe_2"
		"Relation_2" "madman_2"
		"level_upgrades" "3"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.36"
		"RingRadius" "70"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "83.6"
		"AttributeBaseAgility1" "68.2"
		"AttributeBaseIntelligence1" "68.2"
		"AttributeBaseStrength2" "126.92"
		"AttributeBaseAgility2" "103.54"
		"AttributeBaseIntelligence2" "103.54"
		"AttributeBaseStrength3" "161.576"
		"AttributeBaseAgility3" "131.812"
		"AttributeBaseIntelligence3" "131.812"
		"AttributeBaseStrength4" "204.896"
		"AttributeBaseAgility4" "167.152"
		"AttributeBaseIntelligence4" "167.152"
		"AttributeBaseStrength5" "261.212"
		"AttributeBaseAgility5" "213.094"
		"AttributeBaseIntelligence5" "213.094"
		"AttributeBaseStrength6" "761.212"
		"AttributeBaseAgility6" "713.094"
		"AttributeBaseIntelligence6" "713.094"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Shredder"
		"HeroSelectSoundEffect" "Hero_Shredder.Pick"
		"particle_folder" "particles/units/heroes/hero_shredder"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_shredder.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_shredder.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"AmbientModifiers" "modifier_ambient_shredder"
		"Model" "models/heroes/shredder/shredder.vmdl"
		"ModelScale" "1.025"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "7672"

				}
				"2" {
					"ItemDef" "7673"

				}
				"3" {
					"ItemDef" "7674"

				}
				"4" {
					"ItemDef" "7680"

				}
				"5" {
					"ItemDef" "7681"

				}
				"6" {
					"ItemDef" "7682"

				}
				"7" {
					"ItemDef" "11649"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_mirana" {
		"CardName" "item_building_hero_mirana"
		"HeroId" "102012"
		"vscripts" "npc/units/building/tower/building_hero_mirana"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "princess_1"
		"Relation_2" "moonvalley_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "81"
		"AttackDamageMax" "87"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.35"
		"RingRadius" "70"
		"AttackRange" "950"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_mirana/mirana_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "70.4"
		"AttributeBaseAgility1" "81.4"
		"AttributeBaseIntelligence1" "72.6"
		"AttributeBaseStrength2" "106.88"
		"AttributeBaseAgility2" "123.58"
		"AttributeBaseIntelligence2" "110.22"
		"AttributeBaseStrength3" "136.064"
		"AttributeBaseAgility3" "157.324"
		"AttributeBaseIntelligence3" "140.316"
		"AttributeBaseStrength4" "172.544"
		"AttributeBaseAgility4" "199.504"
		"AttributeBaseIntelligence4" "177.936"
		"AttributeBaseStrength5" "219.968"
		"AttributeBaseAgility5" "254.338"
		"AttributeBaseIntelligence5" "226.842"
		"AttributeBaseStrength6" "719.968"
		"AttributeBaseAgility6" "754.338"
		"AttributeBaseIntelligence6" "726.842"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Mirana"
		"HeroSelectSoundEffect" "Hero_Mirana.Pick"
		"particle_folder" "particles/units/heroes/hero_mirana"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_mirana.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/mirana/mirana.vmdl"
		"ModelScale" "1.05"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "6440"

				}
				"2" {
					"ItemDef" "6437"

				}
				"3" {
					"ItemDef" "6445"

				}
				"4" {
					"ItemDef" "6448"

				}
				"5" {
					"ItemDef" "6446"

				}
				"6" {
					"ItemDef" "6438"

				}
				"7" {
					"ItemDef" "6439"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_void_spirit" {
		"CardName" "item_building_hero_void_spirit"
		"HeroId" "102016"
		"vscripts" "npc/units/building/tower/building_hero_void_spirit"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "spirits_3"
		"Relation_2" "void_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.35"
		"RingRadius" "40"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1150"
		"ProjectileSpeed" "1100"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "73.7"
		"AttributeBaseAgility1" "74.8"
		"AttributeBaseIntelligence1" "75.9"
		"AttributeBaseStrength2" "111.89"
		"AttributeBaseAgility2" "113.56"
		"AttributeBaseIntelligence2" "115.23"
		"AttributeBaseStrength3" "142.442"
		"AttributeBaseAgility3" "144.568"
		"AttributeBaseIntelligence3" "146.694"
		"AttributeBaseStrength4" "180.632"
		"AttributeBaseAgility4" "183.328"
		"AttributeBaseIntelligence4" "186.024"
		"AttributeBaseStrength5" "230.279"
		"AttributeBaseAgility5" "233.716"
		"AttributeBaseIntelligence5" "237.153"
		"AttributeBaseStrength6" "730.279"
		"AttributeBaseAgility6" "733.716"
		"AttributeBaseIntelligence6" "737.153"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_VoidSpirit"
		"HeroSelectSoundEffect" "Hero_VoidSpirit.Pick"
		"particle_folder" "particles/units/heroes/hero_void_spirit"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_void_spirit.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_void_spirit.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/void_spirit/void_spirit.vmdl"
		"ModelScale" "1.05"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "686"

				}
				"2" {
					"ItemDef" "687"

				}
				"3" {
					"ItemDef" "688"

				}
				"4" {
					"ItemDef" "689"

				}
				"5" {
					"ItemDef" "690"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_bounty_hunter" {
		"CardName" "item_building_hero_bounty_hunter"
		"HeroId" "102022"
		"vscripts" "npc/units/building/tower/building_hero_bounty_hunter"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "thief_1"
		"Relation_2" "predator_1"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "222"
		"AttackDamageMax" "228"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.59"
		"RingRadius" "70"
		"AttackRange" "750"
		"AttackAcquisitionRange" "1300"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "68.2"
		"AttributeBaseAgility1" "90.2"
		"AttributeBaseIntelligence1" "66"
		"AttributeBaseStrength2" "103.54"
		"AttributeBaseAgility2" "136.94"
		"AttributeBaseIntelligence2" "100.2"
		"AttributeBaseStrength3" "131.812"
		"AttributeBaseAgility3" "174.332"
		"AttributeBaseIntelligence3" "127.56"
		"AttributeBaseStrength4" "167.152"
		"AttributeBaseAgility4" "221.072"
		"AttributeBaseIntelligence4" "161.76"
		"AttributeBaseStrength5" "213.094"
		"AttributeBaseAgility5" "281.834"
		"AttributeBaseIntelligence5" "206.22"
		"AttributeBaseStrength6" "713.094"
		"AttributeBaseAgility6" "781.834"
		"AttributeBaseIntelligence6" "706.22"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_BountyHunter"
		"HeroSelectSoundEffect" "Hero_BountyHunter.Pick"
		"particle_folder" "particles/units/heroes/hero_bounty_hunter"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_bounty_hunter.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_bounty_hunter.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.6"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"AmbientModifiers" "modifier_bounty_hunter_track_bounty"
		"Model" "models/heroes/bounty_hunter/bounty_hunter.vmdl"
		"ModelScale" "1.07"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "54"

				}
				"2" {
					"ItemDef" "50"

				}
				"3" {
					"ItemDef" "51"

				}
				"4" {
					"ItemDef" "52"

				}
				"5" {
					"ItemDef" "55"

				}
				"6" {
					"ItemDef" "564"

				}
				"7" {
					"ItemDef" "53"

				}
				"8" {
					"ItemDef" "7934"

				}
				"9" {
					"ItemDef" "7934"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_dragon_knight" {
		"CardName" "item_building_hero_dragon_knight"
		"HeroId" "102028"
		"vscripts" "npc/units/building/tower/building_hero_dragon_knight"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "hostile_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "162"
		"AttackDamageMax" "168"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "850"
		"AttackAcquisitionRange" "1150"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "91.3"
		"AttributeBaseAgility1" "66"
		"AttributeBaseIntelligence1" "66"
		"AttributeBaseStrength2" "138.61"
		"AttributeBaseAgility2" "100.2"
		"AttributeBaseIntelligence2" "100.2"
		"AttributeBaseStrength3" "176.458"
		"AttributeBaseAgility3" "127.56"
		"AttributeBaseIntelligence3" "127.56"
		"AttributeBaseStrength4" "223.768"
		"AttributeBaseAgility4" "161.76"
		"AttributeBaseIntelligence4" "161.76"
		"AttributeBaseStrength5" "285.271"
		"AttributeBaseAgility5" "206.22"
		"AttributeBaseIntelligence5" "206.22"
		"AttributeBaseStrength6" "785.271"
		"AttributeBaseAgility6" "706.22"
		"AttributeBaseIntelligence6" "706.22"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_DragonKnight"
		"HeroSelectSoundEffect" "Hero_DragonKnight.Pick"
		"particle_folder" "particles/units/heroes/hero_dragon_knight"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_dragon_knight.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_dragon_knight.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/dragon_knight/dragon_knight.vmdl"
		"ModelScale" "1.04"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "67"

				}
				"2" {
					"ItemDef" "66"

				}
				"3" {
					"ItemDef" "8647"

				}
				"4" {
					"ItemDef" "63"

				}
				"5" {
					"ItemDef" "65"

				}
				"6" {
					"ItemDef" "68"

				}
				"7" {
					"ItemDef" "64"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_slardar" {
		"CardName" "item_building_hero_slardar"
		"HeroId" "102029"
		"vscripts" "npc/units/building/tower/building_hero_slardar"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "guard_1"
		"Relation_2" "sea_1"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.36"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1150"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "81.4"
		"AttributeBaseAgility1" "70.4"
		"AttributeBaseIntelligence1" "68.2"
		"AttributeBaseStrength2" "123.58"
		"AttributeBaseAgility2" "106.88"
		"AttributeBaseIntelligence2" "103.54"
		"AttributeBaseStrength3" "157.324"
		"AttributeBaseAgility3" "136.064"
		"AttributeBaseIntelligence3" "131.812"
		"AttributeBaseStrength4" "199.504"
		"AttributeBaseAgility4" "172.544"
		"AttributeBaseIntelligence4" "167.152"
		"AttributeBaseStrength5" "254.338"
		"AttributeBaseAgility5" "219.968"
		"AttributeBaseIntelligence5" "213.094"
		"AttributeBaseStrength6" "754.338"
		"AttributeBaseAgility6" "719.968"
		"AttributeBaseIntelligence6" "713.094"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Slardar"
		"HeroSelectSoundEffect" "Hero_Slardar.Pick"
		"particle_folder" "particles/units/heroes/hero_slardar"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_slardar.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_slardar.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/slardar/slardar.vmdl"
		"ModelScale" "1.08"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "275"

				}
				"2" {
					"ItemDef" "274"

				}
				"3" {
					"ItemDef" "273"

				}
				"4" {
					"ItemDef" "512"

				}
				"5" {
					"ItemDef" "276"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_slark" {
		"CardName" "item_building_hero_slark"
		"HeroId" "102030"
		"vscripts" "npc/units/building/tower/building_hero_slark"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "predator_2"
		"Relation_2" "sea_2"
		"level_upgrades" "3"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1150"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "66"
		"AttributeBaseAgility1" "83.6"
		"AttributeBaseIntelligence1" "70.4"
		"AttributeBaseStrength2" "100.2"
		"AttributeBaseAgility2" "126.92"
		"AttributeBaseIntelligence2" "106.88"
		"AttributeBaseStrength3" "127.56"
		"AttributeBaseAgility3" "161.576"
		"AttributeBaseIntelligence3" "136.064"
		"AttributeBaseStrength4" "161.76"
		"AttributeBaseAgility4" "204.896"
		"AttributeBaseIntelligence4" "172.544"
		"AttributeBaseStrength5" "206.22"
		"AttributeBaseAgility5" "261.212"
		"AttributeBaseIntelligence5" "219.968"
		"AttributeBaseStrength6" "706.22"
		"AttributeBaseAgility6" "761.212"
		"AttributeBaseIntelligence6" "719.968"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Slark"
		"HeroSelectSoundEffect" "Hero_Slark.Pick"
		"particle_folder" "particles/units/heroes/hero_slark"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_slark.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_slark.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.7"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/slark/slark.vmdl"
		"ModelScale" "1.1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "356"

				}
				"2" {
					"ItemDef" "336"

				}
				"3" {
					"ItemDef" "353"

				}
				"4" {
					"ItemDef" "355"

				}
				"5" {
					"ItemDef" "538"

				}
				"6" {
					"ItemDef" "8366"

				}
				"7" {
					"ItemDef" "354"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_ursa" {
		"CardName" "item_building_hero_ursa"
		"HeroId" "102032"
		"vscripts" "npc/units/building/tower/building_hero_ursa"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "bearman_1"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "750"
		"AttackAcquisitionRange" "1150"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "70.4"
		"AttributeBaseAgility1" "85.8"
		"AttributeBaseIntelligence1" "68.2"
		"AttributeBaseStrength2" "106.88"
		"AttributeBaseAgility2" "130.26"
		"AttributeBaseIntelligence2" "103.54"
		"AttributeBaseStrength3" "136.064"
		"AttributeBaseAgility3" "165.828"
		"AttributeBaseIntelligence3" "131.812"
		"AttributeBaseStrength4" "172.544"
		"AttributeBaseAgility4" "210.288"
		"AttributeBaseIntelligence4" "167.152"
		"AttributeBaseStrength5" "219.968"
		"AttributeBaseAgility5" "268.086"
		"AttributeBaseIntelligence5" "213.094"
		"AttributeBaseStrength6" "719.968"
		"AttributeBaseAgility6" "768.086"
		"AttributeBaseIntelligence6" "713.094"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Ursa"
		"HeroSelectSoundEffect" "Hero_Ursa.Pick"
		"particle_folder" "particles/units/heroes/hero_ursa"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_ursa.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_ursa.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/ursa/ursa.vmdl"
		"ModelScale" "0.94"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "4302"

				}
				"2" {
					"ItemDef" "4303"

				}
				"3" {
					"ItemDef" "4304"

				}
				"4" {
					"ItemDef" "4305"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_crystal_maiden" {
		"CardName" "item_building_hero_crystal_maiden"
		"HeroId" "102034"
		"vscripts" "npc/units/building/tower/building_hero_crystal_maiden"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "princess_2"
		"Relation_2" "frostfield_2"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "84"
		"AttackDamageMax" "90"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.45"
		"RingRadius" "70"
		"AttackRange" "950"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_crystalmaiden/maiden_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "68.2"
		"AttributeBaseAgility1" "63.8"
		"AttributeBaseIntelligence1" "88"
		"AttributeBaseStrength2" "103.54"
		"AttributeBaseAgility2" "96.86"
		"AttributeBaseIntelligence2" "133.6"
		"AttributeBaseStrength3" "131.812"
		"AttributeBaseAgility3" "123.308"
		"AttributeBaseIntelligence3" "170.08"
		"AttributeBaseStrength4" "167.152"
		"AttributeBaseAgility4" "156.368"
		"AttributeBaseIntelligence4" "215.68"
		"AttributeBaseStrength5" "213.094"
		"AttributeBaseAgility5" "199.346"
		"AttributeBaseIntelligence5" "274.96"
		"AttributeBaseStrength6" "713.094"
		"AttributeBaseAgility6" "699.346"
		"AttributeBaseIntelligence6" "774.96"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "hero_Crystal"
		"HeroSelectSoundEffect" "Hero_CrystalMaiden.Pick"
		"particle_folder" "particles/units/heroes/hero_crystalmaiden"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_crystalmaiden.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/crystal_maiden/crystal_maiden.vmdl"
		"ModelScale" "1.01"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "6784"

				}
				"2" {
					"ItemDef" "4386"

				}
				"3" {
					"ItemDef" "4389"

				}
				"4" {
					"ItemDef" "4420"

				}
				"5" {
					"ItemDef" "4540"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_ogre_magi" {
		"CardName" "item_building_hero_ogre_magi"
		"HeroId" "102036"
		"vscripts" "npc/units/building/tower/building_hero_ogre_magi"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "fat_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "259"
		"AttackDamageMax" "265"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "750"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "66"
		"AttributeBaseAgility1" "66"
		"AttributeBaseIntelligence1" "88"
		"AttributeBaseStrength2" "100.2"
		"AttributeBaseAgility2" "100.2"
		"AttributeBaseIntelligence2" "133.6"
		"AttributeBaseStrength3" "127.56"
		"AttributeBaseAgility3" "127.56"
		"AttributeBaseIntelligence3" "170.08"
		"AttributeBaseStrength4" "161.76"
		"AttributeBaseAgility4" "161.76"
		"AttributeBaseIntelligence4" "215.68"
		"AttributeBaseStrength5" "206.22"
		"AttributeBaseAgility5" "206.22"
		"AttributeBaseIntelligence5" "274.96"
		"AttributeBaseStrength6" "706.22"
		"AttributeBaseAgility6" "706.22"
		"AttributeBaseIntelligence6" "774.96"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_OgreMagi"
		"HeroSelectSoundEffect" "Hero_OgreMagi.Pick"
		"particle_folder" "particles/units/heroes/hero_ogre_magi"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_ogre_magi.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.6"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/ogre_magi/ogre_magi.vmdl"
		"ModelScale" "1.13"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "136"

				}
				"2" {
					"ItemDef" "105"

				}
				"3" {
					"ItemDef" "534"

				}
				"4" {
					"ItemDef" "134"

				}
				"5" {
					"ItemDef" "135"

				}
				"6" {
					"ItemDef" "133"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_sven" {
		"CardName" "item_building_hero_sven"
		"HeroId" "102037"
		"vscripts" "npc/units/building/tower/building_hero_sven"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "warrior_1"
		"Relation_2" "faceles_island_2"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "262"
		"AttackDamageMax" "268"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.4"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1300"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "83.6"
		"AttributeBaseAgility1" "70.4"
		"AttributeBaseIntelligence1" "70.4"
		"AttributeBaseStrength2" "126.92"
		"AttributeBaseAgility2" "106.88"
		"AttributeBaseIntelligence2" "106.88"
		"AttributeBaseStrength3" "161.576"
		"AttributeBaseAgility3" "136.064"
		"AttributeBaseIntelligence3" "136.064"
		"AttributeBaseStrength4" "204.896"
		"AttributeBaseAgility4" "172.544"
		"AttributeBaseIntelligence4" "172.544"
		"AttributeBaseStrength5" "261.212"
		"AttributeBaseAgility5" "219.968"
		"AttributeBaseIntelligence5" "219.968"
		"AttributeBaseStrength6" "761.212"
		"AttributeBaseAgility6" "719.968"
		"AttributeBaseIntelligence6" "719.968"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Sven"
		"HeroSelectSoundEffect" "Hero_Sven.Pick"
		"particle_folder" "particles/units/heroes/hero_sven"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_sven.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_sven.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/sven/sven.vmdl"
		"ModelScale" "1.04"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "17673"

				}
				"2" {
					"ItemDef" "17672"

				}
				"3" {
					"ItemDef" "17671"

				}
				"4" {
					"ItemDef" "17670"

				}
				"5" {
					"ItemDef" "17669"

				}
				"6" {
					"ItemDef" "17668"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_medusa" {
		"CardName" "item_building_hero_medusa"
		"HeroId" "102038"
		"vscripts" "npc/units/building/tower/building_hero_medusa"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "gunner_2"
		"Relation_2" "snake_1"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "262"
		"AttackDamageMax" "268"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_medusa/medusa_base_attack.vpcf"
		"ProjectileSpeed" "1200"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "70.4"
		"AttributeBaseAgility1" "79.2"
		"AttributeBaseIntelligence1" "70.4"
		"AttributeBaseStrength2" "106.88"
		"AttributeBaseAgility2" "120.24"
		"AttributeBaseIntelligence2" "106.88"
		"AttributeBaseStrength3" "136.064"
		"AttributeBaseAgility3" "153.072"
		"AttributeBaseIntelligence3" "136.064"
		"AttributeBaseStrength4" "172.544"
		"AttributeBaseAgility4" "194.112"
		"AttributeBaseIntelligence4" "172.544"
		"AttributeBaseStrength5" "219.968"
		"AttributeBaseAgility5" "247.464"
		"AttributeBaseIntelligence5" "219.968"
		"AttributeBaseStrength6" "719.968"
		"AttributeBaseAgility6" "747.464"
		"AttributeBaseIntelligence6" "719.968"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Medusa"
		"HeroSelectSoundEffect" "Hero_Medusa.Pick"
		"particle_folder" "particles/units/heroes/hero_medusa"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_medusa.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_medusa.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/medusa/medusa.vmdl"
		"ModelScale" "1.05"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "8191"

				}
				"2" {
					"ItemDef" "8193"

				}
				"3" {
					"ItemDef" "8194"

				}
				"4" {
					"ItemDef" "8195"

				}
				"5" {
					"ItemDef" "8196"

				}
				"6" {
					"ItemDef" "11238"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_leshrac" {
		"CardName" "item_building_hero_leshrac"
		"HeroId" "102041"
		"vscripts" "npc/units/building/tower/building_hero_leshrac"
		"Rarity" "SR"
		"Population" "2"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.4"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" "particles/units/heroes/hero_leshrac/leshrac_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "33"
		"AttributeBaseAgility1" "33"
		"AttributeBaseIntelligence1" "44"
		"AttributeBaseStrength2" "50.1"
		"AttributeBaseAgility2" "50.1"
		"AttributeBaseIntelligence2" "66.8"
		"AttributeBaseStrength3" "63.78"
		"AttributeBaseAgility3" "63.78"
		"AttributeBaseIntelligence3" "85.04"
		"AttributeBaseStrength4" "77.46"
		"AttributeBaseAgility4" "77.46"
		"AttributeBaseIntelligence4" "103.28"
		"AttributeBaseStrength5" "99.69"
		"AttributeBaseAgility5" "99.69"
		"AttributeBaseIntelligence5" "132.92"
		"AttributeBaseStrength6" "599.69"
		"AttributeBaseAgility6" "599.69"
		"AttributeBaseIntelligence6" "632.92"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Leshrac"
		"HeroSelectSoundEffect" "Hero_Leshrac.Pick"
		"particle_folder" "particles/units/heroes/hero_leshrac"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_leshrac.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/leshrac/leshrac.vmdl"
		"ModelScale" "1.04"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "346"

				}
				"2" {
					"ItemDef" "347"

				}
				"3" {
					"ItemDef" "529"

				}
				"4" {
					"ItemDef" "570"

				}
				"5" {
					"ItemDef" "345"

				}
				"6" {
					"ItemDef" "591"

				}

			}

		}
		"IsShow" "0"

	}
	"building_hero_centaur" {
		"CardName" "item_building_hero_centaur"
		"HeroId" "102042"
		"vscripts" "npc/units/building/tower/building_hero_centaur"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "centaur_1"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "850"
		"AttackAcquisitionRange" "1150"
		"ProjectileModel" "particles/base_attacks/ranged_hero.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "83.6"
		"AttributeBaseAgility1" "79.2"
		"AttributeBaseIntelligence1" "66"
		"AttributeBaseStrength2" "126.92"
		"AttributeBaseAgility2" "120.24"
		"AttributeBaseIntelligence2" "100.2"
		"AttributeBaseStrength3" "161.576"
		"AttributeBaseAgility3" "153.072"
		"AttributeBaseIntelligence3" "127.56"
		"AttributeBaseStrength4" "204.896"
		"AttributeBaseAgility4" "194.112"
		"AttributeBaseIntelligence4" "161.76"
		"AttributeBaseStrength5" "261.212"
		"AttributeBaseAgility5" "247.464"
		"AttributeBaseIntelligence5" "206.22"
		"AttributeBaseStrength6" "761.212"
		"AttributeBaseAgility6" "747.464"
		"AttributeBaseIntelligence6" "706.22"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Centaur"
		"HeroSelectSoundEffect" "Hero_Centaur.Pick"
		"particle_folder" "particles/units/heroes/hero_centaur"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_centaur.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/centaur/centaur.vmdl"
		"ModelScale" "0.94"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "362"

				}
				"2" {
					"ItemDef" "363"

				}
				"3" {
					"ItemDef" "359"

				}
				"4" {
					"ItemDef" "360"

				}
				"5" {
					"ItemDef" "8366"

				}
				"6" {
					"ItemDef" "358"

				}
				"7" {
					"ItemDef" "364"

				}
				"8" {
					"ItemDef" "361"

				}
				"9" {
					"ItemDef" "361"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_zuus" {
		"CardName" "item_building_hero_zuus"
		"HeroId" "102044"
		"vscripts" "npc/units/building/tower/building_hero_zuus"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "god_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "50"
		"AttackDamageMax" "56"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.45"
		"RingRadius" "70"
		"AttackRange" "950"
		"AttackAcquisitionRange" "1900"
		"ProjectileModel" "particles/units/heroes/hero_zuus/zuus_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "66"
		"AttributeBaseAgility1" "82.5"
		"AttributeBaseIntelligence1" "88"
		"AttributeBaseStrength2" "100.2"
		"AttributeBaseAgility2" "125.25"
		"AttributeBaseIntelligence2" "133.6"
		"AttributeBaseStrength3" "127.56"
		"AttributeBaseAgility3" "159.45"
		"AttributeBaseIntelligence3" "170.08"
		"AttributeBaseStrength4" "161.76"
		"AttributeBaseAgility4" "202.2"
		"AttributeBaseIntelligence4" "215.68"
		"AttributeBaseStrength5" "206.22"
		"AttributeBaseAgility5" "257.775"
		"AttributeBaseIntelligence5" "274.96"
		"AttributeBaseStrength6" "706.22"
		"AttributeBaseAgility6" "757.775"
		"AttributeBaseIntelligence6" "774.96"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_zuus"
		"HeroSelectSoundEffect" "Hero_zuus.Pick"
		"particle_folder" "particles/units/heroes/hero_zuus"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_zuus.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_zuus.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/zeus/zeus.vmdl"
		"ModelScale" "1.2"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "11624"

				}
				"2" {
					"ItemDef" "7954"

				}
				"3" {
					"ItemDef" "7952"

				}
				"4" {
					"ItemDef" "7953"

				}
				"5" {
					"ItemDef" "7951"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_huskar" {
		"CardName" "item_building_hero_huskar"
		"HeroId" "102051"
		"vscripts" "npc/units/building/tower/building_hero_huskar"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "warrior_2"
		"Relation_2" "fire_2"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "1050"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/units/heroes/hero_huskar/huskar_base_attack.vpcf"
		"ProjectileSpeed" "1000"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "79.2"
		"AttributeBaseAgility1" "74.8"
		"AttributeBaseIntelligence1" "68.2"
		"AttributeBaseStrength2" "120.24"
		"AttributeBaseAgility2" "113.56"
		"AttributeBaseIntelligence2" "103.54"
		"AttributeBaseStrength3" "153.072"
		"AttributeBaseAgility3" "144.568"
		"AttributeBaseIntelligence3" "131.812"
		"AttributeBaseStrength4" "194.112"
		"AttributeBaseAgility4" "183.328"
		"AttributeBaseIntelligence4" "167.152"
		"AttributeBaseStrength5" "247.464"
		"AttributeBaseAgility5" "233.716"
		"AttributeBaseIntelligence5" "213.094"
		"AttributeBaseStrength6" "747.464"
		"AttributeBaseAgility6" "733.716"
		"AttributeBaseIntelligence6" "713.094"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Huskar"
		"HeroSelectSoundEffect" "Hero_Huskar.Pick"
		"particle_folder" "particles/units/heroes/hero_huskar"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_huskar.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_huskar.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/huskar/huskar.vmdl"
		"ModelScale" "0.95"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "4908"

				}
				"2" {
					"ItemDef" "4909"

				}
				"3" {
					"ItemDef" "4907"

				}
				"4" {
					"ItemDef" "4910"

				}
				"5" {
					"ItemDef" "4906"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_viper" {
		"CardName" "item_building_hero_viper"
		"HeroId" "102053"
		"vscripts" "npc/units/building/tower/building_hero_viper"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "snake_2"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.35"
		"RingRadius" "70"
		"AttackRange" "1100"
		"AttackAcquisitionRange" "1900"
		"ProjectileModel" "particles/units/heroes/hero_viper/viper_base_attack.vpcf"
		"ProjectileSpeed" "1200"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "79.2"
		"AttributeBaseAgility1" "88"
		"AttributeBaseIntelligence1" "57.2"
		"AttributeBaseStrength2" "120.24"
		"AttributeBaseAgility2" "133.6"
		"AttributeBaseIntelligence2" "86.84"
		"AttributeBaseStrength3" "153.072"
		"AttributeBaseAgility3" "170.08"
		"AttributeBaseIntelligence3" "110.552"
		"AttributeBaseStrength4" "194.112"
		"AttributeBaseAgility4" "215.68"
		"AttributeBaseIntelligence4" "140.192"
		"AttributeBaseStrength5" "247.464"
		"AttributeBaseAgility5" "274.96"
		"AttributeBaseIntelligence5" "178.724"
		"AttributeBaseStrength6" "747.464"
		"AttributeBaseAgility6" "774.96"
		"AttributeBaseIntelligence6" "678.724"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Viper"
		"HeroSelectSoundEffect" "Hero_Viper.Pick"
		"particle_folder" "particles/units/heroes/hero_viper"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_viper.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_viper.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/viper/viper.vmdl"
		"ModelScale" "1.05"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "654"

				}
				"2" {
					"ItemDef" "611"

				}
				"3" {
					"ItemDef" "519"

				}
				"4" {
					"ItemDef" "623"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_earth_spirit" {
		"CardName" "item_building_hero_earth_spirit"
		"HeroId" "102058"
		"vscripts" "npc/units/building/tower/building_hero_earth_spirit"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "spirits_4"
		"Relation_2" "earth_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.35"
		"RingRadius" "70"
		"AttackRange" "850"
		"AttackAcquisitionRange" "1150"
		"ProjectileSpeed" "1100"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "81.4"
		"AttributeBaseAgility1" "66"
		"AttributeBaseIntelligence1" "75.9"
		"AttributeBaseStrength2" "123.58"
		"AttributeBaseAgility2" "100.2"
		"AttributeBaseIntelligence2" "115.23"
		"AttributeBaseStrength3" "157.324"
		"AttributeBaseAgility3" "127.56"
		"AttributeBaseIntelligence3" "146.694"
		"AttributeBaseStrength4" "199.504"
		"AttributeBaseAgility4" "161.76"
		"AttributeBaseIntelligence4" "186.024"
		"AttributeBaseStrength5" "254.338"
		"AttributeBaseAgility5" "206.22"
		"AttributeBaseIntelligence5" "237.153"
		"AttributeBaseStrength6" "754.338"
		"AttributeBaseAgility6" "706.22"
		"AttributeBaseIntelligence6" "737.153"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_EarthSpirit"
		"HeroSelectSoundEffect" "Hero_EarthSpirit.Pick"
		"particle_folder" "particles/units/heroes/hero_earth_spirit"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_earth_spirit.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_earth_spirit.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/earth_spirit/earth_spirit.vmdl"
		"ModelScale" "1.15"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "475"

				}
				"2" {
					"ItemDef" "480"

				}
				"3" {
					"ItemDef" "481"

				}
				"4" {
					"ItemDef" "526"

				}
				"5" {
					"ItemDef" "479"

				}
				"6" {
					"ItemDef" "482"

				}
				"7" {
					"ItemDef" "477"

				}
				"8" {
					"ItemDef" "8654"

				}
				"9" {
					"ItemDef" "8654"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_omniknight" {
		"CardName" "item_building_hero_omniknight"
		"HeroId" "102100"
		"vscripts" "npc/units/building/tower/building_hero_omniknight"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "utopia_1"
		"Relation_2" "templar_2"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "262"
		"AttackDamageMax" "268"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.4"
		"RingRadius" "70"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1000"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "88"
		"AttributeBaseAgility1" "60.5"
		"AttributeBaseIntelligence1" "77"
		"AttributeBaseStrength2" "133.6"
		"AttributeBaseAgility2" "91.85"
		"AttributeBaseIntelligence2" "116.9"
		"AttributeBaseStrength3" "170.08"
		"AttributeBaseAgility3" "116.93"
		"AttributeBaseIntelligence3" "148.82"
		"AttributeBaseStrength4" "215.68"
		"AttributeBaseAgility4" "148.28"
		"AttributeBaseIntelligence4" "188.72"
		"AttributeBaseStrength5" "274.96"
		"AttributeBaseAgility5" "189.035"
		"AttributeBaseIntelligence5" "240.59"
		"AttributeBaseStrength6" "774.96"
		"AttributeBaseAgility6" "689.035"
		"AttributeBaseIntelligence6" "740.59"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Omniknight"
		"HeroSelectSoundEffect" "Hero_Omniknight.Pick"
		"particle_folder" "particles/units/heroes/hero_omniknight"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_omniknight.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/omniknight/omniknight.vmdl"
		"ModelScale" "0.85"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "42"

				}
				"2" {
					"ItemDef" "43"

				}
				"3" {
					"ItemDef" "44"

				}
				"4" {
					"ItemDef" "45"

				}
				"5" {
					"ItemDef" "46"

				}
				"6" {
					"ItemDef" "13"

				}
				"7" {
					"ItemDef" "562"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_gyrocopter" {
		"CardName" "item_building_hero_gyrocopter"
		"HeroId" "102101"
		"vscripts" "npc/units/building/tower/building_hero_gyrocopter"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "dwarf_1"
		"Relation_2" "engineer_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "81"
		"AttackDamageMax" "87"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.2"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/units/heroes/hero_gyrocopter/gyro_base_attack.vpcf"
		"ProjectileSpeed" "3000"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "70.4"
		"AttributeBaseAgility1" "81.4"
		"AttributeBaseIntelligence1" "72.6"
		"AttributeBaseStrength2" "106.88"
		"AttributeBaseAgility2" "123.58"
		"AttributeBaseIntelligence2" "110.22"
		"AttributeBaseStrength3" "136.064"
		"AttributeBaseAgility3" "157.324"
		"AttributeBaseIntelligence3" "140.316"
		"AttributeBaseStrength4" "172.544"
		"AttributeBaseAgility4" "199.504"
		"AttributeBaseIntelligence4" "177.936"
		"AttributeBaseStrength5" "219.968"
		"AttributeBaseAgility5" "254.338"
		"AttributeBaseIntelligence5" "226.842"
		"AttributeBaseStrength6" "719.968"
		"AttributeBaseAgility6" "754.338"
		"AttributeBaseIntelligence6" "726.842"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Gyrocopter"
		"HeroSelectSoundEffect" "Hero_Gyrocopter.Pick"
		"particle_folder" "particles/units/heroes/hero_gyrocopter"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_gyrocopter.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_gyrocopter.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "325"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/gyro/gyro.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "126"

				}
				"2" {
					"ItemDef" "131"

				}
				"3" {
					"ItemDef" "176"

				}
				"4" {
					"ItemDef" "177"

				}
				"5" {
					"ItemDef" "178"

				}
				"6" {
					"ItemDef" "179"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_phantom_assassin" {
		"CardName" "item_building_hero_phantom_assassin"
		"HeroId" "102102"
		"vscripts" "npc/units/building/tower/building_hero_phantom_assassin"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "assassin_2"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "700"
		"AttackAcquisitionRange" "1100"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "83.6"
		"AttributeBaseAgility1" "70.4"
		"AttributeBaseIntelligence1" "70.4"
		"AttributeBaseStrength2" "126.92"
		"AttributeBaseAgility2" "106.88"
		"AttributeBaseIntelligence2" "106.88"
		"AttributeBaseStrength3" "161.576"
		"AttributeBaseAgility3" "136.064"
		"AttributeBaseIntelligence3" "136.064"
		"AttributeBaseStrength4" "204.896"
		"AttributeBaseAgility4" "172.544"
		"AttributeBaseIntelligence4" "172.544"
		"AttributeBaseStrength5" "261.212"
		"AttributeBaseAgility5" "219.968"
		"AttributeBaseIntelligence5" "219.968"
		"AttributeBaseStrength6" "761.212"
		"AttributeBaseAgility6" "719.968"
		"AttributeBaseIntelligence6" "719.968"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_PhantomAssassin"
		"HeroSelectSoundEffect" "Hero_PhantomAssassin.Pick"
		"particle_folder" "particles/units/heroes/hero_phantom_assassin"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_phantom_assassin.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_phantom_assassin.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/phantom_assassin/phantom_assassin.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "138"

				}
				"2" {
					"ItemDef" "140"

				}
				"3" {
					"ItemDef" "137"

				}
				"4" {
					"ItemDef" "141"

				}
				"5" {
					"ItemDef" "139"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_pugna" {
		"CardName" "item_building_hero_pugna"
		"HeroId" "102103"
		"vscripts" "npc/units/building/tower/building_hero_pugna"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "nether_1"
		"level_upgrades" "2"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "50"
		"AttackDamageMax" "56"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "630"
		"AttackAcquisitionRange" "1900"
		"ProjectileModel" "particles/units/heroes/hero_pugna/pugna_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "66"
		"AttributeBaseAgility1" "82.5"
		"AttributeBaseIntelligence1" "88"
		"AttributeBaseStrength2" "100.2"
		"AttributeBaseAgility2" "125.25"
		"AttributeBaseIntelligence2" "133.6"
		"AttributeBaseStrength3" "127.56"
		"AttributeBaseAgility3" "159.45"
		"AttributeBaseIntelligence3" "170.08"
		"AttributeBaseStrength4" "161.76"
		"AttributeBaseAgility4" "202.2"
		"AttributeBaseIntelligence4" "215.68"
		"AttributeBaseStrength5" "206.22"
		"AttributeBaseAgility5" "257.775"
		"AttributeBaseIntelligence5" "274.96"
		"AttributeBaseStrength6" "706.22"
		"AttributeBaseAgility6" "757.775"
		"AttributeBaseIntelligence6" "774.96"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Pugna"
		"HeroSelectSoundEffect" "Hero_Pugna.Pick"
		"particle_folder" "particles/units/heroes/hero_zuus"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_pugna.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_pugna.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/pugna/pugna.vmdl"
		"ModelScale" "1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "153"

				}
				"2" {
					"ItemDef" "154"

				}
				"3" {
					"ItemDef" "155"

				}
				"4" {
					"ItemDef" "156"

				}
				"5" {
					"ItemDef" "157"

				}
				"6" {
					"ItemDef" "167"

				}
				"7" {
					"ItemDef" "511"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_spirit_bear" {
		"CardName" "item_building_hero_spirit_bear"
		"vscripts" "npc/units/building/tower/building_hero_spirit_bear"
		"Rarity" "SR"
		"Population" "0"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "150"
		"AttackAcquisitionRange" "1300"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "70.4"
		"AttributeBaseAgility1" "85.8"
		"AttributeBaseIntelligence1" "68.2"
		"AttributeBaseStrength2" "106.88"
		"AttributeBaseAgility2" "130.26"
		"AttributeBaseIntelligence2" "103.54"
		"AttributeBaseStrength3" "136.064"
		"AttributeBaseAgility3" "165.828"
		"AttributeBaseIntelligence3" "131.812"
		"AttributeBaseStrength4" "172.544"
		"AttributeBaseAgility4" "210.288"
		"AttributeBaseIntelligence4" "167.152"
		"AttributeBaseStrength5" "219.968"
		"AttributeBaseAgility5" "268.086"
		"AttributeBaseIntelligence5" "213.094"
		"AttributeBaseStrength6" "300"
		"AttributeBaseAgility6" "300"
		"AttributeBaseIntelligence6" "300"
		"UnitLabel" "HERO"
		"HasInventory" "0"
		"InventorySlots" "4"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"BaseClass" "npc_dota_creature"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "450"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/lone_druid/spirit_bear.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}
		"IsShow" "0"

	}
	"building_hero_pangolier" {
		"CardName" "item_building_hero_pangolier"
		"HeroId" "101047"
		"vscripts" "npc/units/building/tower/building_hero_pangolier"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "swordman_2"
		"Relation_2" "utopia_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "tower_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.33"
		"RingRadius" "70"
		"AttackRange" "850"
		"AttackAcquisitionRange" "1150"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "27"
		"AttributeBaseAgility1" "54"
		"AttributeBaseIntelligence1" "18"
		"AttributeBaseStrength2" "41.7"
		"AttributeBaseAgility2" "83.4"
		"AttributeBaseIntelligence2" "27.8"
		"AttributeBaseStrength3" "53.46"
		"AttributeBaseAgility3" "106.92"
		"AttributeBaseIntelligence3" "35.64"
		"AttributeBaseStrength4" "68.16"
		"AttributeBaseAgility4" "136.32"
		"AttributeBaseIntelligence4" "45.44"
		"AttributeBaseStrength5" "87.27"
		"AttributeBaseAgility5" "174.54"
		"AttributeBaseIntelligence5" "58.18"
		"AttributeBaseStrength6" "587.27"
		"AttributeBaseAgility6" "674.54"
		"AttributeBaseIntelligence6" "558.18"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_Pangolier"
		"HeroSelectSoundEffect" "Hero_Pangolier.Pick"
		"particle_folder" "particles/units/heroes/hero_pangolier"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_pangolier.vsndevts"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_pangolin.vsndevts"
		"AbilityLayout" "5"
		"HealthBarOffset" "275"
		"MovementSpeed" "300"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "1"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/pangolier/pangolier.vmdl"
		"ModelScale" "1.1"
		"Creature" {
			"AttachWearables" {
				"1" {
					"ItemDef" "643"

				}
				"2" {
					"ItemDef" "650"

				}
				"3" {
					"ItemDef" "645"

				}
				"4" {
					"ItemDef" "644"

				}

			}

		}
		"IsShow" "1"

	}
	"building_hero_t01" {
		"CardName" "item_building_hero_t01"
		"HeroId" "101065"
		"vscripts" "npc/units/building/tower/building_hero_t01"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "dire_1"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.467"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "38.7"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "27"
		"AttributeBaseStrength2" "59.77"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "41.7"
		"AttributeBaseStrength3" "76.626"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "53.46"
		"AttributeBaseStrength4" "97.696"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "68.16"
		"AttributeBaseStrength5" "125.087"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "87.27"
		"AttributeBaseStrength6" "625.087"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "587.27"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Creep_Bad_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee.vmdl"
		"ModelScale" "1"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t02" {
		"CardName" "item_building_hero_t02"
		"HeroId" "101066"
		"vscripts" "npc/units/building/tower/building_hero_t02"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "dire_2"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "1300"
		"AttackAcquisitionRange" "1900"
		"ProjectileModel" "particles/base_attacks/ranged_badguy.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "36"
		"AttributeBaseAgility1" "9"
		"AttributeBaseIntelligence1" "45"
		"AttributeBaseStrength2" "55.6"
		"AttributeBaseAgility2" "13.9"
		"AttributeBaseIntelligence2" "69.5"
		"AttributeBaseStrength3" "71.28"
		"AttributeBaseAgility3" "17.82"
		"AttributeBaseIntelligence3" "89.1"
		"AttributeBaseStrength4" "90.88"
		"AttributeBaseAgility4" "22.72"
		"AttributeBaseIntelligence4" "113.6"
		"AttributeBaseStrength5" "116.36"
		"AttributeBaseAgility5" "29.09"
		"AttributeBaseIntelligence5" "145.45"
		"AttributeBaseStrength6" "616.36"
		"AttributeBaseAgility6" "529.09"
		"AttributeBaseIntelligence6" "645.45"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Creep_Bad_Range"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/lane_creeps/creep_bad_ranged/lane_dire_ranged.vmdl"
		"ModelScale" "1"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t03" {
		"CardName" "item_building_hero_t03"
		"HeroId" "101067"
		"vscripts" "npc/units/building/tower/building_hero_t03"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "animal_1"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "1200"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/econ/items/keeper_of_the_light/kotl_weapon_arcane_staff/keeper_base_attack_arcane_staff.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "20.7"
		"AttributeBaseAgility1" "23.4"
		"AttributeBaseIntelligence1" "45.9"
		"AttributeBaseStrength2" "31.97"
		"AttributeBaseAgility2" "36.14"
		"AttributeBaseIntelligence2" "70.89"
		"AttributeBaseStrength3" "40.986"
		"AttributeBaseAgility3" "46.332"
		"AttributeBaseIntelligence3" "90.882"
		"AttributeBaseStrength4" "52.256"
		"AttributeBaseAgility4" "59.072"
		"AttributeBaseIntelligence4" "115.872"
		"AttributeBaseStrength5" "66.907"
		"AttributeBaseAgility5" "75.634"
		"AttributeBaseIntelligence5" "148.359"
		"AttributeBaseStrength6" "566.907"
		"AttributeBaseAgility6" "575.634"
		"AttributeBaseIntelligence6" "648.359"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Ranged"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_vulture_a/n_creep_vulture_a.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t04" {
		"CardName" "item_building_hero_t04"
		"HeroId" "101068"
		"vscripts" "npc/units/building/tower/building_hero_t04"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "soul_1"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "40"
		"AttackRange" "1200"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/ghost_base_attack.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "18"
		"AttributeBaseAgility1" "18"
		"AttributeBaseIntelligence1" "54"
		"AttributeBaseStrength2" "27.8"
		"AttributeBaseAgility2" "27.8"
		"AttributeBaseIntelligence2" "83.4"
		"AttributeBaseStrength3" "35.64"
		"AttributeBaseAgility3" "35.64"
		"AttributeBaseIntelligence3" "106.92"
		"AttributeBaseStrength4" "45.44"
		"AttributeBaseAgility4" "45.44"
		"AttributeBaseIntelligence4" "136.32"
		"AttributeBaseStrength5" "58.18"
		"AttributeBaseAgility5" "58.18"
		"AttributeBaseIntelligence5" "174.54"
		"AttributeBaseStrength6" "558.18"
		"AttributeBaseAgility6" "558.18"
		"AttributeBaseIntelligence6" "674.54"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Ranged"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/lane_creeps/creep_radiant_ranged_diretide/creep_radiant_ranged_diretide.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t05" {
		"CardName" "item_building_hero_t05"
		"HeroId" "101069"
		"vscripts" "npc/units/building/tower/building_hero_t05"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "radiant_1"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.46"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "40.5"
		"AttributeBaseAgility1" "24.3"
		"AttributeBaseIntelligence1" "27"
		"AttributeBaseStrength2" "62.55"
		"AttributeBaseAgility2" "37.53"
		"AttributeBaseIntelligence2" "41.7"
		"AttributeBaseStrength3" "80.19"
		"AttributeBaseAgility3" "48.114"
		"AttributeBaseIntelligence3" "53.46"
		"AttributeBaseStrength4" "102.24"
		"AttributeBaseAgility4" "61.344"
		"AttributeBaseIntelligence4" "68.16"
		"AttributeBaseStrength5" "130.905"
		"AttributeBaseAgility5" "78.543"
		"AttributeBaseIntelligence5" "87.27"
		"AttributeBaseStrength6" "630.905"
		"AttributeBaseAgility6" "578.543"
		"AttributeBaseIntelligence6" "587.27"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Creep_Good_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee.vmdl"
		"ModelScale" "1"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t06" {
		"CardName" "item_building_hero_t06"
		"HeroId" "101070"
		"vscripts" "npc/units/building/tower/building_hero_t06"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "radiant_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "1200"
		"AttackAcquisitionRange" "1900"
		"ProjectileModel" "particles/base_attacks/ranged_goodguy.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "27"
		"AttributeBaseAgility1" "22.5"
		"AttributeBaseIntelligence1" "40.5"
		"AttributeBaseStrength2" "41.7"
		"AttributeBaseAgility2" "34.75"
		"AttributeBaseIntelligence2" "62.55"
		"AttributeBaseStrength3" "53.46"
		"AttributeBaseAgility3" "44.55"
		"AttributeBaseIntelligence3" "80.19"
		"AttributeBaseStrength4" "68.16"
		"AttributeBaseAgility4" "56.8"
		"AttributeBaseIntelligence4" "102.24"
		"AttributeBaseStrength5" "87.27"
		"AttributeBaseAgility5" "72.725"
		"AttributeBaseIntelligence5" "130.905"
		"AttributeBaseStrength6" "587.27"
		"AttributeBaseAgility6" "572.725"
		"AttributeBaseIntelligence6" "630.905"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Creep_Good_Range"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/lane_creeps/creep_radiant_ranged/radiant_ranged.vmdl"
		"ModelScale" "1"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t07" {
		"CardName" "item_building_hero_t07"
		"HeroId" "101071"
		"vscripts" "npc/units/building/tower/building_hero_t07"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "envoy_2"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1200"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "18"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "45"
		"AttributeBaseStrength2" "27.8"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "69.5"
		"AttributeBaseStrength3" "35.64"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "89.1"
		"AttributeBaseStrength4" "45.44"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "113.6"
		"AttributeBaseStrength5" "58.18"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "145.45"
		"AttributeBaseStrength6" "558.18"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "645.45"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_satyr_a/n_creep_satyr_a.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t08" {
		"CardName" "item_building_hero_t08"
		"HeroId" "101072"
		"vscripts" "npc/units/building/tower/building_hero_t08"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "electricity_2"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "1000"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/base_attacks/ranged_badguy.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "18"
		"AttributeBaseAgility1" "28.8"
		"AttributeBaseIntelligence1" "43.2"
		"AttributeBaseStrength2" "27.8"
		"AttributeBaseAgility2" "44.48"
		"AttributeBaseIntelligence2" "66.72"
		"AttributeBaseStrength3" "35.64"
		"AttributeBaseAgility3" "57.024"
		"AttributeBaseIntelligence3" "85.536"
		"AttributeBaseStrength4" "45.44"
		"AttributeBaseAgility4" "72.704"
		"AttributeBaseIntelligence4" "109.056"
		"AttributeBaseStrength5" "58.18"
		"AttributeBaseAgility5" "93.088"
		"AttributeBaseIntelligence5" "139.632"
		"AttributeBaseStrength6" "558.18"
		"AttributeBaseAgility6" "593.088"
		"AttributeBaseIntelligence6" "639.632"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Ranged"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_harpy_b/n_creep_harpy_b.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t10" {
		"CardName" "item_building_hero_t10"
		"HeroId" "101074"
		"vscripts" "npc/units/building/tower/building_hero_t10"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "berserker_2"
		"Relation_2" "centaur_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "38.7"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "24.3"
		"AttributeBaseStrength2" "59.77"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "37.53"
		"AttributeBaseStrength3" "76.626"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "48.114"
		"AttributeBaseStrength4" "97.696"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "61.344"
		"AttributeBaseStrength5" "125.087"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "78.543"
		"AttributeBaseStrength6" "625.087"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "578.543"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_centaur_lrg/n_creep_centaur_lrg.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t11" {
		"CardName" "item_building_hero_t11"
		"HeroId" "101075"
		"vscripts" "npc/units/building/tower/building_hero_t11"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "poison_1"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "950"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/base_attacks/ranged_badguy.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "9"
		"AttributeBaseAgility1" "9"
		"AttributeBaseIntelligence1" "72"
		"AttributeBaseStrength2" "13.9"
		"AttributeBaseAgility2" "13.9"
		"AttributeBaseIntelligence2" "111.2"
		"AttributeBaseStrength3" "17.82"
		"AttributeBaseAgility3" "17.82"
		"AttributeBaseIntelligence3" "142.56"
		"AttributeBaseStrength4" "22.72"
		"AttributeBaseAgility4" "22.72"
		"AttributeBaseIntelligence4" "181.76"
		"AttributeBaseStrength5" "29.09"
		"AttributeBaseAgility5" "29.09"
		"AttributeBaseIntelligence5" "232.72"
		"AttributeBaseStrength6" "529.09"
		"AttributeBaseAgility6" "529.09"
		"AttributeBaseIntelligence6" "732.72"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Ranged"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_troll_dark_b/n_creep_troll_dark_b.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t12" {
		"CardName" "item_building_hero_t12"
		"HeroId" "101076"
		"vscripts" "npc/units/building/tower/building_hero_t12"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "fat_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "46.8"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "16.2"
		"AttributeBaseStrength2" "72.28"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "25.02"
		"AttributeBaseStrength3" "92.664"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "32.076"
		"AttributeBaseStrength4" "118.144"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "40.896"
		"AttributeBaseStrength5" "151.268"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "52.362"
		"AttributeBaseStrength6" "651.268"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "552.362"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Ranged"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_ogre_med/n_creep_ogre_med.vmdl"
		"ModelScale" "0.8"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t15" {
		"CardName" "item_building_hero_t15"
		"HeroId" "101079"
		"vscripts" "npc/units/building/tower/building_hero_t15"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "thief_2"
		"Relation_2" "goblin_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.38"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "32.4"
		"AttributeBaseAgility1" "24.3"
		"AttributeBaseIntelligence1" "24.3"
		"AttributeBaseStrength2" "50.04"
		"AttributeBaseAgility2" "37.53"
		"AttributeBaseIntelligence2" "37.53"
		"AttributeBaseStrength3" "64.152"
		"AttributeBaseAgility3" "48.114"
		"AttributeBaseIntelligence3" "48.114"
		"AttributeBaseStrength4" "81.792"
		"AttributeBaseAgility4" "61.344"
		"AttributeBaseIntelligence4" "61.344"
		"AttributeBaseStrength5" "104.724"
		"AttributeBaseAgility5" "78.543"
		"AttributeBaseIntelligence5" "78.543"
		"AttributeBaseStrength6" "604.724"
		"AttributeBaseAgility6" "578.543"
		"AttributeBaseIntelligence6" "578.543"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_kobold/kobold_a/n_creep_kobold_a.vmdl"
		"ModelScale" "0.82"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t16" {
		"CardName" "item_building_hero_t16"
		"HeroId" "101080"
		"vscripts" "npc/units/building/tower/building_hero_t16"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "animal_2"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "87"
		"AttackDamageMax" "93"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"RingRadius" "70"
		"AttackRange" "1050"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/thunderlizard_base_attack.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "22.5"
		"AttributeBaseAgility1" "46.8"
		"AttributeBaseIntelligence1" "20.7"
		"AttributeBaseStrength2" "34.75"
		"AttributeBaseAgility2" "72.28"
		"AttributeBaseIntelligence2" "31.97"
		"AttributeBaseStrength3" "44.55"
		"AttributeBaseAgility3" "92.664"
		"AttributeBaseIntelligence3" "40.986"
		"AttributeBaseStrength4" "56.8"
		"AttributeBaseAgility4" "118.144"
		"AttributeBaseIntelligence4" "52.256"
		"AttributeBaseStrength5" "72.725"
		"AttributeBaseAgility5" "151.268"
		"AttributeBaseIntelligence5" "66.907"
		"AttributeBaseStrength6" "572.725"
		"AttributeBaseAgility6" "651.268"
		"AttributeBaseIntelligence6" "566.907"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Ranged"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_thunder_lizard/n_creep_thunder_lizard_big.vmdl"
		"ModelScale" "0.62"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t17" {
		"CardName" "item_building_hero_t17"
		"HeroId" "101081"
		"vscripts" "npc/units/building/tower/building_hero_t17"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "troll_1"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "87"
		"AttackDamageMax" "93"
		"AttackRate" "1.6"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" "particles/base_attacks/ranged_badguy.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "27"
		"AttributeBaseAgility1" "9"
		"AttributeBaseIntelligence1" "56.25"
		"AttributeBaseStrength2" "41.7"
		"AttributeBaseAgility2" "13.9"
		"AttributeBaseIntelligence2" "86.875"
		"AttributeBaseStrength3" "53.46"
		"AttributeBaseAgility3" "17.82"
		"AttributeBaseIntelligence3" "111.375"
		"AttributeBaseStrength4" "68.16"
		"AttributeBaseAgility4" "22.72"
		"AttributeBaseIntelligence4" "142"
		"AttributeBaseStrength5" "87.27"
		"AttributeBaseAgility5" "29.09"
		"AttributeBaseIntelligence5" "181.8125"
		"AttributeBaseStrength6" "587.27"
		"AttributeBaseAgility6" "529.09"
		"AttributeBaseIntelligence6" "681.8125"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Ranged"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_forest_trolls/n_creep_forest_troll_high_priest.vmdl"
		"ModelScale" "0.8"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t19" {
		"CardName" "item_building_hero_t19"
		"HeroId" "101083"
		"vscripts" "npc/units/building/tower/building_hero_t19"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "guard_3"
		"Relation_2" "bearman_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "45"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "27"
		"AttributeBaseStrength2" "69.5"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "41.7"
		"AttributeBaseStrength3" "89.1"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "53.46"
		"AttributeBaseStrength4" "113.6"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "68.16"
		"AttributeBaseStrength5" "145.45"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "87.27"
		"AttributeBaseStrength6" "645.45"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "587.27"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_furbolg/n_creep_furbolg_disrupter.vmdl"
		"ModelScale" "0.8"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t21" {
		"CardName" "item_building_hero_t21"
		"HeroId" "101085"
		"vscripts" "npc/units/building/tower/building_hero_t21"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "guard_2"
		"Relation_2" "nether_2"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/units/heroes/hero_pugna/pugna_base_attack.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "22.5"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "49.5"
		"AttributeBaseStrength2" "34.75"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "76.45"
		"AttributeBaseStrength3" "44.55"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "98.01"
		"AttributeBaseStrength4" "56.8"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "124.96"
		"AttributeBaseStrength5" "72.725"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "159.995"
		"AttributeBaseStrength6" "572.725"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "659.995"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Creep_Good_Range"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/items/pugna/ward/draining_wight/draining_wight.vmdl"
		"ModelScale" "0.77"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t22" {
		"CardName" "item_building_hero_t22"
		"HeroId" "101086"
		"vscripts" "npc/units/building/tower/building_hero_t22"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "puppet_1"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.4"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" "particles/units/heroes/hero_invoker/invoker_forged_spirit_projectile.vpcf"
		"ProjectileSpeed" "1000"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "13.5"
		"AttributeBaseAgility1" "13.5"
		"AttributeBaseIntelligence1" "63"
		"AttributeBaseStrength2" "20.85"
		"AttributeBaseAgility2" "20.85"
		"AttributeBaseIntelligence2" "97.3"
		"AttributeBaseStrength3" "26.73"
		"AttributeBaseAgility3" "26.73"
		"AttributeBaseIntelligence3" "124.74"
		"AttributeBaseStrength4" "34.08"
		"AttributeBaseAgility4" "34.08"
		"AttributeBaseIntelligence4" "159.04"
		"AttributeBaseStrength5" "43.635"
		"AttributeBaseAgility5" "43.635"
		"AttributeBaseIntelligence5" "203.63"
		"AttributeBaseStrength6" "543.635"
		"AttributeBaseAgility6" "543.635"
		"AttributeBaseIntelligence6" "703.63"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Creep_Good_Range"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/invoker/forge_spirit.vmdl"
		"ModelScale" "0.83"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t23" {
		"CardName" "item_building_hero_t23"
		"HeroId" "101087"
		"vscripts" "npc/units/building/tower/building_hero_t23"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "wolf_2"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "50"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.33"
		"RingRadius" "70"
		"AttackRange" "850"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "36"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "27"
		"AttributeBaseStrength2" "55.6"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "41.7"
		"AttributeBaseStrength3" "71.28"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "53.46"
		"AttributeBaseStrength4" "90.88"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "68.16"
		"AttributeBaseStrength5" "116.36"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "87.27"
		"AttributeBaseStrength6" "616.36"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "587.27"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_worg_large/n_creep_worg_large.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t25" {
		"CardName" "item_building_hero_t25"
		"HeroId" "101089"
		"vscripts" "npc/units/building/tower/building_hero_t25"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "soul_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.2"
		"RingRadius" "70"
		"AttackRange" "1000"
		"AttackAcquisitionRange" "1100"
		"ProjectileModel" "particles/units/heroes/hero_invoker/invoker_forged_spirit_projectile.vpcf"
		"ProjectileSpeed" "1000"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "54"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "9"
		"AttributeBaseStrength2" "83.4"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "13.9"
		"AttributeBaseStrength3" "106.92"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "17.82"
		"AttributeBaseStrength4" "136.32"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "22.72"
		"AttributeBaseStrength5" "174.54"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "29.09"
		"AttributeBaseStrength6" "674.54"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "529.09"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Creep_Good_Range"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/items/invoker/forge_spirit/frostivus2018_invoker_keeper_of_magic_spirit/frostivus2018_invoker_keeper_of_magic_spirit.vmdl"
		"ModelScale" "0.95"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t27" {
		"CardName" "item_building_hero_t27"
		"HeroId" "101091"
		"vscripts" "npc/units/building/tower/building_hero_t27"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "elements_1"
		"Relation_2" "storm_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "262"
		"AttackDamageMax" "268"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.4"
		"RingRadius" "70"
		"AttackRange" "1000"
		"AttackAcquisitionRange" "1900"
		"ProjectileModel" "particles/units/heroes/hero_brewmaster/brewmaster_storm_attack.vpcf"
		"ProjectileSpeed" "1800"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "22.5"
		"AttributeBaseAgility1" "45"
		"AttributeBaseIntelligence1" "22.5"
		"AttributeBaseStrength2" "34.75"
		"AttributeBaseAgility2" "69.5"
		"AttributeBaseIntelligence2" "34.75"
		"AttributeBaseStrength3" "44.55"
		"AttributeBaseAgility3" "89.1"
		"AttributeBaseIntelligence3" "44.55"
		"AttributeBaseStrength4" "56.8"
		"AttributeBaseAgility4" "113.6"
		"AttributeBaseIntelligence4" "56.8"
		"AttributeBaseStrength5" "72.725"
		"AttributeBaseAgility5" "145.45"
		"AttributeBaseIntelligence5" "72.725"
		"AttributeBaseStrength6" "572.725"
		"AttributeBaseAgility6" "645.45"
		"AttributeBaseIntelligence6" "572.725"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Brewmaster_Storm"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/brewmaster/brewmaster_windspirit.vmdl"
		"ModelScale" "0.8"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t28" {
		"CardName" "item_building_hero_t28"
		"HeroId" "101092"
		"vscripts" "npc/units/building/tower/building_hero_t28"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "elements_2"
		"Relation_2" "earth_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "262"
		"AttackDamageMax" "268"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1500"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "45"
		"AttributeBaseAgility1" "22.5"
		"AttributeBaseIntelligence1" "22.5"
		"AttributeBaseStrength2" "69.5"
		"AttributeBaseAgility2" "34.75"
		"AttributeBaseIntelligence2" "34.75"
		"AttributeBaseStrength3" "89.1"
		"AttributeBaseAgility3" "44.55"
		"AttributeBaseIntelligence3" "44.55"
		"AttributeBaseStrength4" "113.6"
		"AttributeBaseAgility4" "56.8"
		"AttributeBaseIntelligence4" "56.8"
		"AttributeBaseStrength5" "145.45"
		"AttributeBaseAgility5" "72.725"
		"AttributeBaseIntelligence5" "72.725"
		"AttributeBaseStrength6" "645.45"
		"AttributeBaseAgility6" "572.725"
		"AttributeBaseIntelligence6" "572.725"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Brewmaster_Earth"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/brewmaster/brewmaster_earthspirit.vmdl"
		"ModelScale" "0.8"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t29" {
		"CardName" "item_building_hero_t29"
		"HeroId" "101093"
		"vscripts" "npc/units/building/tower/building_hero_t29"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "elements_3"
		"Relation_2" "flame_1"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.33"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1300"
		"ProjectileModel" "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "22.5"
		"AttributeBaseAgility1" "22.5"
		"AttributeBaseIntelligence1" "45"
		"AttributeBaseStrength2" "34.75"
		"AttributeBaseAgility2" "34.75"
		"AttributeBaseIntelligence2" "69.5"
		"AttributeBaseStrength3" "44.55"
		"AttributeBaseAgility3" "44.55"
		"AttributeBaseIntelligence3" "89.1"
		"AttributeBaseStrength4" "56.8"
		"AttributeBaseAgility4" "56.8"
		"AttributeBaseIntelligence4" "113.6"
		"AttributeBaseStrength5" "72.725"
		"AttributeBaseAgility5" "72.725"
		"AttributeBaseIntelligence5" "145.45"
		"AttributeBaseStrength6" "572.725"
		"AttributeBaseAgility6" "572.725"
		"AttributeBaseIntelligence6" "645.45"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Brewmaster_Fire"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/brewmaster/brewmaster_firespirit.vmdl"
		"ModelScale" "0.8"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t34" {
		"CardName" "item_building_hero_t34"
		"HeroId" "101098"
		"vscripts" "npc/units/building/tower/building_hero_t34"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "puppet_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.33"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "54"
		"AttributeBaseAgility1" "18"
		"AttributeBaseIntelligence1" "27"
		"AttributeBaseStrength2" "83.4"
		"AttributeBaseAgility2" "27.8"
		"AttributeBaseIntelligence2" "41.7"
		"AttributeBaseStrength3" "106.92"
		"AttributeBaseAgility3" "35.64"
		"AttributeBaseIntelligence3" "53.46"
		"AttributeBaseStrength4" "136.32"
		"AttributeBaseAgility4" "45.44"
		"AttributeBaseIntelligence4" "68.16"
		"AttributeBaseStrength5" "174.54"
		"AttributeBaseAgility5" "58.18"
		"AttributeBaseIntelligence5" "87.27"
		"AttributeBaseStrength6" "674.54"
		"AttributeBaseAgility6" "558.18"
		"AttributeBaseIntelligence6" "587.27"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_golem_a/neutral_creep_golem_a.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t35" {
		"CardName" "item_building_hero_t35"
		"HeroId" "102099"
		"vscripts" "npc/units/building/tower/building_hero_t35"
		"Rarity" "SR"
		"Population" "2"
		"Relation_1" "hellfire_1"
		"level_upgrades" "1"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "180"
		"AttackDamageMax" "227"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1100"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength1" "110"
		"AttributeBaseAgility1" "110"
		"AttributeBaseIntelligence1" "110"
		"AttributeBaseStrength2" "167"
		"AttributeBaseAgility2" "167"
		"AttributeBaseIntelligence2" "167"
		"AttributeBaseStrength3" "212.6"
		"AttributeBaseAgility3" "212.6"
		"AttributeBaseIntelligence3" "212.6"
		"AttributeBaseStrength4" "269.6"
		"AttributeBaseAgility4" "269.6"
		"AttributeBaseIntelligence4" "269.6"
		"AttributeBaseStrength5" "343.7"
		"AttributeBaseAgility5" "343.7"
		"AttributeBaseIntelligence5" "343.7"
		"AttributeBaseStrength6" "843.7"
		"AttributeBaseAgility6" "843.7"
		"AttributeBaseIntelligence6" "843.7"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Hero_WarlockGolem"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_warlock.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/items/warlock/golem/hellsworn_golem/hellsworn_golem.vmdl"
		"ModelScale" "1"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t36" {
		"CardName" "item_building_hero_t36"
		"HeroId" "101100"
		"vscripts" "npc/units/building/tower/building_hero_t36"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "hostile_2"
		"Relation_2" "dragon_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.83"
		"RingRadius" "70"
		"AttackRange" "1200"
		"AttackAcquisitionRange" "1500"
		"ProjectileModel" "particles/neutral_fx/black_dragon_attack.vpcf"
		"ProjectileSpeed" "1600"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "54"
		"AttributeBaseAgility1" "27"
		"AttributeBaseIntelligence1" "9"
		"AttributeBaseStrength2" "83.4"
		"AttributeBaseAgility2" "41.7"
		"AttributeBaseIntelligence2" "13.9"
		"AttributeBaseStrength3" "106.92"
		"AttributeBaseAgility3" "53.46"
		"AttributeBaseIntelligence3" "17.82"
		"AttributeBaseStrength4" "136.32"
		"AttributeBaseAgility4" "68.16"
		"AttributeBaseIntelligence4" "22.72"
		"AttributeBaseStrength5" "174.54"
		"AttributeBaseAgility5" "87.27"
		"AttributeBaseIntelligence5" "29.09"
		"AttributeBaseStrength6" "674.54"
		"AttributeBaseAgility6" "587.27"
		"AttributeBaseIntelligence6" "529.09"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Ranged"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_black_dragon/n_creep_black_dragon.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t37" {
		"CardName" "item_building_hero_t37"
		"HeroId" "101101"
		"vscripts" "npc/units/building/tower/building_hero_t37"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "elements_4"
		"Relation_2" "void_2"
		"level_upgrades" "10"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "900"
		"AttackAcquisitionRange" "1300"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength1" "36"
		"AttributeBaseAgility1" "18"
		"AttributeBaseIntelligence1" "36"
		"AttributeBaseStrength2" "55.6"
		"AttributeBaseAgility2" "27.8"
		"AttributeBaseIntelligence2" "55.6"
		"AttributeBaseStrength3" "71.28"
		"AttributeBaseAgility3" "35.64"
		"AttributeBaseIntelligence3" "71.28"
		"AttributeBaseStrength4" "90.88"
		"AttributeBaseAgility4" "45.44"
		"AttributeBaseIntelligence4" "90.88"
		"AttributeBaseStrength5" "116.36"
		"AttributeBaseAgility5" "58.18"
		"AttributeBaseIntelligence5" "116.36"
		"AttributeBaseStrength6" "616.36"
		"AttributeBaseAgility6" "558.18"
		"AttributeBaseIntelligence6" "616.36"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "Brewmaster_Earth"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/heroes/brewmaster/brewmaster_voidspirit.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_hero_t41" {
		"CardName" "item_building_hero_t41"
		"HeroId" "101102"
		"vscripts" "npc/units/building/tower/building_hero_t41"
		"Rarity" "R"
		"Population" "1"
		"Relation_1" "troll_2"
		"level_upgrades" "9"
		"Ability1" "lina_1"
		"Ability2" "lina_2"
		"Ability3" "lina_3"
		"Ability4" "building_auto_findtreasure"
		"Ability6" "ability_tp"
		"StatusMana" "450"
		"StatusManaRegen" "1"
		"StatusEnergy" "100"
		"AttackEnergy" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "62"
		"AttackDamageMax" "68"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.3"
		"RingRadius" "70"
		"AttackRange" "800"
		"AttackAcquisitionRange" "1200"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength1" "22.5"
		"AttributeBaseAgility1" "58.5"
		"AttributeBaseIntelligence1" "9"
		"AttributeBaseStrength2" "34.75"
		"AttributeBaseAgility2" "90.35"
		"AttributeBaseIntelligence2" "13.9"
		"AttributeBaseStrength3" "44.55"
		"AttributeBaseAgility3" "115.83"
		"AttributeBaseIntelligence3" "17.82"
		"AttributeBaseStrength4" "56.8"
		"AttributeBaseAgility4" "147.68"
		"AttributeBaseIntelligence4" "22.72"
		"AttributeBaseStrength5" "72.725"
		"AttributeBaseAgility5" "189.085"
		"AttributeBaseIntelligence5" "29.09"
		"AttributeBaseStrength6" "572.725"
		"AttributeBaseAgility6" "689.085"
		"AttributeBaseIntelligence6" "529.09"
		"UnitLabel" "HERO"
		"HasInventory" "1"
		"InventorySlots" "6"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"SoundSet" "n_creep_Melee"
		"GameSoundsFile" "soundevents/game_sounds_creeps.vsndevts"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "1.9"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/creeps/neutral_creeps/n_creep_troll_dark_a/n_creep_troll_dark_a.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}
		"IsShow" "1"

	}
	"building_unit_mango_tree" {
		"CardName" "item_building_unit_mango_tree"
		"HeroId" "101103"
		"vscripts" "npc/units/building/tower/building_unit_mango_tree"
		"Rarity" "R"
		"Population" "1"
		"level_upgrades" "1"
		"StatusMana" "450"
		"StatusManaRegen" "0"
		"StatusEnergy" "200"
		"AttackEnergy" "2"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0"
		"RingRadius" "70"
		"AttackRange" "0"
		"AttackAcquisitionRange" "300"
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"UnitLabel" "1"
		"InventorySlots" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"BaseClass" "npc_dota_creature"
		"AbilityLayout" "6"
		"HealthBarOffset" "275"
		"MovementSpeed" "210"
		"MovementTurnRate" "0.5"
		"HasAggressiveStance" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.25"
		"Model" "models/props_tree/mango_tree.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}
		"IsShow" "0"

	}

}
