
export interface KvAllInterface  {
"npc_heroes_custom": npc_heroes_custom.OBJ_1_1,
"dota_items": dota_items.OBJ_1_1,
"dota_abilities": dota_abilities.OBJ_1_1,
"shipin_config": shipin_config.OBJ_1_1,
"lang_config": lang_config.OBJ_1_1,
"publicshop_config": publicshop_config.OBJ_1_1,
"courier_units": courier_units.OBJ_1_1,
"building_item_card": building_item_card.OBJ_1_1,
"building_round": building_round.OBJ_1_1,
"building_round_board": building_round_board.OBJ_1_1,
"building_round_challenge": building_round_challenge.OBJ_1_1,
"building_round_board_challenge": building_round_board_challenge.OBJ_1_1,
"building_unit_tower": building_unit_tower.OBJ_1_1,
"building_unit_enemy": building_unit_enemy.OBJ_1_1,
"building_config": building_config.OBJ_1_1,
"building_unit_summoned": building_unit_summoned.OBJ_1_1,
"building_ability_tower": building_ability_tower.OBJ_1_1,
"courier_abilities": courier_abilities.OBJ_1_1,
}
export const KvAllPath = {
"npc_heroes_custom": "scripts/npc/npc_heroes_custom.txt",
"dota_items": "scripts/npc/dota/dota_items.kv",
"dota_abilities": "scripts/npc/dota/dota_abilities.kv",
"shipin_config": "scripts/npc/kvConfig/shipin_config.kv",
"lang_config": "scripts/npc/kvConfig/lang_config.kv",
"publicshop_config": "scripts/npc/kvConfig/publicshop_config.kv",
"courier_units": "scripts/npc/units/courier_units.kv",
"building_item_card": "scripts/npc/building/building_item_card.kv",
"building_round": "scripts/npc/building/building_round.kv",
"building_round_board": "scripts/npc/building/building_round_board.kv",
"building_round_challenge": "scripts/npc/building/building_round_challenge.kv",
"building_round_board_challenge": "scripts/npc/building/building_round_board_challenge.kv",
"building_unit_tower": "scripts/npc/building/building_unit_tower.kv",
"building_unit_enemy": "scripts/npc/building/building_unit_enemy.kv",
"building_config": "scripts/npc/building/building_config.kv",
"building_unit_summoned": "scripts/npc/building/building_unit_summoned.kv",
"building_ability_tower": "scripts/npc/building/building_ability_tower.kv",
"courier_abilities": "scripts/npc/abilities/courier_abilities.kv",
}
export interface KvServerInterface   {
"npc_heroes_custom": npc_heroes_custom.OBJ_1_1,
"dota_items": dota_items.OBJ_1_1,
"dota_abilities": dota_abilities.OBJ_1_1,
"shipin_config": shipin_config.OBJ_1_1,
"lang_config": lang_config.OBJ_1_1,
"publicshop_config": publicshop_config.OBJ_1_1,
"courier_units": courier_units.OBJ_1_1,
"building_item_card": building_item_card.OBJ_1_1,
"building_round": building_round.OBJ_1_1,
"building_round_board": building_round_board.OBJ_1_1,
"building_round_challenge": building_round_challenge.OBJ_1_1,
"building_round_board_challenge": building_round_board_challenge.OBJ_1_1,
"building_unit_tower": building_unit_tower.OBJ_1_1,
"building_unit_enemy": building_unit_enemy.OBJ_1_1,
"building_config": building_config.OBJ_1_1,
"building_unit_summoned": building_unit_summoned.OBJ_1_1,
"building_ability_tower": building_ability_tower.OBJ_1_1,
"courier_abilities": courier_abilities.OBJ_1_1,
}
export const KvServer = {
"npc_heroes_custom": "scripts/npc/npc_heroes_custom.txt",
"dota_items": "scripts/npc/dota/dota_items.kv",
"dota_abilities": "scripts/npc/dota/dota_abilities.kv",
"shipin_config": "scripts/npc/kvConfig/shipin_config.kv",
"lang_config": "scripts/npc/kvConfig/lang_config.kv",
"publicshop_config": "scripts/npc/kvConfig/publicshop_config.kv",
"courier_units": "scripts/npc/units/courier_units.kv",
"building_item_card": "scripts/npc/building/building_item_card.kv",
"building_round": "scripts/npc/building/building_round.kv",
"building_round_board": "scripts/npc/building/building_round_board.kv",
"building_round_challenge": "scripts/npc/building/building_round_challenge.kv",
"building_round_board_challenge": "scripts/npc/building/building_round_board_challenge.kv",
"building_unit_tower": "scripts/npc/building/building_unit_tower.kv",
"building_unit_enemy": "scripts/npc/building/building_unit_enemy.kv",
"building_config": "scripts/npc/building/building_config.kv",
"building_unit_summoned": "scripts/npc/building/building_unit_summoned.kv",
"building_ability_tower": "scripts/npc/building/building_ability_tower.kv",
"courier_abilities": "scripts/npc/abilities/courier_abilities.kv",
}
export interface KvClientInterface   {
"npc_heroes_custom": npc_heroes_custom.OBJ_1_1,
"dota_items": dota_items.OBJ_1_1,
"dota_abilities": dota_abilities.OBJ_1_1,
"shipin_config": shipin_config.OBJ_1_1,
"lang_config": lang_config.OBJ_1_1,
"publicshop_config": publicshop_config.OBJ_1_1,
"courier_units": courier_units.OBJ_1_1,
"building_item_card": building_item_card.OBJ_1_1,
"building_round": building_round.OBJ_1_1,
"building_round_board": building_round_board.OBJ_1_1,
"building_round_challenge": building_round_challenge.OBJ_1_1,
"building_round_board_challenge": building_round_board_challenge.OBJ_1_1,
"building_unit_tower": building_unit_tower.OBJ_1_1,
"building_unit_enemy": building_unit_enemy.OBJ_1_1,
"building_config": building_config.OBJ_1_1,
"building_unit_summoned": building_unit_summoned.OBJ_1_1,
"building_ability_tower": building_ability_tower.OBJ_1_1,
"courier_abilities": courier_abilities.OBJ_1_1,
}
export const KvClient = {
"npc_heroes_custom": "scripts/npc/npc_heroes_custom.txt",
"dota_items": "scripts/npc/dota/dota_items.kv",
"dota_abilities": "scripts/npc/dota/dota_abilities.kv",
"shipin_config": "scripts/npc/kvConfig/shipin_config.kv",
"lang_config": "scripts/npc/kvConfig/lang_config.kv",
"publicshop_config": "scripts/npc/kvConfig/publicshop_config.kv",
"courier_units": "scripts/npc/units/courier_units.kv",
"building_item_card": "scripts/npc/building/building_item_card.kv",
"building_round": "scripts/npc/building/building_round.kv",
"building_round_board": "scripts/npc/building/building_round_board.kv",
"building_round_challenge": "scripts/npc/building/building_round_challenge.kv",
"building_round_board_challenge": "scripts/npc/building/building_round_board_challenge.kv",
"building_unit_tower": "scripts/npc/building/building_unit_tower.kv",
"building_unit_enemy": "scripts/npc/building/building_unit_enemy.kv",
"building_config": "scripts/npc/building/building_config.kv",
"building_unit_summoned": "scripts/npc/building/building_unit_summoned.kv",
"building_ability_tower": "scripts/npc/building/building_ability_tower.kv",
"courier_abilities": "scripts/npc/abilities/courier_abilities.kv",
}
export const allAbilitys = ["courier_abilities","building_ability_tower"];
export type KV_Abilitys = courier_abilities.OBJ_1_1|building_ability_tower.OBJ_1_1;
export const allItems = ["building_item_card"];
export type KV_Items = building_item_card.OBJ_1_1;
export const allUnits = ["building_unit_enemy","building_unit_tower","building_unit_summoned"];
export type KV_Units = building_unit_enemy.OBJ_1_1|building_unit_tower.OBJ_1_1|building_unit_summoned.OBJ_1_1;
