
export interface KvAllInterface  {
"npc_heroes_custom": npc_heroes_custom.OBJ_1_1,
"dota_items": dota_items.OBJ_1_1,
"dota_abilities": dota_abilities.OBJ_1_1,
"lang_config": lang_config.OBJ_1_1,
"common_units": common_units.OBJ_1_1,
"courier_units": courier_units.OBJ_1_1,
"building_item_card": building_item_card.OBJ_1_1,
"building_unit_tower": building_unit_tower.OBJ_1_1,
"building_unit_enemy": building_unit_enemy.OBJ_1_1,
"building_unit_summoned": building_unit_summoned.OBJ_1_1,
"building_ability_tower": building_ability_tower.OBJ_1_1,
"courier_abilities": courier_abilities.OBJ_1_1,
"imba_abilities": imba_abilities.OBJ_1_1,
"imba_items": imba_items.OBJ_1_1,
"artifact_items": artifact_items.OBJ_1_1,
}
export const KvAllPath = {
"npc_heroes_custom": "scripts/npc/npc_heroes_custom.txt",
"dota_items": "scripts/npc/dota/dota_items.kv",
"dota_abilities": "scripts/npc/dota/dota_abilities.kv",
"lang_config": "scripts/npc/kvConfig/lang_config.kv",
"common_units": "scripts/npc/units/common_units.kv",
"courier_units": "scripts/npc/units/courier_units.kv",
"building_item_card": "scripts/npc/building/building_item_card.kv",
"building_unit_tower": "scripts/npc/building/building_unit_tower.kv",
"building_unit_enemy": "scripts/npc/building/building_unit_enemy.kv",
"building_unit_summoned": "scripts/npc/building/building_unit_summoned.kv",
"building_ability_tower": "scripts/npc/building/building_ability_tower.kv",
"courier_abilities": "scripts/npc/abilities/courier_abilities.kv",
"imba_abilities": "scripts/npc/abilities/imba_abilities.kv",
"imba_items": "scripts/npc/items/imba_items.kv",
"artifact_items": "scripts/npc/items/artifact_items.kv",
}
export interface KvServerInterface   {
"npc_heroes_custom": npc_heroes_custom.OBJ_1_1,
"dota_items": dota_items.OBJ_1_1,
"dota_abilities": dota_abilities.OBJ_1_1,
"lang_config": lang_config.OBJ_1_1,
"common_units": common_units.OBJ_1_1,
"courier_units": courier_units.OBJ_1_1,
"building_item_card": building_item_card.OBJ_1_1,
"building_unit_tower": building_unit_tower.OBJ_1_1,
"building_unit_enemy": building_unit_enemy.OBJ_1_1,
"building_unit_summoned": building_unit_summoned.OBJ_1_1,
"building_ability_tower": building_ability_tower.OBJ_1_1,
"courier_abilities": courier_abilities.OBJ_1_1,
"imba_abilities": imba_abilities.OBJ_1_1,
"imba_items": imba_items.OBJ_1_1,
"artifact_items": artifact_items.OBJ_1_1,
}
export const KvServer = {
"npc_heroes_custom": "scripts/npc/npc_heroes_custom.txt",
"dota_items": "scripts/npc/dota/dota_items.kv",
"dota_abilities": "scripts/npc/dota/dota_abilities.kv",
"lang_config": "scripts/npc/kvConfig/lang_config.kv",
"common_units": "scripts/npc/units/common_units.kv",
"courier_units": "scripts/npc/units/courier_units.kv",
"building_item_card": "scripts/npc/building/building_item_card.kv",
"building_unit_tower": "scripts/npc/building/building_unit_tower.kv",
"building_unit_enemy": "scripts/npc/building/building_unit_enemy.kv",
"building_unit_summoned": "scripts/npc/building/building_unit_summoned.kv",
"building_ability_tower": "scripts/npc/building/building_ability_tower.kv",
"courier_abilities": "scripts/npc/abilities/courier_abilities.kv",
"imba_abilities": "scripts/npc/abilities/imba_abilities.kv",
"imba_items": "scripts/npc/items/imba_items.kv",
"artifact_items": "scripts/npc/items/artifact_items.kv",
}
export interface KvClientInterface   {
"npc_heroes_custom": npc_heroes_custom.OBJ_1_1,
"dota_items": dota_items.OBJ_1_1,
"dota_abilities": dota_abilities.OBJ_1_1,
"lang_config": lang_config.OBJ_1_1,
"common_units": common_units.OBJ_1_1,
"courier_units": courier_units.OBJ_1_1,
"building_item_card": building_item_card.OBJ_1_1,
"building_unit_tower": building_unit_tower.OBJ_1_1,
"building_unit_enemy": building_unit_enemy.OBJ_1_1,
"building_unit_summoned": building_unit_summoned.OBJ_1_1,
"building_ability_tower": building_ability_tower.OBJ_1_1,
"courier_abilities": courier_abilities.OBJ_1_1,
"imba_abilities": imba_abilities.OBJ_1_1,
"imba_items": imba_items.OBJ_1_1,
"artifact_items": artifact_items.OBJ_1_1,
}
export const KvClient = {
"npc_heroes_custom": "scripts/npc/npc_heroes_custom.txt",
"dota_items": "scripts/npc/dota/dota_items.kv",
"dota_abilities": "scripts/npc/dota/dota_abilities.kv",
"lang_config": "scripts/npc/kvConfig/lang_config.kv",
"common_units": "scripts/npc/units/common_units.kv",
"courier_units": "scripts/npc/units/courier_units.kv",
"building_item_card": "scripts/npc/building/building_item_card.kv",
"building_unit_tower": "scripts/npc/building/building_unit_tower.kv",
"building_unit_enemy": "scripts/npc/building/building_unit_enemy.kv",
"building_unit_summoned": "scripts/npc/building/building_unit_summoned.kv",
"building_ability_tower": "scripts/npc/building/building_ability_tower.kv",
"courier_abilities": "scripts/npc/abilities/courier_abilities.kv",
"imba_abilities": "scripts/npc/abilities/imba_abilities.kv",
"imba_items": "scripts/npc/items/imba_items.kv",
"artifact_items": "scripts/npc/items/artifact_items.kv",
}
export const allAbilitys = ["courier_abilities","imba_abilities","building_ability_tower"];
export type KV_Abilitys = courier_abilities.OBJ_1_1|imba_abilities.OBJ_1_1|building_ability_tower.OBJ_1_1;
export const allItems = ["building_item_card","imba_items","artifact_items"];
export type KV_Items = building_item_card.OBJ_1_1|imba_items.OBJ_1_1|artifact_items.OBJ_1_1;
export const allUnits = ["building_unit_enemy","building_unit_tower","building_unit_summoned","common_units"];
export type KV_Units = building_unit_enemy.OBJ_1_1|building_unit_tower.OBJ_1_1|building_unit_summoned.OBJ_1_1|common_units.OBJ_1_1;
