// generate with PIPIXIA's kv generator 
export namespace building_combination_ability { 
export interface OBJ_0_1 {
"building_combination_ability" :OBJ_1_1 ,
}
export interface OBJ_1_1 {
"phyarm_up_3_ursa" :OBJ_2_1 ,
"phyarm_up_6_ursa" :OBJ_2_1 ,
"phyarm_up_9_ursa" :OBJ_2_1 ,
"phyarm_up_3_kunkka" :OBJ_2_1 ,
"phyarm_up_6_kunkka" :OBJ_2_1 ,
"phyarm_up_9_kunkka" :OBJ_2_1 ,
"phyarm_up_3_tusk" :OBJ_2_1 ,
"phyarm_up_6_tusk" :OBJ_2_1 ,
"phyarm_up_9_tusk" :OBJ_2_1 ,
"phyarm_up_3_axe" :OBJ_2_1 ,
"phyarm_up_6_axe" :OBJ_2_1 ,
"phyarm_up_9_axe" :OBJ_2_1 ,
"phyarm_up_3_juggernaut" :OBJ_2_1 ,
"phyarm_up_6_juggernaut" :OBJ_2_1 ,
"phyarm_up_9_juggernaut" :OBJ_2_1 ,
"phyarm_up_3_troll_warlord" :OBJ_2_1 ,
"phyarm_up_6_troll_warlord" :OBJ_2_1 ,
"phyarm_up_9_troll_warlord" :OBJ_2_1 ,
"phyarm_up_3_slardar" :OBJ_2_1 ,
"phyarm_up_6_slardar" :OBJ_2_1 ,
"phyarm_up_9_slardar" :OBJ_2_1 ,
"phyarm_up_3_sven" :OBJ_2_1 ,
"phyarm_up_6_sven" :OBJ_2_1 ,
"phyarm_up_9_sven" :OBJ_2_1 ,
"phyarm_up_3_mars" :OBJ_2_1 ,
"phyarm_up_6_mars" :OBJ_2_1 ,
"phyarm_up_9_mars" :OBJ_2_1 ,
"phyarm_up_3_primal_beast" :OBJ_2_1 ,
"phyarm_up_6_primal_beast" :OBJ_2_1 ,
"phyarm_up_9_primal_beast" :OBJ_2_1 ,
"phyarm_up_3_skeleton_king" :OBJ_2_1 ,
"phyarm_up_6_skeleton_king" :OBJ_2_1 ,
"phyarm_up_9_skeleton_king" :OBJ_2_1 ,
"phyarm_up_3_pudge" :OBJ_2_1 ,
"phyarm_up_6_pudge" :OBJ_2_1 ,
"phyarm_up_9_pudge" :OBJ_2_1 ,
[k:string] : OBJ_2_1 }
export interface OBJ_2_1 {
"relation" :string ,
"relationicon" :string ,
"relationid" :string ,
"index" :string ,
"active_count" :string ,
"acitve_common_effect" :string ,
"Abilityid" :string ,
[k:string] : string }
}