// generate with  kv generator 

"DOTAUnits" {
	"npc_dota_invoker_forged_spirit" {
		"UnitLabel" "forged_spirits"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/invoker/forge_spirit.vmdl"
		"ModelScale" "1.0"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"HealthBarOffset" "270"
		"MovementSpeed" "320"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "2"
		"MagicalResistance" "0"
		"StatusHealth" "5"
		"StatusHealthRegen" "0.25"
		"StatusMana" "5"
		"StatusManaRegen" "5.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.5"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.2"
		"AttackRange" "250"
		"AttackAcquisitionRange" "900"
		"ProjectileModel" "particles/units/heroes/hero_invoker/invoker_forged_spirit_projectile.vpcf"
		"ProjectileSpeed" "1000"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_imba_mars_arena_of_blood_soldier" {
		"BaseClass" "npc_dota_phantomassassin_gravestone"
		"Model" "models/development/invisiblebox.vmdl"
		"ModelScale" "1.0"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "0"
		"VisionNighttimeRange" "0"
		"HealthBarOffset" "170"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0.25"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.0"
		"AttackAnimationPoint" "0.0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"Creature" {

		}

	}
	"npc_dota_undying_imba_tombstone" {
		"BaseClass" "npc_dota_unit_undying_tombstone"
		"Model" "models/heroes/undying/undying_tower.vmdl"
		"ModelScale" ".8"
		"SoundSet" "Undying_Tombstone"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "1800"
		"Ability1" "neutral_spell_immunity"
		"Ability2" "imba_undying_tombstone_aura"
		"HealthBarOffset" "250"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0.0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "16"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_undying_imba_zombie" {
		"BaseClass" "npc_dota_unit_undying_zombie"
		"Model" "models/heroes/undying/undying_minion.vmdl"
		"ModelScale" "1.05"
		"SoundSet" "Undying_Zombie"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALLEST"
		"VisionDaytimeRange" "1400"
		"VisionNighttimeRange" "1400"
		"RingRadius" "70"
		"Ability1" "imba_undying_tombstone_zombie_deathlust"
		"Ability2" "neutral_spell_immunity"
		"HealthBarOffset" "160"
		"MovementSpeed" "375"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "33"
		"StatusHealth" "2"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "44"
		"AttackDamageMax" "48"
		"AttackRate" "1.6"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "128"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_undying_imba_zombie_torso" {
		"BaseClass" "npc_dota_unit_undying_zombie"
		"Model" "models/heroes/undying/undying_minion_torso.vmdl"
		"ModelScale" "1.05"
		"SoundSet" "Undying_Zombie"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALLEST"
		"VisionDaytimeRange" "1400"
		"VisionNighttimeRange" "1400"
		"RingRadius" "70"
		"Ability1" "imba_undying_tombstone_zombie_deathlust"
		"Ability2" "neutral_spell_immunity"
		"HealthBarOffset" "160"
		"MovementSpeed" "375"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "33"
		"StatusHealth" "2"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "44"
		"AttackDamageMax" "48"
		"AttackRate" "1.6"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "128"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_hero_hell_empress" {
		"BaseClass" "npc_dota_hero_abyssal_underlord"
		"Model" "models/heroes/abyssal_underlord/abyssal_underlord_v2.vmdl"
		"ModelScale" "1.080000"
		"SoundSet" "Hero_AbyssalUnderlord"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"RingRadius" "70"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_hell_empress.vsndevts"
		"Ability1" "imba_empress_eleven_curses"
		"Ability2" "imba_empress_hellbolt"
		"Ability3" "imba_empress_royal_wrath"
		"Ability4" "imba_empress_ambient_effects"
		"Ability6" "imba_empress_hurl_through_hell"
		"Ability10" "special_bonus_magic_resistance_15"
		"Ability11" "special_bonus_armor_6"
		"Ability12" "special_bonus_attack_damage_40"
		"Ability13" "special_bonus_mp_300"
		"Ability14" "special_bonus_cast_range_150"
		"Ability15" "special_bonus_spell_amplify_10"
		"Ability16" "special_bonus_cooldown_reduction_15"
		"Ability17" "special_bonus_imba_empress_royal_wrath_cooldown"
		"HealthBarOffset" "240"
		"MovementSpeed" "315"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.4"
		"ArmorPhysical" "-1"
		"MagicalResistance" "25"
		"StatusHealth" "200"
		"StatusHealthRegen" "3.0"
		"StatusMana" "50"
		"StatusManaRegen" "1.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "30"
		"AttackDamageMax" "40"
		"AttackRate" "1.700"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.450000"
		"AttackRange" "250"
		"AttackAcquisitionRange" "600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength" "24"
		"AttributeStrengthGain" "2.4"
		"AttributeBaseAgility" "22"
		"AttributeAgilityGain" "2.0"
		"AttributeBaseIntelligence" "24"
		"AttributeIntelligenceGain" "3.6"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_hero_malfurion" {
		"BaseClass" "npc_dota_hero_ursa"
		"Model" "models/items/lone_druid/true_form/form_of_the_atniw/form_of_the_atniw.vmdl"
		"ModelScale" "0.87"
		"SoundSet" "Hero_Ursa"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"RingRadius" "70"
		"Ability1" "imba_malfurion_entrangling_roots"
		"Ability2" "imba_malfurion_rejuvenation"
		"Ability3" "imba_malfurion_mark_of_the_claw"
		"Ability4" "imba_malfurion_strength_of_the_wild"
		"Ability6" "imba_malfurion_living_tower"
		"Ability10" "special_bonus_imba_malfurion_1"
		"Ability11" "special_bonus_imba_malfurion_2"
		"Ability12" "special_bonus_attack_damage_40"
		"Ability13" "special_bonus_cooldown_reduction_12"
		"Ability14" "special_bonus_strength_25"
		"Ability15" "special_bonus_imba_malfurion_5"
		"Ability16" "special_bonus_imba_malfurion_4"
		"Ability17" "special_bonus_imba_malfurion_3"
		"HealthBarOffset" "220"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.4"
		"ArmorPhysical" "2.1"
		"MagicalResistance" "25"
		"StatusHealth" "200"
		"StatusHealthRegen" "2.1"
		"StatusMana" "50"
		"StatusManaRegen" "1.05"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "26"
		"AttackDamageMax" "36"
		"AttackRate" "1.6"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.300"
		"AttackRange" "128"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "42"
		"AttributeStrengthGain" "3.15"
		"AttributeBaseAgility" "31.5"
		"AttributeAgilityGain" "2.1"
		"AttributeBaseIntelligence" "21"
		"AttributeIntelligenceGain" "2.1"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_hero_nian" {
		"BaseClass" "npc_dota_hero_mirana"
		"Model" "models/creeps/nian/nian_creep.vmdl"
		"ModelScale" "0.4"
		"SoundSet" "cny_beast"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"particle_folder" "particles/units/heroes/hero_chen"
		"Ability1" "imba_nian_frenzy_swipes"
		"Ability2" "imba_nian_crushing_leap"
		"Ability3" "imba_nian_tail_spin"
		"Ability6" "imba_nian_volcanic_burster"
		"Ability10" "special_bonus_imba_nian_crushing_leap_cast_range"
		"Ability11" "special_bonus_attack_damage_25"
		"Ability12" "special_bonus_imba_nian_frenzy_swipes_upgrade"
		"Ability13" "special_bonus_magic_resistance_20"
		"Ability14" "special_bonus_imba_nian_tail_spin_pierces_spell_immunity"
		"Ability15" "special_bonus_movement_speed_40"
		"Ability16" "special_bonus_imba_nian_crushing_leap_cooldown"
		"Ability17" "special_bonus_all_stats_15"
		"MovementSpeed" "300"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "4"
		"MagicalResistance" "25"
		"StatusHealth" "200"
		"StatusHealthRegen" "5.0"
		"StatusMana" "75"
		"StatusManaRegen" "1.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "30"
		"AttackDamageMax" "30"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "175"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength" "25"
		"AttributeStrengthGain" "2.5"
		"AttributeBaseAgility" "25"
		"AttributeAgilityGain" "2.5"
		"AttributeBaseIntelligence" "25"
		"AttributeIntelligenceGain" "2.5"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_hero_sohei" {
		"BaseClass" "npc_dota_hero_juggernaut"
		"Model" "models/heroes/sohei/sohei.vmdl"
		"SoundSet" "Sohei"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_sohei.vsndevts"
		"particle_folder" "particles/hero/sohei"
		"Ability1" "sohei_dash"
		"Ability2" "sohei_wholeness_of_body"
		"Ability3" "sohei_momentum"
		"Ability4" "sohei_palm_of_life"
		"Ability6" "sohei_flurry_of_blows"
		"Ability10" "special_bonus_cleave_25"
		"Ability11" "special_bonus_lifesteal_10"
		"Ability12" "special_bonus_strength_20"
		"Ability13" "special_bonus_imba_sohei_wholeness_of_body_heal"
		"Ability14" "special_bonus_movement_speed_60"
		"Ability15" "special_bonus_imba_sohei_wholeness_allycast"
		"Ability16" "special_bonus_hp_700"
		"Ability17" "special_bonus_sohei_fob_radius"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "1.5"
		"ArmorPhysical" "5"
		"MagicalResistance" "25"
		"StatusHealth" "200"
		"StatusHealthRegen" "3.25"
		"StatusMana" "75"
		"StatusManaRegen" "0.9"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "31"
		"AttackDamageMax" "33"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.30"
		"AttackRange" "150"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "23"
		"AttributeStrengthGain" "4.0"
		"AttributeBaseAgility" "18"
		"AttributeAgilityGain" "1.5"
		"AttributeBaseIntelligence" "17"
		"AttributeIntelligenceGain" "1.5"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_hero_vardor" {
		"BaseClass" "npc_dota_hero_phantom_lancer"
		"Model" "models/heroes/phantom_lancer/phantom_lancer.vmdl"
		"ModelScale" "0.840000"
		"SoundSet" "Hero_PhantomLancer"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"RingRadius" "70"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts"
		"Ability1" "vardor_piercing_shot"
		"Ability2" "vardor_graceful_jump"
		"Ability3" "vardor_mental_thrusts"
		"Ability6" "vardor_celestial_rain_of_yari"
		"Ability10" "special_bonus_mp_350"
		"Ability11" "special_bonus_agility_12"
		"Ability12" "special_bonus_cast_range_150"
		"Ability13" "special_bonus_attack_speed_40"
		"Ability14" "special_bonus_vardor_ground_yaris_mind_bleed"
		"Ability15" "special_bonus_vardor_bonus_yari"
		"Ability16" "special_bonus_vardor_graceful_jump_root"
		"Ability17" "special_bonus_vardor_mental_thrusts_bonus"
		"HealthBarOffset" "190"
		"MovementSpeed" "305"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "3.0"
		"MagicalResistance" "25"
		"StatusHealth" "200"
		"StatusHealthRegen" "2.1"
		"StatusMana" "50"
		"StatusManaRegen" "1.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "26"
		"AttackDamageMax" "38"
		"AttackRate" "1.700"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.500000"
		"AttackRange" "128"
		"AttackAcquisitionRange" "600"
		"AttributePrimary" "DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength" "22"
		"AttributeStrengthGain" "2.3"
		"AttributeBaseAgility" "22"
		"AttributeAgilityGain" "2.7"
		"AttributeBaseIntelligence" "14"
		"AttributeIntelligenceGain" "1.6"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_vardor_spear_dummy" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/spear.vmdl"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "0"
		"VisionNighttimeRange" "0"
		"RingRadius" "60"
		"MovementSpeed" "450"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"spearholder_unit" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/dummy.vmdl"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "0"
		"VisionNighttimeRange" "0"
		"RingRadius" "60"
		"MovementSpeed" "450"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_donator_companion" {
		"UnitLabel" "donator_companion"
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/courier/doom_demihero_courier/doom_demihero_courier.vmdl"
		"ModelScale" "1.0"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "0"
		"VisionNighttimeRange" "0"
		"Ability1" "companion_morph"
		"Ability2" "neutral_spell_immunity"
		"HealthBarOffset" "240"
		"MovementSpeed" "480"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0.0"
		"StatusMana" "0"
		"StatusManaRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0.0"
		"AttackRange" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_donator_companion_demi_doom" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/doom_demihero_courier/doom_demihero_courier.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_carty" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/carty/carty.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_carty_dire" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/carty_dire/carty_dire_flying.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_llama" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/livery_llama_courier/livery_llama_courier.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_jumo" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/jumo/jumo.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_jin" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/jin_yin_white_fox/jin_yin_white_fox.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_amaterasu" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/amaterasu/amaterasu.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_boooofus" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/boooofus_courier/boooofus_courier.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_duskie" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/duskie/duskie.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_baekho" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/baekho/baekho.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_devourling" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/devourling/devourling.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_sappling" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/little_sappling_style1/little_sappling_style1.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_itsy" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/itsy/itsy.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}

	}
	"npc_donator_companion_golem" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/warlock/golem/ti_8_warlock_darkness_apostate_golem/ti_8_warlock_darkness_apostate_golem.vmdl"
		"ModelScale" "0.35"
		"Creature" {

		}

	}
	"npc_donator_companion_cookies" {
		"BaseClass" "npc_dota_roshan"
		"Model" "models/courier/baby_rosh/babyroshan.vmdl"
		"ModelScale" "0.65"
		"Creature" {

		}

	}
	"npc_donator_companion_baumi" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/baby_rosh/babyroshan.vmdl"
		"ModelScale" "0.6"
		"Creature" {

		}

	}
	"npc_donator_companion_icefrog" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/frog/frog.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_admiral_bulldog" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/lone_druid/true_form/elemental_curse_set_elemental_curse_true_form/elemental_curse_set_elemental_curse_true_form.vmdl"
		"ModelScale" "0.3"
		"Creature" {

		}

	}
	"npc_donator_companion_hamahe" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/shibe_dog_cat/shibe_dog_cat.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_suthernfriend" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/creeps/roshan/roshan.vmdl"
		"ModelScale" "0.45"
		"Creature" {

		}

	}
	"npc_donator_companion_acalia" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/heroes/enchantress/enchantress.vmdl"
		"ModelScale" "0.5"
		"Creature" {

		}

	}
	"npc_donator_companion_zonnoz" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/pudge/arcana/pudge_arcana_base.vmdl"
		"ModelScale" "0.5"
		"Creature" {

		}

	}
	"npc_donator_companion_terdic" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/shagbark/shagbark.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_vaal" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/vaal_the_animated_constructradiant/vaal_the_animated_constructradiant.vmdl"
		"ModelScale" "0.9"
		"Creature" {

		}

	}
	"npc_donator_companion_exzas" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/io/io_ti7/io_ti7.vmdl"
		"ModelScale" "0.5"
		"Creature" {

		}

	}
	"npc_donator_companion_the_blind_dog" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/gnomepig/gnomepig_flying.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_conjurist" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/donkey_unicorn/donkey_unicorn_flying.vmdl"
		"ModelScale" "0.65"
		"Creature" {

		}

	}
	"npc_donator_companion_gordon_ramsay" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/heroes/phoenix/phoenix_bird.vmdl"
		"ModelScale" "0.4"
		"Creature" {

		}

	}
	"npc_donator_companion_rayzone" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/heroes/bristleback/bristleback.vmdl"
		"ModelScale" "0.5"
		"Creature" {

		}

	}
	"npc_donator_companion_rubick_arcana" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/rubick/rubick_arcana/rubick_arcana_base.vmdl"
		"ModelScale" "0.35"
		"Creature" {

		}

	}
	"npc_donator_companion_crux" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/donkey_crummy_wizard_2014/donkey_crummy_wizard_2014_flying.vmdl"
		"ModelScale" "0.55"
		"Creature" {

		}

	}
	"npc_donator_companion_phish" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/sw_donkey/sw_donkey_flying.vmdl"
		"ModelScale" "0.6"
		"Creature" {

		}

	}
	"npc_donator_companion_juggernaut_arcana" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/heroes/juggernaut/juggernaut_arcana.vmdl"
		"ModelScale" "0.45"
		"Creature" {

		}

	}
	"npc_donator_companion_miku" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/nian_courier/nian_courier.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_vivi" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/phoenix/ultimate/golden_nirvana_golden_nirvana_nova/golden_nirvana_golden_nirvana_nova.vmdl"
		"ModelScale" "0.6"
		"Creature" {

		}

	}
	"npc_donator_companion_altivu" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/donkey_ti7/donkey_ti7_flying.vmdl"
		"ModelScale" "0.65"
		"Creature" {

		}

	}
	"npc_donator_companion_pine_tree" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/props_tree/tree_pinestatic_02.vmdl"
		"ModelScale" "0.45"
		"Creature" {

		}

	}
	"npc_donator_companion_terrorblade_arcana" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/heroes/terrorblade/terrorblade_arcana.vmdl"
		"ModelScale" "0.45"
		"Creature" {

		}

	}
	"npc_donator_companion_tinkbot" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/tinkbot/tinkbot.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_deathripper" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/deathripper/deathripper.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_butch" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/butch_pudge_dog/butch_pudge_dog.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_tory" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/tory_the_sky_guardian/tory_the_sky_guardian.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}

	}
	"npc_donator_companion_hollow_jack" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/pumpkin_courier/pumpkin_courier.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_amphibian_kid" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/amphibian_kid/amphibian_kid.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}

	}
	"npc_donator_companion_vigilante_fox" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/vigilante_fox_green/vigilante_fox_green.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_golden_venoling" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/venoling/venoling.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_raiq" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/raiq/raiq.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}

	}
	"npc_donator_companion_chocobo" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/chocobo/chocobo.vmdl"
		"ModelScale" "0.85"
		"Creature" {

		}

	}
	"npc_donator_companion_mega_greevil" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/mega_greevil_courier/mega_greevil_courier.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_snelfret" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/snail/courier_snail.vmdl"
		"ModelScale" "0.8"
		"Creature" {

		}

	}
	"npc_donator_companion_chuckles" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/items/courier/mighty_chicken/mighty_chicken.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_frog" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/courier/frog/frog.vmdl"
		"ModelScale" "0.75"
		"Creature" {

		}

	}
	"npc_donator_companion_kiddo" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/heroes/phantom_assassin/pa_arcana.vmdl"
		"ModelScale" "0.5"
		"Creature" {

		}

	}
	"npc_donator_companion_crystal_maiden_puppy" {
		"BaseClass" "npc_donator_companion"
		"Model" "models/pets/icewrack_wolf/icewrack_wolf.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/effigy_pedestal_dire.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_cookies" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/shadow_fiend/pedestal_sf.vmdl"
		"ModelScale" "2.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_developer_good" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/mesh/effigy_pedestal_fm16.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_developer_bad" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/mesh/effigy_pedestal_fm16_dire.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_golden_good" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/effigy_pedestal_ti5_lv2.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_golden_bad" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/effigy_pedestal_ti5_lv2_dire.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_ember_good" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/mesh/effigy_pedestal_ti6_lv2_model_dmx.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_ember_bad" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/mesh/effigy_pedestal_ti6_lv2_dire_model_dmx.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_salamander_good" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/effigy_pedestal_frost_radiant.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_salamander_bad" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/pedestal/effigy_pedestal_frosty_dire.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_icefrog" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/phantom_assassin/arcana_pedestal.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_pedestal_pudge_arcana" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/items/pudge/arcana/pudge_arcana_pedestal.vmdl"
		"ModelScale" "1.0"
		"Creature" {

		}

	}
	"npc_donator_statue_brewmaster_earth_spirit" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/brewmaster/brewmaster_earthspirit.vmdl"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_brewmaster_ember_spirit" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/brewmaster/brewmaster_firespirit.vmdl"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_brewmaster_storm_spirit" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/brewmaster/brewmaster_windspirit.vmdl"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_grillhound" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/items/courier/starladder_grillhound/starladder_grillhound.vmdl"
		"ModelScale" "1.5"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_llama" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/items/courier/livery_llama_courier/livery_llama_courier.vmdl"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_roshan" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/creeps/roshan/roshan.vmdl"
		"ModelScale" "0.6"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_crystal_maiden_arcana" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_cookies" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/items/courier/chocobo/chocobo.vmdl"
		"ModelScale" "1.5"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_acalia" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl"
		"ModelScale" "0.81"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_lily" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/items/undying/flesh_golem/deathmatch_dominator_golem/deathmatch_dominator_golem.vmdl"
		"ModelScale" "0.9"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_suthernfriend" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/creeps/roshan/roshan.vmdl"
		"ModelScale" "0.6"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_exzas" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/shredder/shredder.vmdl"
		"ModelScale" "0.9"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_zonnoz" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/items/courier/butch_pudge_dog/butch_pudge_dog.vmdl"
		"ModelScale" "1.1"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_tabisama" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/vr_env/vr_avatars/avatar_antimage_model.vmdl"
		"ModelScale" "1.0"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_january0000" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/creeps/neutral_creeps/n_creep_satyr_spawn_a/n_creep_satyr_spawn_a.vmdl"
		"ModelScale" "0.85"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_terdic" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/items/courier/captain_bamboo/captain_bamboo.vmdl"
		"ModelScale" "1.6"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_toc" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/huskar/huskar.vmdl"
		"ModelScale" "1.0"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_oviakin" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/rubick/rubick.vmdl"
		"ModelScale" "1.0"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_hamahe" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/items/courier/shibe_dog_cat/shibe_dog_cat_flying.vmdl"
		"ModelScale" "1.2"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_donator_statue_deadknight" {
		"BaseClass" "npc_dota_base_additive"
		"Model" ""
		"ModelScale" "1.1"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_FILLER"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "600"
		"RingRadius" "100"
		"MinimapIcon" "minimap_miscbuilding"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "260"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "14"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower1_top" {
		"ArmorPhysical" "20"
		"StatusHealth" "2600"
		"AttackRate" "0.9"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower1_mid" {
		"ArmorPhysical" "20"
		"StatusHealth" "2600"
		"AttackRate" "0.9"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower1_bot" {
		"ArmorPhysical" "20"
		"StatusHealth" "2600"
		"AttackRate" "0.9"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower1_top" {
		"ArmorPhysical" "20"
		"StatusHealth" "2600"
		"AttackRate" "0.9"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower1_mid" {
		"ArmorPhysical" "20"
		"StatusHealth" "2600"
		"AttackRate" "0.9"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower1_bot" {
		"ArmorPhysical" "20"
		"StatusHealth" "2600"
		"AttackRate" "0.9"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower2_top" {
		"ArmorPhysical" "27"
		"StatusHealth" "3200"
		"AttackDamageMin" "220"
		"AttackDamageMax" "240"
		"AttackRate" "0.8"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower2_mid" {
		"ArmorPhysical" "27"
		"StatusHealth" "3200"
		"AttackDamageMin" "220"
		"AttackDamageMax" "240"
		"AttackRate" "0.8"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower2_bot" {
		"ArmorPhysical" "27"
		"StatusHealth" "3200"
		"AttackDamageMin" "220"
		"AttackDamageMax" "240"
		"AttackRate" "0.8"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower3_top" {
		"ArmorPhysical" "35"
		"StatusHealth" "3600"
		"AttackDamageMin" "340"
		"AttackDamageMax" "360"
		"AttackRate" "0.65"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower3_mid" {
		"ArmorPhysical" "35"
		"StatusHealth" "3600"
		"AttackDamageMin" "340"
		"AttackDamageMax" "360"
		"AttackRate" "0.65"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower3_bot" {
		"ArmorPhysical" "35"
		"StatusHealth" "3600"
		"AttackDamageMin" "340"
		"AttackDamageMax" "360"
		"AttackRate" "0.65"
		"Creature" {

		}

	}
	"npc_dota_goodguys_tower4" {
		"ArmorPhysical" "40"
		"StatusHealth" "4200"
		"AttackDamageMin" "490"
		"AttackDamageMax" "510"
		"AttackRate" "0.4"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower2_top" {
		"ArmorPhysical" "27"
		"StatusHealth" "3200"
		"AttackDamageMin" "220"
		"AttackDamageMax" "240"
		"AttackRate" "0.8"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower2_mid" {
		"ArmorPhysical" "27"
		"StatusHealth" "3200"
		"AttackDamageMin" "220"
		"AttackDamageMax" "240"
		"AttackRate" "0.8"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower2_bot" {
		"ArmorPhysical" "27"
		"StatusHealth" "3200"
		"AttackDamageMin" "220"
		"AttackDamageMax" "240"
		"AttackRate" "0.8"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower3_top" {
		"ArmorPhysical" "35"
		"StatusHealth" "3600"
		"AttackDamageMin" "340"
		"AttackDamageMax" "360"
		"AttackRate" "0.65"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower3_mid" {
		"ArmorPhysical" "35"
		"StatusHealth" "3600"
		"AttackDamageMin" "340"
		"AttackDamageMax" "360"
		"AttackRate" "0.65"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower3_bot" {
		"ArmorPhysical" "35"
		"StatusHealth" "3600"
		"AttackDamageMin" "340"
		"AttackDamageMax" "360"
		"AttackRate" "0.65"
		"Creature" {

		}

	}
	"npc_dota_badguys_tower4" {
		"ArmorPhysical" "40"
		"StatusHealth" "4200"
		"AttackDamageMin" "490"
		"AttackDamageMax" "510"
		"AttackRate" "0.4"
		"Creature" {

		}

	}
	"npc_dota_goodguys_melee_rax_top" {
		"ArmorPhysical" "42"
		"StatusHealth" "3800"
		"StatusHealthRegen" "8.0"
		"Creature" {

		}

	}
	"npc_dota_goodguys_melee_rax_mid" {
		"ArmorPhysical" "42"
		"StatusHealth" "3800"
		"StatusHealthRegen" "8.0"
		"Creature" {

		}

	}
	"npc_dota_goodguys_melee_rax_bot" {
		"ArmorPhysical" "42"
		"StatusHealth" "3800"
		"StatusHealthRegen" "8.0"
		"Creature" {

		}

	}
	"npc_dota_goodguys_range_rax_top" {
		"ArmorPhysical" "20"
		"StatusHealth" "2700"
		"StatusHealthRegen" "2"
		"Creature" {

		}

	}
	"npc_dota_goodguys_range_rax_mid" {
		"ArmorPhysical" "20"
		"StatusHealth" "2700"
		"StatusHealthRegen" "2"
		"Creature" {

		}

	}
	"npc_dota_goodguys_range_rax_bot" {
		"ArmorPhysical" "20"
		"StatusHealth" "2700"
		"StatusHealthRegen" "2"
		"Creature" {

		}

	}
	"npc_dota_badguys_melee_rax_top" {
		"ArmorPhysical" "42"
		"StatusHealth" "3800"
		"StatusHealthRegen" "8.0"
		"Creature" {

		}

	}
	"npc_dota_badguys_melee_rax_mid" {
		"ArmorPhysical" "42"
		"StatusHealth" "3800"
		"StatusHealthRegen" "8.0"
		"Creature" {

		}

	}
	"npc_dota_badguys_melee_rax_bot" {
		"ArmorPhysical" "42"
		"StatusHealth" "3800"
		"StatusHealthRegen" "8.0"
		"Creature" {

		}

	}
	"npc_dota_badguys_range_rax_top" {
		"ArmorPhysical" "20"
		"StatusHealth" "2700"
		"StatusHealthRegen" "2"
		"Creature" {

		}

	}
	"npc_dota_badguys_range_rax_mid" {
		"ArmorPhysical" "20"
		"StatusHealth" "2700"
		"StatusHealthRegen" "2"
		"Creature" {

		}

	}
	"npc_dota_badguys_range_rax_bot" {
		"ArmorPhysical" "20"
		"StatusHealth" "2700"
		"StatusHealthRegen" "2"
		"Creature" {

		}

	}
	"npc_dota_goodguys_healers" {
		"ArmorPhysical" "24"
		"Creature" {

		}

	}
	"npc_dota_badguys_healers" {
		"ArmorPhysical" "24"
		"Creature" {

		}

	}
	"npc_dota_creep_goodguys_melee" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_goodguys_melee_upgraded" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_goodguys_melee_upgraded_mega" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_goodguys_ranged" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_goodguys_ranged_upgraded" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_goodguys_ranged_upgraded_mega" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_goodguys_siege" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_goodguys_siege_upgraded" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_goodguys_siege_upgraded_mega" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_badguys_melee" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_badguys_melee_upgraded" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_badguys_melee_upgraded_mega" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_badguys_ranged" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_badguys_ranged_upgraded" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_creep_badguys_ranged_upgraded_mega" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_badguys_siege" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_badguys_siege_upgraded" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_badguys_siege_upgraded_mega" {
		"Ability1" "custom_creep_scaling"
		"Creature" {

		}

	}
	"npc_dota_phantom_assassin_gravestone" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/heroes/phantom_assassin/weapon_fx.vmdl"
		"ModelScale" "1.0"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "0"
		"VisionNighttimeRange" "0"
		"HealthBarOffset" "170"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0.25"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.0"
		"AttackAnimationPoint" "0.0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"Creature" {

		}

	}
	"npc_dummy_unit" {
		"UnitLabel" "healing_ward"
		"BaseClass" "npc_dota_creep_neutral"
		"Model" "models/development/invisiblebox.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "0"
		"VisionNighttimeRange" "0"
		"Ability1" "dummy_unit_state"
		"MovementSpeed" "450"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dummy_unit_perma" {
		"UnitLabel" "healing_ward"
		"BaseClass" "npc_dota_creep_neutral"
		"Model" "models/development/invisiblebox.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "0"
		"VisionNighttimeRange" "0"
		"Ability1" "dummy_unit_state"
		"MovementSpeed" "450"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_warlock_golem_1" {
		"Ability1" "imba_warlock_flaming_fists"
		"Ability2" "imba_warlock_permanent_immolation"
		"Creature" {

		}

	}
	"npc_dota_warlock_golem_2" {
		"Ability1" "imba_warlock_flaming_fists"
		"Ability2" "imba_warlock_permanent_immolation"
		"Creature" {

		}

	}
	"npc_dota_warlock_golem_3" {
		"Ability1" "imba_warlock_flaming_fists"
		"Ability2" "imba_warlock_permanent_immolation"
		"Creature" {

		}

	}
	"npc_dota_warlock_golem_scepter_1" {
		"Ability1" "imba_warlock_flaming_fists"
		"Ability2" "imba_warlock_permanent_immolation"
		"Creature" {

		}

	}
	"npc_dota_warlock_golem_scepter_2" {
		"Ability1" "imba_warlock_flaming_fists"
		"Ability2" "imba_warlock_permanent_immolation"
		"Creature" {

		}

	}
	"npc_dota_warlock_golem_scepter_3" {
		"Ability1" "imba_warlock_flaming_fists"
		"Ability2" "imba_warlock_permanent_immolation"
		"Creature" {

		}

	}
	"npc_dota_tusk_frozen_sigil1" {
		"UnitLabel" "frozen_sigil"
		"BaseClass" "npc_dota_tusk_frozen_sigil"
		"Model" "models/heroes/tuskarr/tuskarr_sigil.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "12"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_tusk_frozen_sigil2" {
		"UnitLabel" "frozen_sigil"
		"BaseClass" "npc_dota_tusk_frozen_sigil"
		"Model" "models/heroes/tuskarr/tuskarr_sigil.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "12"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_tusk_frozen_sigil3" {
		"UnitLabel" "frozen_sigil"
		"BaseClass" "npc_dota_tusk_frozen_sigil"
		"Model" "models/heroes/tuskarr/tuskarr_sigil.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "16"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_tusk_frozen_sigil4" {
		"UnitLabel" "frozen_sigil"
		"BaseClass" "npc_dota_tusk_frozen_sigil"
		"Model" "models/heroes/tuskarr/tuskarr_sigil.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "16"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_tusk_frozen_sigil5" {
		"UnitLabel" "frozen_sigil"
		"BaseClass" "npc_dota_tusk_frozen_sigil"
		"Model" "models/heroes/tuskarr/tuskarr_sigil.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "16"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_tusk_frozen_sigil6" {
		"UnitLabel" "frozen_sigil"
		"BaseClass" "npc_dota_tusk_frozen_sigil"
		"Model" "models/heroes/tuskarr/tuskarr_sigil.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "16"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_tusk_frozen_sigil7" {
		"UnitLabel" "frozen_sigil"
		"BaseClass" "npc_dota_tusk_frozen_sigil"
		"Model" "models/heroes/tuskarr/tuskarr_sigil.vmdl"
		"SoundSet" "Creep_Good_Range"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"MovementSpeed" "310"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "16"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "500"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"imba_witch_doctor_death_ward" {
		"BaseClass" "npc_dota_witch_doctor_death_ward"
		"Model" "models/heroes/witchdoctor/witchdoctor_ward.vmdl"
		"ModelScale" "1.0"
		"BoundsHullName" "DOTA_HULL_SIZE_SIEGE"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"RingRadius" "70"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "2"
		"MagicalResistance" "0"
		"StatusHealth" "420"
		"StatusHealthRegen" "0.0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "0.0"
		"AttackDamageMax" "0.0"
		"AttackRate" "0.22"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.0"
		"AttackRange" "700"
		"AttackAcquisitionRange" "700"
		"ProjectileModel" "particles/units/heroes/hero_witchdoctor/witchdoctor_ward_attack.vpcf"
		"ProjectileSpeed" "1000"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_lycan_wolf1" {
		"UnitLabel" "lycan_wolf1"
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/lycan/summon_wolves.vmdl"
		"ModelScale" "0.9"
		"SoundSet" "Hero_Lycan.SummonWolves"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"Ability1" "imba_summoned_wolf_wicked_crunch"
		"Ability2" "imba_summoned_wolf_invisibility"
		"Ability3" "imba_summoned_wolf_hunter_instincts"
		"HealthBarOffset" "225"
		"MovementSpeed" "400"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "70"
		"StatusHealth" "300"
		"StatusHealthRegen" "0.5"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "24"
		"AttackDamageMax" "28"
		"AttackRate" "1.2"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "90"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"ConsideredHero" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_lycan_wolf2" {
		"UnitLabel" "lycan_wolf2"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lycan/wolves/ambry_summon/ambry_summon.vmdl"
		"ModelScale" "0.95"
		"SoundSet" "Hero_Lycan.SummonWolves"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"Ability1" "imba_summoned_wolf_wicked_crunch"
		"Ability2" "imba_summoned_wolf_invisibility"
		"Ability3" "imba_summoned_wolf_hunter_instincts"
		"HealthBarOffset" "225"
		"MovementSpeed" "420"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "70"
		"StatusHealth" "350"
		"StatusHealthRegen" "0.5"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "32"
		"AttackDamageMax" "36"
		"AttackRate" "1.1"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "90"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"ConsideredHero" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_lycan_wolf3" {
		"UnitLabel" "lycan_wolf3"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lycan/wolves/icewrack_pack/icewrack_pack.vmdl"
		"ModelScale" "0.98"
		"SoundSet" "Hero_Lycan.SummonWolves"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"Ability1" "imba_summoned_wolf_wicked_crunch"
		"Ability2" "imba_summoned_wolf_invisibility"
		"Ability3" "imba_summoned_wolf_hunter_instincts"
		"HealthBarOffset" "225"
		"MovementSpeed" "440"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "70"
		"StatusHealth" "400"
		"StatusHealthRegen" "0.5"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "40"
		"AttackDamageMax" "44"
		"AttackRate" "1.0"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "90"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"ConsideredHero" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_lycan_wolf4" {
		"UnitLabel" "lycan_wolf4"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lycan/wolves/alpha_summon_01/alpha_summon_01.vmdl"
		"ModelScale" "1.0"
		"SoundSet" "Hero_Lycan.SummonWolves"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"Ability1" "imba_summoned_wolf_wicked_crunch"
		"Ability2" "imba_summoned_wolf_invisibility"
		"Ability3" "imba_summoned_wolf_hunter_instincts"
		"HealthBarOffset" "225"
		"MovementSpeed" "460"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "70"
		"StatusHealth" "450"
		"StatusHealthRegen" "0.5"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "48"
		"AttackDamageMax" "52"
		"AttackRate" "0.9"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "90"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"ConsideredHero" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_lycan_wolf5" {
		"UnitLabel" "lycan_wolf5"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lycan/wolves/blood_moon_hunter_wolves/blood_moon_hunter_wolves.vmdl"
		"ModelScale" "1.02"
		"SoundSet" "Hero_Lycan.SummonWolves"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"Ability1" "imba_summoned_wolf_wicked_crunch"
		"Ability2" "imba_summoned_wolf_invisibility"
		"Ability3" "imba_summoned_wolf_hunter_instincts"
		"HealthBarOffset" "225"
		"MovementSpeed" "480"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "70"
		"StatusHealth" "500"
		"StatusHealthRegen" "0.5"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "56"
		"AttackDamageMax" "60"
		"AttackRate" "0.8"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "90"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"ConsideredHero" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_lycan_wolf6" {
		"UnitLabel" "lycan_wolf6"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lycan/wolves/hunter_kings_wolves/hunter_kings_wolves.vmdl"
		"ModelScale" "1.08"
		"SoundSet" "Hero_Lycan.SummonWolves"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"Ability1" "imba_summoned_wolf_wicked_crunch"
		"Ability2" "imba_summoned_wolf_invisibility"
		"Ability3" "imba_summoned_wolf_hunter_instincts"
		"HealthBarOffset" "225"
		"MovementSpeed" "500"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "70"
		"StatusHealth" "550"
		"StatusHealthRegen" "0.5"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "64"
		"AttackDamageMax" "68"
		"AttackRate" "0.7"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "90"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"ConsideredHero" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_lycan_summoned_wolf_talent" {
		"UnitLabel" "lycan_alpha_wolf"
		"BaseClass" "npc_dota_creature"
		"Model" "models/items/lycan/wolves/alpha_summon_01/alpha_summon_01.vmdl"
		"ModelScale" "1.2"
		"SoundSet" "Hero_Lycan.SummonWolves"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1200"
		"VisionNighttimeRange" "800"
		"Ability1" "imba_summoned_wolf_wicked_crunch"
		"Ability2" "imba_summoned_wolf_pack_leader"
		"HealthBarOffset" "225"
		"MovementSpeed" "500"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "70"
		"StatusHealth" "800"
		"StatusHealthRegen" "0.5"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "64"
		"AttackDamageMax" "68"
		"AttackRate" "0.8"
		"AttackAnimationPoint" "0.33"
		"AttackRange" "90"
		"AttackAcquisitionRange" "500"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"HasInventory" "0"
		"ConsideredHero" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_earth_1" {
		"ArmorPhysical" "3"
		"StatusHealth" "1400"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "25"
		"AttackDamageMax" "35"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_earth_2" {
		"ArmorPhysical" "5"
		"StatusHealth" "2200"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "55"
		"AttackDamageMax" "65"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_earth_3" {
		"ArmorPhysical" "7"
		"StatusHealth" "3000"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "85"
		"AttackDamageMax" "95"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_earth_4" {
		"UnitLabel" "brewmaster_earth"
		"BaseClass" "npc_dota_brewmaster_earth"
		"Model" "models/heroes/brewmaster/brewmaster_earthspirit.vmdl"
		"ModelScale" ".98"
		"SoundSet" "Brewmaster_Earth"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_earth_hurl_boulder"
		"Ability2" "brewmaster_earth_spell_immunity"
		"Ability3" "brewmaster_earth_pulverize"
		"Ability4" "brewmaster_thunder_clap"
		"HealthBarOffset" "175"
		"MovementSpeed" "325"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "5"
		"StatusHealth" "3800"
		"StatusHealthRegen" "3"
		"StatusMana" "700"
		"StatusManaRegen" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "115"
		"AttackDamageMax" "125"
		"AttackRate" "1.25"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "150"
		"AttackAcquisitionRange" "600"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_earth_5" {
		"UnitLabel" "brewmaster_earth"
		"BaseClass" "npc_dota_brewmaster_earth"
		"Model" "models/heroes/brewmaster/brewmaster_earthspirit.vmdl"
		"ModelScale" "1.05"
		"SoundSet" "Brewmaster_Earth"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_earth_hurl_boulder"
		"Ability2" "brewmaster_earth_spell_immunity"
		"Ability3" "brewmaster_earth_pulverize"
		"Ability4" "brewmaster_thunder_clap"
		"HealthBarOffset" "175"
		"MovementSpeed" "325"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "5"
		"StatusHealth" "4600"
		"StatusHealthRegen" "4"
		"StatusMana" "800"
		"StatusManaRegen" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "145"
		"AttackDamageMax" "155"
		"AttackRate" "1.25"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "150"
		"AttackAcquisitionRange" "600"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_earth_6" {
		"UnitLabel" "brewmaster_earth"
		"BaseClass" "npc_dota_brewmaster_earth"
		"Model" "models/heroes/brewmaster/brewmaster_earthspirit.vmdl"
		"ModelScale" "1.1"
		"SoundSet" "Brewmaster_Earth"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_earth_hurl_boulder"
		"Ability2" "brewmaster_earth_spell_immunity"
		"Ability3" "brewmaster_earth_pulverize"
		"Ability4" "brewmaster_thunder_clap"
		"HealthBarOffset" "175"
		"MovementSpeed" "325"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "5"
		"StatusHealth" "5400"
		"StatusHealthRegen" "5"
		"StatusMana" "900"
		"StatusManaRegen" "2"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "175"
		"AttackDamageMax" "185"
		"AttackRate" "1.25"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "150"
		"AttackAcquisitionRange" "600"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_storm_1" {
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"StatusHealth" "1000"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "25"
		"AttackDamageMax" "35"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_storm_2" {
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"StatusHealth" "1800"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "45"
		"AttackDamageMax" "55"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_storm_3" {
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"StatusHealth" "2375"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "70"
		"AttackDamageMax" "80"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_storm_4" {
		"UnitLabel" "brewmaster_storm"
		"BaseClass" "npc_dota_brewmaster_storm"
		"Model" "models/heroes/brewmaster/brewmaster_windspirit.vmdl"
		"ModelScale" ".98"
		"SoundSet" "Brewmaster_Storm"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_storm_dispel_magic"
		"Ability2" "brewmaster_storm_cyclone"
		"Ability3" "brewmaster_storm_wind_walk"
		"Ability4" "brewmaster_drunken_haze"
		"HealthBarOffset" "175"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "2"
		"StatusHealth" "2400"
		"StatusHealthRegen" "3"
		"StatusMana" "900"
		"StatusManaRegen" "1.5"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "75"
		"AttackDamageMax" "85"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.4"
		"AttackRange" "600"
		"AttackAcquisitionRange" "600"
		"ProjectileModel" "particles/units/heroes/hero_brewmaster/brewmaster_storm_attack.vpcf"
		"ProjectileSpeed" "1200"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_storm_5" {
		"UnitLabel" "brewmaster_storm"
		"BaseClass" "npc_dota_brewmaster_storm"
		"Model" "models/heroes/brewmaster/brewmaster_windspirit.vmdl"
		"ModelScale" "1.05"
		"SoundSet" "Brewmaster_Storm"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_storm_dispel_magic"
		"Ability2" "brewmaster_storm_cyclone"
		"Ability3" "brewmaster_storm_wind_walk"
		"Ability4" "brewmaster_drunken_haze"
		"HealthBarOffset" "175"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "2"
		"StatusHealth" "2800"
		"StatusHealthRegen" "4"
		"StatusMana" "900"
		"StatusManaRegen" "1.5"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "95"
		"AttackDamageMax" "105"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.4"
		"AttackRange" "600"
		"AttackAcquisitionRange" "600"
		"ProjectileModel" "particles/units/heroes/hero_brewmaster/brewmaster_storm_attack.vpcf"
		"ProjectileSpeed" "1200"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_storm_6" {
		"UnitLabel" "brewmaster_storm"
		"BaseClass" "npc_dota_brewmaster_storm"
		"Model" "models/heroes/brewmaster/brewmaster_windspirit.vmdl"
		"ModelScale" "1.1"
		"SoundSet" "Brewmaster_Storm"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_storm_dispel_magic"
		"Ability2" "brewmaster_storm_cyclone"
		"Ability3" "brewmaster_storm_wind_walk"
		"Ability4" "brewmaster_drunken_haze"
		"HealthBarOffset" "175"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "2"
		"StatusHealth" "3200"
		"StatusHealthRegen" "5"
		"StatusMana" "1050"
		"StatusManaRegen" "1.5"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "115"
		"AttackDamageMax" "125"
		"AttackRate" "1.5"
		"AttackAnimationPoint" "0.4"
		"AttackRange" "600"
		"AttackAcquisitionRange" "600"
		"ProjectileModel" "particles/units/heroes/hero_brewmaster/brewmaster_storm_attack.vpcf"
		"ProjectileSpeed" "1200"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_fire_1" {
		"StatusHealth" "1300"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "75"
		"AttackDamageMax" "85"
		"AttackRate" "1.35"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_fire_2" {
		"StatusHealth" "1300"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "125"
		"AttackDamageMax" "135"
		"AttackRate" "1.35"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_fire_3" {
		"StatusHealth" "1625"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "175"
		"AttackDamageMax" "185"
		"AttackRate" "1.35"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_fire_4" {
		"UnitLabel" "brewmaster_fire"
		"BaseClass" "npc_dota_brewmaster_fire"
		"Model" "models/heroes/brewmaster/brewmaster_firespirit.vmdl"
		"ModelScale" ".98"
		"SoundSet" "Brewmaster_Fire"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_fire_permanent_immolation"
		"Ability2" "brewmaster_drunken_brawler"
		"HealthBarOffset" "175"
		"MovementSpeed" "550"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "9"
		"StatusHealth" "1300"
		"StatusHealthRegen" "6"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "195"
		"AttackDamageMax" "205"
		"AttackRate" "1.35"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "150"
		"AttackAcquisitionRange" "600"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_fire_5" {
		"UnitLabel" "brewmaster_fire"
		"BaseClass" "npc_dota_brewmaster_fire"
		"Model" "models/heroes/brewmaster/brewmaster_firespirit.vmdl"
		"ModelScale" "1.05"
		"SoundSet" "Brewmaster_Fire"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_fire_permanent_immolation"
		"Ability2" "brewmaster_drunken_brawler"
		"HealthBarOffset" "175"
		"MovementSpeed" "550"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "12"
		"StatusHealth" "1300"
		"StatusHealthRegen" "8"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "235"
		"AttackDamageMax" "245"
		"AttackRate" "1.35"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "150"
		"AttackAcquisitionRange" "600"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_brewmaster_fire_6" {
		"UnitLabel" "brewmaster_fire"
		"BaseClass" "npc_dota_brewmaster_fire"
		"Model" "models/heroes/brewmaster/brewmaster_firespirit.vmdl"
		"ModelScale" "1.1"
		"SoundSet" "Brewmaster_Fire"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"Ability1" "brewmaster_fire_permanent_immolation"
		"Ability2" "brewmaster_drunken_brawler"
		"HealthBarOffset" "175"
		"MovementSpeed" "550"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "15"
		"StatusHealth" "1300"
		"StatusHealthRegen" "10"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "275"
		"AttackDamageMax" "285"
		"AttackRate" "1.35"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "150"
		"AttackAcquisitionRange" "600"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_unit_tombstone1" {
		"StatusHealth" "16"
		"Creature" {

		}

	}
	"npc_dota_unit_tombstone2" {
		"StatusHealth" "20"
		"Creature" {

		}

	}
	"npc_dota_unit_tombstone3" {
		"StatusHealth" "24"
		"Creature" {

		}

	}
	"npc_dota_unit_tombstone4" {
		"StatusHealth" "28"
		"Creature" {

		}

	}
	"npc_dota_visage_familiar1" {
		"Ability1" "imba_visage_summon_familiars_stone_form"
		"ArmorPhysical" "0"
		"StatusHealth" "500"
		"AttackDamageMin" "25"
		"AttackDamageMax" "25"
		"Creature" {

		}

	}
	"npc_dota_visage_familiar2" {
		"Ability1" "imba_visage_summon_familiars_stone_form"
		"ArmorPhysical" "1"
		"StatusHealth" "600"
		"AttackDamageMin" "50"
		"AttackDamageMax" "50"
		"Creature" {

		}

	}
	"npc_dota_visage_familiar3" {
		"Ability1" "imba_visage_summon_familiars_stone_form"
		"ArmorPhysical" "2"
		"StatusHealth" "700"
		"AttackDamageMin" "75"
		"AttackDamageMax" "75"
		"Creature" {

		}

	}
	"npc_dota_beastmaster_hawk_1" {
		"VisionDaytimeRange" "600"
		"VisionNighttimeRange" "600"
		"MovementSpeed" "300"
		"StatusHealth" "150"
		"Creature" {

		}

	}
	"npc_dota_beastmaster_hawk_2" {
		"VisionDaytimeRange" "700"
		"VisionNighttimeRange" "700"
		"MovementSpeed" "340"
		"StatusHealth" "200"
		"Creature" {

		}

	}
	"npc_dota_beastmaster_hawk_3" {
		"VisionDaytimeRange" "800"
		"VisionNighttimeRange" "800"
		"MovementSpeed" "380"
		"StatusHealth" "250"
		"Creature" {

		}

	}
	"npc_dota_beastmaster_hawk_4" {
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "900"
		"MovementSpeed" "420"
		"StatusHealth" "300"
		"Creature" {

		}

	}
	"npc_dota_beastmaster_boar_1" {
		"StatusHealth" "300"
		"AttackDamageMin" "16"
		"AttackDamageMax" "16"
		"Creature" {

		}

	}
	"npc_dota_beastmaster_boar_2" {
		"StatusHealth" "450"
		"AttackDamageMin" "32"
		"AttackDamageMax" "32"
		"Creature" {

		}

	}
	"npc_dota_beastmaster_boar_3" {
		"StatusHealth" "600"
		"AttackDamageMin" "48"
		"AttackDamageMax" "48"
		"Creature" {

		}

	}
	"npc_dota_beastmaster_boar_4" {
		"StatusHealth" "750"
		"AttackDamageMin" "64"
		"AttackDamageMax" "64"
		"Creature" {

		}

	}
	"npc_dota_rattletrap_cog" {
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"Creature" {

		}

	}
	"npc_dota_hero_sly_king" {
		"BaseClass" "npc_dota_hero_weaver"
		"Model" "models/heroes/slyli/model_weaver.vmdl"
		"ModelScale" "0.940000"
		"SoundSet" "Hero_Weaver"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"RingRadius" "70"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_weaver.vsndevts"
		"Ability1" "imba_sly_king_burrow_blast"
		"Ability2" "imba_sly_king_frost_gale"
		"Ability3" "imba_sly_king_hypothermic_wisdom"
		"Ability6" "imba_sly_king_winterbringer"
		"Ability10" "special_bonus_magic_resistance_12"
		"Ability11" "special_bonus_armor_6"
		"Ability12" "special_bonus_imba_unique_sly_king_1"
		"Ability13" "special_bonus_hp_regen_10"
		"Ability14" "special_bonus_imba_unique_sly_king_2"
		"Ability15" "special_bonus_attack_damage_90"
		"Ability16" "special_bonus_cooldown_reduction_15"
		"Ability17" "special_bonus_spell_lifesteal_15"
		"HealthBarOffset" "240"
		"MovementSpeed" "325"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.4"
		"ArmorPhysical" "3"
		"MagicalResistance" "25"
		"StatusHealth" "200"
		"StatusHealthRegen" "3.0"
		"StatusMana" "50"
		"StatusManaRegen" "1.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "30"
		"AttackDamageMax" "40"
		"AttackRate" "1.700"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.300"
		"AttackRange" "150"
		"AttackAcquisitionRange" "600"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength" "20"
		"AttributeStrengthGain" "2.4"
		"AttributeBaseAgility" "18"
		"AttributeAgilityGain" "1.9"
		"AttributeBaseIntelligence" "16"
		"AttributeIntelligenceGain" "3.3"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_elder_titan_ancestral_spirit" {
		"BaseClass" "npc_dota_elder_titan_ancestral_spirit"
		"Model" "models/heroes/elder_titan/ancestral_spirit.vmdl"
		"ModelScale" "1.0"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"Ability1" "imba_elder_titan_echo_stomp_spirit"
		"Ability2" "imba_elder_titan_return_spirit"
		"Ability3" "imba_elder_titan_natural_order"
		"MovementSpeed" "315"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.0"
		"AttackAnimationPoint" "0.0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_hero_scaldris" {
		"BaseClass" "npc_dota_hero_invoker"
		"Model" "models/heroes/invoker/invoker.vmdl"
		"ModelScale" "0.810000"
		"SoundSet" "Hero_Invoker"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"RingRadius" "70"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts"
		"Ability1" "imba_scaldris_heatwave"
		"Ability2" "imba_scaldris_scorch"
		"Ability3" "imba_scaldris_jet_blaze"
		"Ability5" "imba_scaldris_antipode"
		"Ability6" "imba_scaldris_living_flame"
		"Ability10" "special_bonus_magic_resistance_15"
		"Ability11" "special_bonus_movement_speed_30"
		"Ability12" "special_bonus_attack_damage_100"
		"Ability13" "special_bonus_mp_400"
		"Ability14" "special_bonus_cast_range_200"
		"Ability15" "special_bonus_spell_amplify_10"
		"Ability16" "special_bonus_cooldown_reduction_15"
		"Ability17" "special_bonus_spell_block_15"
		"HealthBarOffset" "240"
		"MovementSpeed" "305"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "5"
		"MagicalResistance" "25"
		"StatusHealth" "300"
		"StatusHealthRegen" "3.0"
		"StatusMana" "50"
		"StatusManaRegen" "1.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "19"
		"AttackDamageMax" "25"
		"AttackRate" "1.700"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.400"
		"AttackRange" "600"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" "particles/units/heroes/hero_invoker/invoker_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"AttributePrimary" "DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength" "20"
		"AttributeStrengthGain" "2.200000"
		"AttributeBaseAgility" "14"
		"AttributeAgilityGain" "1.900000"
		"AttributeBaseIntelligence" "20"
		"AttributeIntelligenceGain" "4.000000"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_hero_storegga" {
		"BaseClass" "npc_dota_hero_tiny"
		"Model" "models/creeps/ice_biome/storegga/storegga.vmdl"
		"ModelScale" "0.8"
		"SoundSet" "Hero_Tiny"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "800"
		"RingRadius" "70"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_tiny.vsndevts"
		"Ability1" "storegga_arm_slam"
		"Ability2" "storegga_grab"
		"Ability3" "storegga_grab_throw"
		"Ability6" "storegga_avalanche"
		"Ability10" "special_bonus_magic_resistance_15"
		"Ability11" "special_bonus_exp_boost_10"
		"Ability12" "special_bonus_attack_damage_40"
		"Ability13" "special_bonus_mp_300"
		"Ability14" "special_bonus_cast_range_150"
		"Ability15" "special_bonus_spell_amplify_10"
		"Ability16" "special_bonus_cooldown_reduction_15"
		"Ability17" "special_bonus_gold_income_50"
		"HealthBarOffset" "240"
		"MovementSpeed" "285"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "8"
		"MagicalResistance" "25"
		"StatusHealth" "200"
		"StatusHealthRegen" "3.0"
		"StatusMana" "50"
		"StatusManaRegen" "1.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "59"
		"AttackDamageMax" "75"
		"AttackRate" "1.700"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "1.000"
		"AttackRange" "150"
		"AttackAcquisitionRange" "800"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "26"
		"AttributeStrengthGain" "4.400000"
		"AttributeBaseAgility" "19"
		"AttributeAgilityGain" "2.900000"
		"AttributeBaseIntelligence" "16"
		"AttributeIntelligenceGain" "2.600000"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_mutation_spiderling_super_big" {
		"BaseClass" "npc_dota_broodmother_spiderling"
		"Model" "models/heroes/broodmother/spiderling.vmdl"
		"ModelScale" ".8"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "900"
		"HealthBarOffset" "200"
		"MovementSpeed" "400"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "8"
		"MagicalResistance" "25"
		"StatusHealth" "2000"
		"StatusHealthRegen" "8.0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "200"
		"AttackDamageMax" "200"
		"AttackRate" "1.35"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "200"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_mutation_spiderling_big" {
		"BaseClass" "npc_dota_broodmother_spiderling"
		"Model" "models/heroes/broodmother/spiderling.vmdl"
		"ModelScale" ".5"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "900"
		"HealthBarOffset" "170"
		"MovementSpeed" "375"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "6"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "4.0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "120"
		"AttackDamageMax" "120"
		"AttackRate" "1.35"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "150"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_mutation_spiderling" {
		"BaseClass" "npc_dota_broodmother_spiderling"
		"Model" "models/heroes/broodmother/spiderling.vmdl"
		"ModelScale" ".3"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "900"
		"HealthBarOffset" "140"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "3"
		"MagicalResistance" "0"
		"StatusHealth" "600"
		"StatusHealthRegen" "2.5"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "60"
		"AttackDamageMax" "60"
		"AttackRate" "1.35"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "100"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_mutation_spiderite" {
		"BaseClass" "npc_dota_broodmother_spiderling"
		"Model" "models/heroes/broodmother/spiderling.vmdl"
		"ModelScale" ".2"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "900"
		"HealthBarOffset" "140"
		"MovementSpeed" "325"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "200"
		"StatusHealthRegen" "1.0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "25"
		"AttackDamageMax" "25"
		"AttackRate" "1.35"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "100"
		"AttackAcquisitionRange" "1200"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_mutation_golem" {
		"UnitLabel" "mutation_golem"
		"BaseClass" "npc_dota_warlock_golem"
		"Model" "models/items/warlock/golem/ti_8_warlock_darkness_apostate_golem/ti_8_warlock_darkness_apostate_golem.vmdl"
		"ModelScale" "0.7"
		"SoundSet" "Hero_WarlockGolem"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "900"
		"VisionNighttimeRange" "900"
		"VoiceFile" "soundevents/voscripts/game_sounds_vo_warlock_golem.vsndevts"
		"HealthBarOffset" "240"
		"MovementSpeed" "320"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "25"
		"StatusHealth" "300"
		"StatusHealthRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.2"
		"AttackAnimationPoint" "0.26"
		"AttackRange" "160"
		"AttackAcquisitionRange" "600"
		"ProjectileModel" ""
		"ProjectileSpeed" "900"
		"ConsideredHero" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_kobold_overboss" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props_structures/midas_throne/kobold_underboss.vmdl"
		"Ability1" "dota_ability_throw_coin"
		"Ability2" "dota_ability_throw_coin_long"
		"Ability3" "dota_ability_celebrate"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"StatusHealth" "5000"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"Creature" {

		}

	}
	"npc_dota_kobold_radiantboss" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props_structures/midas_throne/kobold_radiantboss.vmdl"
		"Ability1" "dota_ability_throw_coin"
		"Ability2" "dota_ability_throw_coin_long"
		"Ability3" "dota_ability_celebrate"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"StatusHealth" "5000"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"Creature" {

		}

	}
	"npc_dota_kobold_underboss" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props_structures/midas_throne/kobold_underboss.vmdl"
		"Ability1" "dota_ability_throw_coin"
		"Ability2" "dota_ability_throw_coin_long"
		"Ability3" "dota_ability_celebrate"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"StatusHealth" "5000"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"Creature" {

		}

	}
	"npc_vision_revealer" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/development/invisiblebox.vmdl"
		"VisionDaytimeRange" "600"
		"VisionNighttimeRange" "600"
		"MinimapIcon" "minimap_treasure_chest"
		"Ability1" "dota_ability_vision_revealer"
		"Ability2" "dota_ability_reveal_invis"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"StatusHealth" "5000"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"Creature" {

		}

	}
	"npc_dota_creature_basic_zombie" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/undying/undying_minion.vmdl"
		"ModelScale" "1"
		"SoundSet" "Undying_Zombie"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1000"
		"VisionNighttimeRange" "1000"
		"RingRadius" "70"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_undying.vsndevts"
		"HealthBarOffset" "160"
		"MovementSpeed" "120"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "3"
		"MagicalResistance" "33"
		"StatusHealth" "250"
		"StatusHealthRegen" "0.25"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "24"
		"AttackDamageMax" "40"
		"AttackRate" "1.6"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "128"
		"AttackAcquisitionRange" "400"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_SOFT"
		"Creature" {

		}

	}
	"npc_dota_creature_berserk_zombie" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/heroes/undying/undying_minion_torso.vmdl"
		"ModelScale" "1"
		"SoundSet" "Undying_Zombie"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1000"
		"VisionNighttimeRange" "1000"
		"RingRadius" "70"
		"GameSoundsFile" "soundevents/game_sounds_heroes/game_sounds_undying.vsndevts"
		"Ability1" "zombie_berserk"
		"HealthBarOffset" "160"
		"MovementSpeed" "120"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "4"
		"MagicalResistance" "33"
		"StatusHealth" "250"
		"StatusHealthRegen" "5.0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "24"
		"AttackDamageMax" "30"
		"AttackRate" "1.6"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "128"
		"AttackAcquisitionRange" "400"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_SOFT"
		"Creature" {

		}

	}
	"npc_dota_treasure_courier" {
		"BaseClass" "npc_dota_base"
		"Model" "models/courier/lockjaw/lockjaw_flying.vmdl"
		"ModelScale" "1"
		"SoundSet" ""
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1000"
		"VisionNighttimeRange" "1000"
		"RingRadius" "70"
		"GameSoundsFile" ""
		"Ability1" "dota_ability_treasure_courier"
		"HealthBarOffset" "160"
		"MovementSpeed" "350"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "3"
		"MagicalResistance" "33"
		"StatusHealth" "5000"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.6"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_SOFT"
		"Creature" {

		}

	}
	"npc_dota_fire_trap_ward" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props/traps/barking_dog/barking_dog.vmdl"
		"Ability1" "breathe_fire"
		"Ability2" "trap_unselectable"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0.25"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"Creature" {

		}

	}
	"npc_dota_venom_trap_ward" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props/traps/hooded_fang/hooded_fang.vmdl"
		"Ability1" "breathe_poison"
		"Ability2" "trap_unselectable"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0.25"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"Creature" {

		}

	}
	"npc_dota_spike_trap_ward" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props/traps/spiketrap/spiketrap.vmdl"
		"Ability1" "spike_trap"
		"Ability2" "trap_unselectable"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0.25"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"Creature" {

		}

	}
	"npc_dota_pendulum_trap_ward" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props/traps/pendulum/pendulum.vmdl"
		"Ability1" "pendulum_trap"
		"Ability2" "trap_unselectable"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "6"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"Creature" {

		}

	}
	"npc_dota_goodguys_fort" {
		"BaseClass" "npc_dota_fort"
		"Model" "models/props_structures/radiant_ancient001.vmdl"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_BUILDING"
		"VisionDaytimeRange" "2600"
		"VisionNighttimeRange" "2600"
		"RingRadius" "350"
		"MinimapIcon" "minimap_ancient"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "400"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "42"
		"MagicalResistance" "0"
		"StatusHealth" "8000"
		"StatusHealthRegen" "12.0"
		"StatusMana" "0"
		"StatusManaRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_dota_badguys_fort" {
		"BaseClass" "npc_dota_fort"
		"Model" "models/props_structures/dire_ancient_base001.vmdl"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_BUILDING"
		"VisionDaytimeRange" "2600"
		"VisionNighttimeRange" "2600"
		"RingRadius" "350"
		"MinimapIcon" "minimap_ancient"
		"Ability1" "backdoor_protection_in_base"
		"HealthBarOffset" "400"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "42"
		"MagicalResistance" "0"
		"StatusHealth" "8000"
		"StatusHealthRegen" "12.0"
		"StatusMana" "0"
		"StatusManaRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_treasure_chest" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props_generic/chest_treasure_02.vmdl"
		"ModelScale" "1.5"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "1"
		"VisionNighttimeRange" "1"
		"RingRadius" "45"
		"HealthBarOffset" "110"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "20"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "3"
		"StatusMana" "500"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_treasure_chest_anim" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props_generic/chest_treasure_02_open.vmdl"
		"ModelScale" "1.5"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "1"
		"VisionNighttimeRange" "1"
		"RingRadius" "45"
		"HealthBarOffset" "110"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "20"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "3"
		"StatusMana" "500"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_special_treasure_chest" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props_generic/chest_treasure_02.vmdl"
		"ModelScale" "1.5"
		"skin" "1"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "1"
		"VisionNighttimeRange" "1"
		"RingRadius" "45"
		"HealthBarOffset" "110"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "20"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "3"
		"StatusMana" "500"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_special_treasure_chest_anim" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/props_generic/chest_treasure_02_open.vmdl"
		"ModelScale" "1.5"
		"skin" "1"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "1"
		"VisionNighttimeRange" "1"
		"RingRadius" "45"
		"HealthBarOffset" "110"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "20"
		"MagicalResistance" "0"
		"StatusHealth" "1000"
		"StatusHealthRegen" "3"
		"StatusMana" "500"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "0"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_creature_techies_land_mine" {
		"BaseClass" "npc_dota_techies_mines"
		"Model" "models/heroes/techies/fx_techiesfx_mine.vmdl"
		"ModelScale" "1.3"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "64"
		"VisionNighttimeRange" "64"
		"Ability1" "ability_unselectable"
		"HealthBarOffset" "140"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0"
		"ArmorPhysical" "0"
		"StatusHealth" "1"
		"StatusHealthRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.0"
		"AttackAnimationPoint" "0.0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_good_candy_pumpkin" {
		"BaseClass" "npc_dota_tower"
		"Model" "models/props_gameplay/pumpkin_bucket.vmdl"
		"ModelScale" "1"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"RingRadius" "120"
		"MinimapIcon" "minimap_candybucket"
		"Ability1" "diretide_pumpkin_immune"
		"HealthBarOffset" "150"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "1.0"
		"StatusHealth" "150"
		"StatusHealthRegen" "0.0"
		"StatusMana" "0.0"
		"StatusManaRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_dota_bad_candy_pumpkin" {
		"BaseClass" "npc_dota_tower"
		"Model" "models/props_gameplay/pumpkin_bucket.vmdl"
		"ModelScale" "1"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "400"
		"VisionNighttimeRange" "400"
		"RingRadius" "120"
		"MinimapIcon" "minimap_candybucket"
		"Ability1" "diretide_pumpkin_immune"
		"HealthBarOffset" "150"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "1.0"
		"StatusHealth" "150"
		"StatusHealthRegen" "0.0"
		"StatusMana" "0.0"
		"StatusManaRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_SIEGE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_STRUCTURE"
		"Creature" {

		}

	}
	"npc_diretide_roshan" {
		"UnitLabel" "npc_diretide_roshan"
		"BaseClass" "npc_dota_creature"
		"Model" "models/rosh/roshan_halloween.vmdl"
		"ModelScale" "1.1"
		"SoundSet" "Roshan"
		"BoundsHullName" "DOTA_HULL_SIZE_HERO"
		"VisionDaytimeRange" "1400"
		"VisionNighttimeRange" "1400"
		"RingRadius" "110"
		"MinimapIcon" "minimap_roshancamp"
		"GameSoundsFile" "soundevents/diretide_soundevents.vsndevts"
		"Ability1" "imba_roshan_diretide_apocalypse"
		"Ability2" "roshan_deafening_blast"
		"Ability3" "tiny_toss"
		"Ability4" "creature_fire_breath"
		"Ability6" "roshan_spell_block"
		"HealthBarOffset" "400"
		"MovementSpeed" "450"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "15000"
		"StatusHealthRegen" "50.0"
		"StatusMana" "0"
		"StatusManaRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "600"
		"AttackDamageMax" "600"
		"AttackRate" "1.25"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.2"
		"AttackRange" "200"
		"AttackAcquisitionRange" "600"
		"ProjectileModel" "ranged_goodguy"
		"ProjectileSpeed" "1000"
		"HasInventory" "1"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_HERO"
		"Creature" {

		}

	}
	"npc_dota_diretide_easter_egg" {
		"BaseClass" "npc_dota_ward_base"
		"Model" "models/props_gameplay/pumpkin_bucket.vmdl"
		"ModelScale" "1.0"
		"SoundSet" "Creep_Good_Melee"
		"BoundsHullName" "DOTA_HULL_SIZE_REGULAR"
		"VisionDaytimeRange" "1000"
		"VisionNighttimeRange" "800"
		"RingRadius" "45"
		"HealthBarOffset" "150"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementTurnRate" "0"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "100"
		"StatusHealthRegen" "0.0"
		"StatusMana" "0"
		"StatusManaRegen" "3"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.467"
		"AttackRange" "100"
		"AttackAcquisitionRange" "600"
		"ProjectileModel" ""
		"ProjectileSpeed" ""
		"AttributePrimary" "DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength" "0"
		"AttributeStrengthGain" "0"
		"AttributeBaseAgility" "0"
		"AttributeAgilityGain" "0"
		"AttributeBaseIntelligence" "0"
		"AttributeIntelligenceGain" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"wearable_dummy" {
		"BaseClass" "npc_dota_base_additive"
		"Creature" {

		}

	}
	"npc_dota_neutral_caster" {
		"BaseClass" "npc_dota_creature"
		"Model" "models/development/invisiblebox.vmdl"
		"Ability1" "dota_ability_dummy"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_FLY"
		"StatusHealth" "5000"
		"StatusMana" "5000"
		"StatusManaRegen" "250"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"Creature" {

		}

	}
	"npc_dota_roshan" {
		"ArmorPhysical" "25"
		"MagicalResistance" "55"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "100"
		"AttackDamageMax" "100"
		"AttackRate" "1.4"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.6"
		"Creature" {

		}

	}
	"npc_dota_clinkz_skeleton_archer" {
		"BaseClass" "npc_dota_clinkz_skeleton_archer"
		"Model" "models/heroes/clinkz/clinkz_archer.vmdl"
		"ModelScale" "1.1"
		"SoundSet" "Hero_Clinkz"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "800"
		"VisionNighttimeRange" "800"
		"Ability1" "imba_clinkz_searing_arrows"
		"HealthBarOffset" "200"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "0.5"
		"ArmorPhysical" "0"
		"MagicalResistance" "0"
		"StatusHealth" "8"
		"StatusHealthRegen" "0"
		"StatusMana" "100"
		"StatusManaRegen" "0"
		"AttackCapabilities" "DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin" "5"
		"AttackDamageMax" "5"
		"AttackRate" "1.7"
		"AttackDamageType" "DAMAGE_TYPE_ArmorPhysical"
		"AttackAnimationPoint" "0.3"
		"AttackRange" "500"
		"AttackAcquisitionRange" "900"
		"ProjectileModel" "particles/units/heroes/hero_clinkz/clinkz_base_attack.vpcf"
		"ProjectileSpeed" "900"
		"HasInventory" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_wraith_king_skeleton_warrior" {
		"StatusHealth" "175"
		"AttackDamageMin" "35"
		"AttackDamageMax" "40"
		"Creature" {

		}

	}
	"npc_dota_life_stealer_banquet" {
		"BaseClass" "npc_dota_base_additive"
		"Model" "models/props_gameplay/cheese_04.vmdl"
		"ModelScale" "1.5"
		"SoundSet" "0"
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "0"
		"VisionNighttimeRange" "0"
		"MovementSpeed" "0"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"MovementTurnRate" "1.0"
		"ArmorPhysical" "0"
		"StatusHealth" "400"
		"StatusHealthRegen" "0.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_NO_ATTACK"
		"AttackDamageMin" "0"
		"AttackDamageMax" "0"
		"AttackRate" "1.0"
		"AttackAnimationPoint" "0.0"
		"AttackRange" "0"
		"AttackAcquisitionRange" "0"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_BASIC"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_aether_spec_ward" {
		"BaseClass" "npc_dota_ward_base"
		"Model" "models/items/wards/eyeofforesight/eyeofforesight.vmdl"
		"ModelScale" "1"
		"SoundSet" ""
		"BoundsHullName" "DOTA_HULL_SIZE_SMALL"
		"VisionDaytimeRange" "1000"
		"VisionNighttimeRange" "1000"
		"MinimapIcon" "minimap_ward_obs"
		"HealthBarOffset" "140"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_NONE"
		"StatusHealth" "16"
		"StatusHealthRegen" "0"
		"StatusMana" "0"
		"StatusManaRegen" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_PIERCE"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}
	"npc_dota_templar_assassin_psionic_trap" {
		"Ability1" "imba_templar_assassin_self_trap"
		"Creature" {

		}

	}
	"npc_dota_slark_spawn" {
		"BaseClass" "npc_dota_creep"
		"Model" "models/heroes/slark/slark.vmdl"
		"ModelScale" "0.6"
		"SoundSet" "Hero_Slark"
		"VisionDaytimeRange" "1800"
		"VisionNighttimeRange" "1800"
		"RingRadius" "40"
		"Ability1" "imba_slark_dark_pact"
		"Ability2" "imba_slark_pounce"
		"HealthBarOffset" "150"
		"MovementSpeed" "300"
		"MovementCapabilities" "DOTA_UNIT_CAP_MOVE_GROUND"
		"ArmorPhysical" "0"
		"StatusHealth" "800"
		"StatusHealthRegen" "1.75"
		"StatusMana" "300"
		"StatusManaRegen" "1.0"
		"AttackCapabilities" "DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin" "32"
		"AttackDamageMax" "40"
		"AttackRate" "1.7"
		"AttackAnimationPoint" "0.5"
		"AttackRange" "150"
		"AttackAcquisitionRange" "600"
		"ProjectileModel" ""
		"ProjectileSpeed" "0"
		"CombatClassAttack" "DOTA_COMBAT_CLASS_ATTACK_HERO"
		"CombatClassDefend" "DOTA_COMBAT_CLASS_DEFEND_BASIC"
		"Creature" {

		}

	}

}
