
declare namespace lang_config { 
 interface OBJ_0_1 {
"lang_config" :OBJ_1_1 ,
}
 interface OBJ_1_1 {
"population" :OBJ_2_1 ,
"gold" :OBJ_2_1 ,
"wood" :OBJ_2_1 ,
"turn" :OBJ_2_1 ,
"soulcrystal" :OBJ_2_1 ,
"TopBarRound" :OBJ_2_1 ,
"TopBarDifficulty" :OBJ_2_1 ,
"round_start" :OBJ_2_1 ,
"round_battle" :OBJ_2_1 ,
"round_prize" :OBJ_2_1 ,
"round_waiting_next" :OBJ_2_1 ,
"round_end" :OBJ_2_1 ,
"MenuButton_setting" :OBJ_2_1 ,
"MenuButton_mail" :OBJ_2_1 ,
"MenuButton_store" :OBJ_2_1 ,
"MenuButton_battlepass" :OBJ_2_1 ,
"MenuButton_draw" :OBJ_2_1 ,
"MenuButton_handbook" :OBJ_2_1 ,
"MenuButton_rank" :OBJ_2_1 ,
"MenuButton_activity" :OBJ_2_1 ,
"MenuButton_record" :OBJ_2_1 ,
"MenuButton_storage" :OBJ_2_1 ,
"LevelChallenge" :OBJ_2_1 ,
"tech" :OBJ_2_1 ,
"bagshop" :OBJ_2_1 ,
"HUD_Shop_Home" :OBJ_2_1 ,
"HUD_Shop_Props" :OBJ_2_1 ,
"HUD_Shop_Resource" :OBJ_2_1 ,
"HUD_Shop_Star" :OBJ_2_1 ,
"HUD_Shop_Chest" :OBJ_2_1 ,
"HUD_Shop_HotSale" :OBJ_2_1 ,
"HUD_Shop_DailyLimitedSale" :OBJ_2_1 ,
"HUD_Shop_LimitedSale" :OBJ_2_1 ,
"LimitedSaleTime" :OBJ_2_1 ,
"Free" :OBJ_2_1 ,
"Shop_Buy_With_Money" :OBJ_2_1 ,
"Error_Star_Not_Enough" :OBJ_2_1 ,
"DialogBox_Buy_Success" :OBJ_2_1 ,
"DialogBox_Buy_Fail" :OBJ_2_1 ,
"DialogBox_Get_Success" :OBJ_2_1 ,
"DialogBox_Get_Fail" :OBJ_2_1 ,
"Payment_PleaseWait" :OBJ_2_1 ,
"Payment_WebPageOpened" :OBJ_2_1 ,
"Payment_Create_Fail" :OBJ_2_1 ,
"Shop_Goods_1" :OBJ_2_1 ,
"Shop_Goods_line_first" :OBJ_2_1 ,
"Shop_Goods_line" :OBJ_2_1 ,
"Shop_Goods_limit_1" :OBJ_2_1 ,
"Shop_Goods_limit_2" :OBJ_2_1 ,
"Shop_Goods_limit_3" :OBJ_2_1 ,
"CDK" :OBJ_2_1 ,
"CDKResult" :OBJ_2_1 ,
"ExchangeProductResult" :OBJ_2_1 ,
"combination_rule" :OBJ_2_1 ,
[k:string] : OBJ_2_1 }
 interface OBJ_2_1 {
"Des" :string ,
[k:string] : string }
}