// generate with PIPIXIA's kv generator 

"custom_sounds" {
	"animation_aegis" {
		"soundIndex" "animation_aegis"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/aegis_expire.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.932766"

	}
	"animation_cookie" {
		"soundIndex" "animation_cookie"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/snapfire/cookie_target.vsnd"
		"volume" "0.600000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.20102"

	}
	"animation_levelup" {
		"soundIndex" "animation_levelup"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/menu/trophy_levelup.vsnd"
		"volume" "0.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.798503"

	}
	"animation_portal" {
		"soundIndex" "animation_portal"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/void_spirit/dissimilate_portal01.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.720136"

	}
	"animation_snowman" {
		"soundIndex" "animation_snowman"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/snowman_spawn.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.52"

	}
	"animation_tk_boots" {
		"soundIndex" "animation_tk_boots"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/phase_boots_activate.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.990522"

	}
	"animation_torrent" {
		"soundIndex" "animation_torrent"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/kunkka/ability_geyser.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.010794"

	}
	"animation_tree" {
		"soundIndex" "animation_tree"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/furion/treant_spawn01.vsnd
sounds/weapons/hero/furion/treant_spawn02.vsnd
sounds/weapons/hero/furion/treant_spawn03.vsnd
sounds/weapons/hero/furion/treant_spawn04.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.915419"

	}
	"animation_windrun" {
		"soundIndex" "animation_windrun"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/windrunner/windrun.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.000567"

	}
	"bkb_dota1" {
		"soundIndex" "bkb_dota1"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/bkb_dota1.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.198503"

	}
	"black_gear_transfer" {
		"soundIndex" "black_gear_transfer"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/tinker/rearm.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.416735"

	}
	"card_flip" {
		"soundIndex" "card_flip"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/npe_badge.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.2"

	}
	"courier_t102_chat_english" {
		"soundIndex" "courier_t102_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t102/h007_showup_02_eng.vsnd
sounds/t102/h007_showup_03_eng.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.280542"

	}
	"courier_t102_chat_schinese" {
		"soundIndex" "courier_t102_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t102/h007_showup_03.vsnd
sounds/t102/h007_showup_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.766349"

	}
	"courier_t102_win_english" {
		"soundIndex" "courier_t102_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t102/h007_showup_01_eng.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.5"

	}
	"courier_t102_win_schinese" {
		"soundIndex" "courier_t102_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t401/p032_win_03.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.775771"

	}
	"courier_t103_chat_english" {
		"soundIndex" "courier_t103_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/physics/movement/hero/crystal_maiden/idle_alt_shake.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.332812"

	}
	"courier_t103_chat_schinese" {
		"soundIndex" "courier_t103_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/physics/movement/hero/crystal_maiden/idle_alt_shake.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.332812"

	}
	"courier_t103_win_english" {
		"soundIndex" "courier_t103_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/physics/movement/hero/crystal_maiden/pant01.vsnd
sounds/physics/movement/hero/crystal_maiden/idle_alt_bark.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.615238"

	}
	"courier_t103_win_schinese" {
		"soundIndex" "courier_t103_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/physics/movement/hero/crystal_maiden/pant01.vsnd
sounds/physics/movement/hero/crystal_maiden/idle_alt_bark.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.615238"

	}
	"courier_t105_chat_english" {
		"soundIndex" "courier_t105_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t105/p059_win_02.vsnd
sounds/t105/p059_showup_02.vsnd
sounds/t105/p059_win_03.vsnd
sounds/t105/p059_win_04.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.803875"

	}
	"courier_t105_chat_schinese" {
		"soundIndex" "courier_t105_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t105/p059_win_02.vsnd
sounds/t105/p059_showup_02.vsnd
sounds/t105/p059_win_03.vsnd
sounds/t105/p059_win_04.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.803875"

	}
	"courier_t105_win_english" {
		"soundIndex" "courier_t105_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t105/p059_showup_01.vsnd
sounds/t105/p059_win_01.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.430396"

	}
	"courier_t105_win_schinese" {
		"soundIndex" "courier_t105_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t105/p059_showup_01.vsnd
sounds/t105/p059_win_01.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.430396"

	}
	"courier_t201_chat_english" {
		"soundIndex" "courier_t201_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t201/h034_showup_01_eng.vsnd
sounds/t201/h034_showup_02_eng.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.5"

	}
	"courier_t201_chat_schinese" {
		"soundIndex" "courier_t201_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t201/h034_showup_01.vsnd
sounds/t201/h034_showup_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.450249"

	}
	"courier_t201_win_english" {
		"soundIndex" "courier_t201_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t201/h034_showup_03_eng.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.1875"

	}
	"courier_t201_win_schinese" {
		"soundIndex" "courier_t201_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t201/h034_showup_03.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.146122"

	}
	"courier_t202_chat_english" {
		"soundIndex" "courier_t202_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t202/h002_showup_01_eng.vsnd
sounds/t202/h002_showup_02_eng.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.358021"

	}
	"courier_t202_chat_schinese" {
		"soundIndex" "courier_t202_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t202/h002_showup_01.vsnd
sounds/t202/h002_showup_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.901333"

	}
	"courier_t202_win_english" {
		"soundIndex" "courier_t202_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t202/h002_showup_02_eng.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.358021"

	}
	"courier_t202_win_schinese" {
		"soundIndex" "courier_t202_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t202/h002_showup_03.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.464"

	}
	"courier_t203_chat_english" {
		"soundIndex" "courier_t203_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t203/p015_showup_01_eng.vsnd
sounds/t203/p015_showup_02_eng.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.983167"

	}
	"courier_t203_chat_schinese" {
		"soundIndex" "courier_t203_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t203/p015_showup_02.vsnd
sounds/t203/p015_win_01.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.152125"

	}
	"courier_t203_win_english" {
		"soundIndex" "courier_t203_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t203/p015_win_01_eng.vsnd
sounds/t203/p015_win_02_eng.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.638854"

	}
	"courier_t203_win_schinese" {
		"soundIndex" "courier_t203_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t203/p015_win_01.vsnd
sounds/t203/p015_win_02.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.152125"

	}
	"courier_t204_chat_english" {
		"soundIndex" "courier_t204_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvo_la_ability_forgespirit_04.vsnd
sounds/vo/invoker/kidvo_la_ability_forgespirit_03.vsnd
sounds/vo/invoker/kidvo_la_ability_forgespirit_01.vsnd
sounds/vo/invoker/kidvo_la_ability_forgespirit_06_02.vsnd
sounds/vo/invoker/kidvo_la_ability_forgespirit_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.580998"

	}
	"courier_t204_chat_schinese" {
		"soundIndex" "courier_t204_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvo_la_ability_forgespirit_04.vsnd
sounds/vo/invoker/kidvo_la_ability_forgespirit_03.vsnd
sounds/vo/invoker/kidvo_la_ability_forgespirit_01.vsnd
sounds/vo/invoker/kidvo_la_ability_forgespirit_06_02.vsnd
sounds/vo/invoker/kidvo_la_ability_forgespirit_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.580998"

	}
	"courier_t204_win_english" {
		"soundIndex" "courier_t204_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvo_la_ability_forgespirit_05.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.187528"

	}
	"courier_t204_win_schinese" {
		"soundIndex" "courier_t204_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvo_la_ability_forgespirit_05.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.187528"

	}
	"courier_t301_chat_english" {
		"soundIndex" "courier_t301_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t301/h036_showup_01_eng.vsnd
sounds/t301/h036_showup_02_eng.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.695812"

	}
	"courier_t301_chat_schinese" {
		"soundIndex" "courier_t301_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t301/h036_showup_01.vsnd
sounds/t301/h036_showup_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "8.282676"

	}
	"courier_t301_win_english" {
		"soundIndex" "courier_t301_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t301/h036_showup_03_eng.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.721125"

	}
	"courier_t301_win_schinese" {
		"soundIndex" "courier_t301_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t301/h036_showup_03.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6"

	}
	"courier_t302_chat_english" {
		"soundIndex" "courier_t302_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t302/h018_showup_01_eng.vsnd
sounds/t302/h018_showup_02_eng.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.75"

	}
	"courier_t302_chat_schinese" {
		"soundIndex" "courier_t302_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t302/h018_showup_01.vsnd
sounds/t302/h018_showup_02.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.717664"

	}
	"courier_t302_win_english" {
		"soundIndex" "courier_t302_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t302/h018_showup_03_eng.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.538646"

	}
	"courier_t302_win_schinese" {
		"soundIndex" "courier_t302_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t302/h018_showup_03.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.937188"

	}
	"courier_t303_chat_english" {
		"soundIndex" "courier_t303_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t303/h058_showup_01_eng.vsnd
sounds/t303/h058_showup_02_eng.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.211896"

	}
	"courier_t303_chat_schinese" {
		"soundIndex" "courier_t303_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t303/h058_showup_03.vsnd
sounds/t303/h058_showup_01.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.768979"

	}
	"courier_t303_win_english" {
		"soundIndex" "courier_t303_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t303/h058_showup_03_eng.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.831646"

	}
	"courier_t303_win_schinese" {
		"soundIndex" "courier_t303_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t303/h058_showup_02.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.797917"

	}
	"courier_t304_chat_english" {
		"soundIndex" "courier_t304_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t304/h030_showup_01_eng.vsnd
sounds/t304/h030_showup_02_eng.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.676771"

	}
	"courier_t304_chat_schinese" {
		"soundIndex" "courier_t304_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t304/h030_showup_03.vsnd
sounds/t304/h030_showup_01.vsnd"
		"volume" "2.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.388"

	}
	"courier_t304_win_english" {
		"soundIndex" "courier_t304_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t304/h030_showup_03_eng.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.634854"

	}
	"courier_t304_win_schinese" {
		"soundIndex" "courier_t304_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t304/h030_showup_02.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.585"

	}
	"courier_t305_chat_english" {
		"soundIndex" "courier_t305_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t305/p066_showup_01_eng.vsnd
sounds/t305/p066_showup_02_eng.vsnd
sounds/t305/p066_win_02_eng.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.310204"

	}
	"courier_t305_chat_schinese" {
		"soundIndex" "courier_t305_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t305/p066_showup_01.vsnd
sounds/t305/p066_showup_02.vsnd
sounds/t305/p066_win_02.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.5"

	}
	"courier_t305_win_english" {
		"soundIndex" "courier_t305_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t305/p066_win_01_eng.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.787755"

	}
	"courier_t305_win_schinese" {
		"soundIndex" "courier_t305_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t305/p066_win_01.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.923792"

	}
	"courier_t401_chat_english" {
		"soundIndex" "courier_t401_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t401/p032_showup_01_eng.vsnd
sounds/t401/p032_showup_02_eng.vsnd
sounds/t401/p032_win_01_eng.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.154646"

	}
	"courier_t401_chat_schinese" {
		"soundIndex" "courier_t401_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t401/p032_showup_01.vsnd
sounds/t401/p032_showup_02.vsnd
sounds/t401/p032_win_01.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.532542"

	}
	"courier_t401_win_english" {
		"soundIndex" "courier_t401_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t401/p032_win_03_eng.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.914688"

	}
	"courier_t401_win_schinese" {
		"soundIndex" "courier_t401_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/t401/p032_win_03.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.775771"

	}
	"courier_t402_chat_english" {
		"soundIndex" "courier_t402_chat_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/physics/footsteps/creeps/neutral/greevil/hum01.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum02.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum03.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum04.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum05.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum06.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum07.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum08.vsnd"
		"volume" "4.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.662993"

	}
	"courier_t402_chat_schinese" {
		"soundIndex" "courier_t402_chat_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/physics/footsteps/creeps/neutral/greevil/hum01.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum02.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum03.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum04.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum05.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum06.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum07.vsnd
sounds/physics/footsteps/creeps/neutral/greevil/hum08.vsnd"
		"volume" "4.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.662993"

	}
	"courier_t402_win_english" {
		"soundIndex" "courier_t402_win_english"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/greevil_laugh01.vsnd
sounds/misc/soundboard/greevil_laugh02.vsnd
sounds/misc/soundboard/greevil_laugh03.vsnd
sounds/misc/soundboard/greevil_laugh04.vsnd
sounds/misc/soundboard/greevil_laugh05.vsnd
sounds/misc/soundboard/greevil_laugh06.vsnd
sounds/misc/soundboard/greevil_laugh07.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.270522"

	}
	"courier_t402_win_schinese" {
		"soundIndex" "courier_t402_win_schinese"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/greevil_laugh01.vsnd
sounds/misc/soundboard/greevil_laugh02.vsnd
sounds/misc/soundboard/greevil_laugh03.vsnd
sounds/misc/soundboard/greevil_laugh04.vsnd
sounds/misc/soundboard/greevil_laugh05.vsnd
sounds/misc/soundboard/greevil_laugh06.vsnd
sounds/misc/soundboard/greevil_laugh07.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.270522"

	}
	"courier_transfer_chess" {
		"soundIndex" "courier_transfer_chess"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/economy/plink_goal_tier7.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.117528"

	}
	"diretide_begin" {
		"soundIndex" "diretide_begin"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ambient/diretide/diretide_begins_radiant.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "9.403583"

	}
	"diretide_countdown" {
		"soundIndex" "diretide_countdown"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/addons/conquest/capture_point_timer_hallow.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.248005"

	}
	"diretide_darkwillow" {
		"soundIndex" "diretide_darkwillow"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dark_willow/sylph_spawn_02.vsnd
sounds/vo/dark_willow/sylph_wheel_all_05.vsnd
sounds/vo/dark_willow/sylph_spawn_15.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.355102"

	}
	"diretide_hit" {
		"soundIndex" "diretide_hit"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/ti9_monkey_impact.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.383129"

	}
	"diretide_sad" {
		"soundIndex" "diretide_sad"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/sad_bone.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.217959"

	}
	"diretide_stinger" {
		"soundIndex" "diretide_stinger"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/addons/conquest/stinger_hulk_hallow.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.08585"

	}
	"diretide_welcome" {
		"soundIndex" "diretide_welcome"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/announcer_dlc_monkey_king/mk_ann_welcome_01.vsnd
sounds/vo/announcer_dlc_monkey_king/mk_ann_unpause_01.vsnd
sounds/vo/announcer_dlc_monkey_king/mk_ann_battle_begins_01.vsnd
sounds/vo/announcer_dlc_monkey_king/mk_ann_battle_begins_04.vsnd
sounds/vo/announcer_dlc_monkey_king/mk_ann_ancient_attack_follow_up_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.056"

	}
	"egg_break" {
		"soundIndex" "egg_break"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/inventory/inv_egg_hatch.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.644989"

	}
	"et_earth_splitter_end" {
		"soundIndex" "et_earth_splitter_end"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/elder_titan/earth_split_destroy01.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.193742"

	}
	"ex_machina_get" {
		"soundIndex" "ex_machina_get"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/addons/conquest/spike_trap.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.700295"

	}
	"ex_machina_open" {
		"soundIndex" "ex_machina_open"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/challenge_failure.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.363288"

	}
	"greevil_stinger" {
		"soundIndex" "greevil_stinger"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/music/valve_ti6/music/battle_01_end.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "13.662041"

	}
	"hero_aw_devided_1" {
		"soundIndex" "hero_aw_devided_1"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/arc_warden/arcwar_tempest_double_01.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.377143"

	}
	"hero_aw_devided_2" {
		"soundIndex" "hero_aw_devided_2"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/arc_warden/arcwar_tempest_double_02.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.395918"

	}
	"hero_aw_merge" {
		"soundIndex" "hero_aw_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/arc_warden/arcwar_levelup_03.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.310204"

	}
	"hero_aw_spawn" {
		"soundIndex" "hero_aw_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/arc_warden/arcwar_spawn_02.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.026939"

	}
	"hero_aw_thanks" {
		"soundIndex" "hero_aw_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/arc_warden/arcwar_thanks_01.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.115918"

	}
	"hero_aw_win" {
		"soundIndex" "hero_aw_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/arc_warden/arcwar_win_05.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.91102"

	}
	"hero_axe_spawn" {
		"soundIndex" "hero_axe_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/axe/jung_axe_spawn_12.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.962903"

	}
	"hero_br_merge" {
		"soundIndex" "hero_br_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/broodmother/broo_spawn_04.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.649796"

	}
	"hero_br_spawn" {
		"soundIndex" "hero_br_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/broodmother/broo_spawn_05.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.246531"

	}
	"hero_br_win" {
		"soundIndex" "hero_br_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/broodmother/broo_win_03.vsnd
sounds/vo/broodmother/broo_rare_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.343673"

	}
	"hero_brew_fish" {
		"soundIndex" "hero_brew_fish"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/brewmaster/brew_respawn_01.vsnd
sounds/vo/brewmaster/brew_firstblood_04.vsnd
sounds/vo/brewmaster/brew_kill_12.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.638367"

	}
	"hero_brew_merge" {
		"soundIndex" "hero_brew_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/brewmaster/brew_respawn_11.vsnd
sounds/vo/brewmaster/brew_respawn_10.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.101224"

	}
	"hero_brew_spawn" {
		"soundIndex" "hero_brew_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/brewmaster/brew_spawn_03.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.272653"

	}
	"hero_brew_thanks" {
		"soundIndex" "hero_brew_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/brewmaster/brew_thanks_02.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.802449"

	}
	"hero_brew_win" {
		"soundIndex" "hero_brew_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/brewmaster/brew_respawn_09.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.056327"

	}
	"hero_bs_merge" {
		"soundIndex" "hero_bs_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/bloodseeker/blod_level_03.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.977959"

	}
	"hero_bs_spawn" {
		"soundIndex" "hero_bs_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/bloodseeker/blod_spawn_07.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.15347"

	}
	"hero_bs_win" {
		"soundIndex" "hero_bs_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/bloodseeker/blod_thanks_02.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.66449"

	}
	"hero_chen_fuhuo" {
		"soundIndex" "hero_chen_fuhuo"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/chen/hog_hero01.vsnd
sounds/weapons/hero/chen/hog_hero02.vsnd
sounds/weapons/hero/chen/hog_hero03.vsnd
sounds/weapons/hero/chen/hog_hero04.vsnd
sounds/weapons/hero/chen/hog_hero05.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.727302"

	}
	"hero_chen_merge" {
		"soundIndex" "hero_chen_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/chen/chen_ability_handgod_01.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.795102"

	}
	"hero_chen_spawn" {
		"soundIndex" "hero_chen_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/chen/chen_ability_holyp_04.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.76898"

	}
	"hero_chen_win" {
		"soundIndex" "hero_chen_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/chen/chen_win_03.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.037551"

	}
	"hero_dk_merge" {
		"soundIndex" "hero_dk_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dragon_knight/dk_davion_ability_elderdragon_06.vsnd"
		"volume" "1.700000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.498095"

	}
	"hero_dk_spawn" {
		"soundIndex" "hero_dk_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dragon_knight/dk_davion_spawn_03.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.596667"

	}
	"hero_dk_thanks" {
		"soundIndex" "hero_dk_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dragon_knight/dk_davion_wheel_thanks_01.vsnd
sounds/vo/dragon_knight/dk_davion_thanks_03.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.997438"

	}
	"hero_dk_win" {
		"soundIndex" "hero_dk_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dragon_knight/dk_davion_spawn_18.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.771973"

	}
	"hero_dr_thanks" {
		"soundIndex" "hero_dr_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/drowranger/drow_thanks_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.201633"

	}
	"hero_dw_merge" {
		"soundIndex" "hero_dw_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dark_willow/sylph_spawn_09.vsnd
sounds/vo/dark_willow/sylph_levelup_05.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.66449"

	}
	"hero_dw_spawn" {
		"soundIndex" "hero_dw_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dark_willow/sylph_spawn_02.vsnd
sounds/vo/dark_willow/sylph_spawn_05.vsnd
sounds/vo/dark_willow/sylph_spawn_03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.369796"

	}
	"hero_dw_thanks" {
		"soundIndex" "hero_dw_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dark_willow/sylph_thanks_01.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.462857"

	}
	"hero_dw_win" {
		"soundIndex" "hero_dw_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dark_willow/sylph_ability3_04.vsnd
sounds/vo/dark_willow/sylph_ability1_09.vsnd
sounds/vo/dark_willow/sylph_move_04.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.369796"

	}
	"hero_earth_fish" {
		"soundIndex" "hero_earth_fish"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earth_spirit/earthspi_stonecaller_03.vsnd
sounds/vo/earth_spirit/earthspi_stonecaller_09.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.66449"

	}
	"hero_earth_merge" {
		"soundIndex" "hero_earth_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earth_spirit/earthspi_spawn_06.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.526531"

	}
	"hero_earth_spawn" {
		"soundIndex" "hero_earth_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earth_spirit/earthspi_spawn_03.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.343673"

	}
	"hero_earth_thanks" {
		"soundIndex" "hero_earth_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earth_spirit/earthspi_thanks_02.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.063673"

	}
	"hero_earth_win" {
		"soundIndex" "hero_earth_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earth_spirit/earthspi_win_03.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.369796"

	}
	"hero_ember_fish" {
		"soundIndex" "hero_ember_fish"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/ember_spirit/embr_rival_12.vsnd
sounds/vo/ember_spirit/embr_levelup_09.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.638367"

	}
	"hero_ember_merge" {
		"soundIndex" "hero_ember_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/ember_spirit/embr_levelup_14.vsnd
sounds/vo/ember_spirit/embr_levelup_12.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.168163"

	}
	"hero_ember_spawn" {
		"soundIndex" "hero_ember_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/ember_spirit/embr_spawn_05.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.959184"

	}
	"hero_ember_thanks" {
		"soundIndex" "hero_ember_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/ember_spirit/embr_thanks_01.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.089796"

	}
	"hero_ember_win" {
		"soundIndex" "hero_ember_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/ember_spirit/embr_win_03.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.481633"

	}
	"hero_es_merge" {
		"soundIndex" "hero_es_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earthshaker/erth_level_03.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.324898"

	}
	"hero_es_spawn" {
		"soundIndex" "hero_es_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earthshaker/erth_spawn_03.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.638367"

	}
	"hero_es_taunt_ward" {
		"soundIndex" "hero_es_taunt_ward"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/monkey_king/taunt_boing.vsnd"
		"volume" "0.700000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.050708"

	}
	"hero_es_thanks" {
		"soundIndex" "hero_es_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earthshaker/erth_thanks_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.776327"

	}
	"hero_es_win" {
		"soundIndex" "hero_es_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/earthshaker/erth_win_06.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.448163"

	}
	"hero_et_merge" {
		"soundIndex" "hero_et_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/elder_titan/elder_levelup_08.vsnd
sounds/vo/elder_titan/elder_earthsplitter_05.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.179592"

	}
	"hero_et_spawn" {
		"soundIndex" "hero_et_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/elder_titan/elder_spawn_01.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.638367"

	}
	"hero_et_thanks" {
		"soundIndex" "hero_et_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/elder_titan/elder_thanks_02.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.168163"

	}
	"hero_et_win" {
		"soundIndex" "hero_et_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/elder_titan/elder_earthsplitter_02.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.951837"

	}
	"hero_fv_merge" {
		"soundIndex" "hero_fv_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/faceless_void/face_ability_chronos_05.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.925714"

	}
	"hero_fv_spawn" {
		"soundIndex" "hero_fv_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/faceless_void/face_spawn_01.vsnd
sounds/vo/faceless_void/face_rare_03.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.918367"

	}
	"hero_fv_thanks" {
		"soundIndex" "hero_fv_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/faceless_void/face_thanks_02.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.28"

	}
	"hero_fv_win" {
		"soundIndex" "hero_fv_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/faceless_void/face_kill_01.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.056327"

	}
	"hero_ga_merge" {
		"soundIndex" "hero_ga_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/alchemist/alch_respawn_09.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.683265"

	}
	"hero_ga_spawn" {
		"soundIndex" "hero_ga_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/alchemist/alch_spawn_05.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.160816"

	}
	"hero_ga_thanks" {
		"soundIndex" "hero_ga_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/alchemist/alch_spawn_06.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.73551"

	}
	"hero_ga_win" {
		"soundIndex" "hero_ga_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/alchemist/alch_win_03.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.35102"

	}
	"hero_gs_merge" {
		"soundIndex" "hero_gs_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/grimstroke/grimstroke_ability4_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.699955"

	}
	"hero_gs_spawn" {
		"soundIndex" "hero_gs_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/grimstroke/grimstroke_spawn_13.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.3"

	}
	"hero_gs_win" {
		"soundIndex" "hero_gs_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/grimstroke/grimstroke_spawn_11.vsnd"
		"volume" "0.800000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.4"

	}
	"hero_huskar_merge" {
		"soundIndex" "hero_huskar_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/huskar/husk_level_07.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.108572"

	}
	"hero_huskar_spawn" {
		"soundIndex" "hero_huskar_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/huskar/husk_spawn_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.253878"

	}
	"hero_huskar_win" {
		"soundIndex" "hero_huskar_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/huskar/husk_win_03.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.440816"

	}
	"hero_hw_merge" {
		"soundIndex" "hero_hw_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/hoodwink/hoodwink_levelup_13.vsnd
sounds/vo/hoodwink/hoodwink_levelup_19.vsnd"
		"volume" "0.900000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.48"

	}
	"hero_hw_spawn" {
		"soundIndex" "hero_hw_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/hoodwink/hoodwink_spawn_09.vsnd
sounds/vo/hoodwink/hoodwink_spawn_02_81.vsnd"
		"volume" "0.900000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.915"

	}
	"hero_hw_thanks" {
		"soundIndex" "hero_hw_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/hoodwink/hoodwink_thanks_03_04.vsnd
sounds/vo/hoodwink/hoodwink_wheel_thanks_02_02.vsnd"
		"volume" "0.900000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.1"

	}
	"hero_hw_win" {
		"soundIndex" "hero_hw_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/hoodwink/hoodwink_spawn_24.vsnd
sounds/vo/hoodwink/hoodwink_win_04.vsnd
sounds/vo/hoodwink/hoodwink_win_03.vsnd"
		"volume" "0.900000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.8"

	}
	"hero_kael_merge" {
		"soundIndex" "hero_kael_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvo_la_level_04.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.289977"

	}
	"hero_kael_spawn" {
		"soundIndex" "hero_kael_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvo_la_spawn_07.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.620454"

	}
	"hero_kael_thanks" {
		"soundIndex" "hero_kael_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvo_la_thanks_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.636168"

	}
	"hero_kael_win" {
		"soundIndex" "hero_kael_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvo_la_spawn_10_02.vsnd
sounds/vo/broodmother/broo_rare_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.707959"

	}
	"hero_kunkka_ship_bell" {
		"soundIndex" "hero_kunkka_ship_bell"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/kunkka/ability_ghost_ship_bell.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.72576"

	}
	"hero_kunkka_ship_bell_shark" {
		"soundIndex" "hero_kunkka_ship_bell_shark"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/kunkka/shark_bell.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.959229"

	}
	"hero_kunkka_ship_crash" {
		"soundIndex" "hero_kunkka_ship_crash"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/kunkka/ghostship_crash.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.172381"

	}
	"hero_kunkka_ship_crash_shark" {
		"soundIndex" "hero_kunkka_ship_crash_shark"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/kunkka/sharkship_impact.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.107891"

	}
	"hero_kunkka_ship_run" {
		"soundIndex" "hero_kunkka_ship_run"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/kunkka/ability_ghost_ship.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.425873"

	}
	"hero_kunkka_ship_run_shark" {
		"soundIndex" "hero_kunkka_ship_run_shark"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/kunkka/shark_ship.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.162676"

	}
	"hero_lc_merge" {
		"soundIndex" "hero_lc_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/legion_commander/legcom_levelup_09.vsnd
sounds/vo/legion_commander/legcom_levelup_07.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.526531"

	}
	"hero_lc_qianggong" {
		"soundIndex" "hero_lc_qianggong"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/legion_commander/press_cast.vsnd"
		"volume" "0.700000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.955692"

	}
	"hero_lc_spawn" {
		"soundIndex" "hero_lc_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/legion_commander/legcom_spawn_04.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.586123"

	}
	"hero_lc_thanks" {
		"soundIndex" "hero_lc_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/legion_commander/legcom_thanks_03.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.638367"

	}
	"hero_lc_win" {
		"soundIndex" "hero_lc_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/legion_commander/legcom_duelhero_32.vsnd
sounds/vo/legion_commander/legcom_respawn_02.vsnd
sounds/vo/legion_commander/legcom_respawn_03.vsnd
sounds/vo/legion_commander/legcom_duelhero_33.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.918367"

	}
	"hero_lion_merge" {
		"soundIndex" "hero_lion_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/lion/lion_level_05.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.552653"

	}
	"hero_lion_spawn" {
		"soundIndex" "hero_lion_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/lion/lion_spawn_04.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.84"

	}
	"hero_lion_win" {
		"soundIndex" "hero_lion_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/lion/lion_thanks_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.429388"

	}
	"hero_marci_merge" {
		"soundIndex" "hero_marci_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/marci/marci_immortality.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.351146"

	}
	"hero_marci_spawn" {
		"soundIndex" "hero_marci_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/marci/marci_move.vsnd
sounds/vo/marci/marci_move_2.vsnd
sounds/vo/marci/marci_move_3.vsnd
sounds/vo/marci/marci_sad.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.09825"

	}
	"hero_marci_thanks" {
		"soundIndex" "hero_marci_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/marci/marci_thanks.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.370083"

	}
	"hero_marci_win" {
		"soundIndex" "hero_marci_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/marci/marci_laugh.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.588667"

	}
	"hero_meepo_devided_1" {
		"soundIndex" "hero_meepo_devided_1"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/meepo/meepo_divided_01.vsnd
sounds/vo/meepo/meepo_divided_02.vsnd
sounds/vo/meepo/meepo_divided_03.vsnd
sounds/vo/meepo/meepo_divided_23.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.923016"

	}
	"hero_meepo_devided_2" {
		"soundIndex" "hero_meepo_devided_2"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/meepo/meepo_divided_24.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.727982"

	}
	"hero_meepo_merge" {
		"soundIndex" "hero_meepo_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/meepo/meepo_spawn_03.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.2"

	}
	"hero_meepo_poof" {
		"soundIndex" "hero_meepo_poof"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/meepo/poof_tone_01.vsnd
sounds/weapons/hero/meepo/poof_tone_02.vsnd
sounds/weapons/hero/meepo/poof_tone_03.vsnd
sounds/weapons/hero/meepo/poof_tone_04.vsnd
sounds/weapons/hero/meepo/poof_tone_05.vsnd"
		"volume" "0.750000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.158435"

	}
	"hero_meepo_spawn" {
		"soundIndex" "hero_meepo_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/meepo/meepo_spawn_02.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.300023"

	}
	"hero_meepo_thanks" {
		"soundIndex" "hero_meepo_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/meepo/meepo_thanks_01.vsnd
sounds/vo/meepo/meepo_thanks_02.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.100045"

	}
	"hero_meepo_win" {
		"soundIndex" "hero_meepo_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/meepo/meepo_win_03.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.6"

	}
	"hero_mk_merge" {
		"soundIndex" "hero_mk_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/monkey_king/monkey_spawn_09.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.848"

	}
	"hero_mk_spawn" {
		"soundIndex" "hero_mk_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/monkey_king/monkey_spawn_16.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.544"

	}
	"hero_mk_thanks" {
		"soundIndex" "hero_mk_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/monkey_king/monkey_thanks_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.752"

	}
	"hero_mk_win" {
		"soundIndex" "hero_mk_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/monkey_king/monkey_spawn_05.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.056"

	}
	"hero_na_merge" {
		"soundIndex" "hero_na_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/nyx_assassin/nyx_move_07.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.47102"

	}
	"hero_na_spawn" {
		"soundIndex" "hero_na_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/nyx_assassin/nyx_move_13.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.94449"

	}
	"hero_na_win" {
		"soundIndex" "hero_na_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/nyx_assassin/nyx_move_06.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.977959"

	}
	"hero_naga_merge" {
		"soundIndex" "hero_naga_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/naga_siren/naga_sing_01.vsnd
sounds/vo/naga_siren/naga_sing_02.vsnd
sounds/vo/naga_siren/naga_sing_03.vsnd
sounds/vo/naga_siren/naga_sing_04.vsnd
sounds/vo/naga_siren/naga_sing_05.vsnd
sounds/vo/naga_siren/naga_sing_06.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.269388"

	}
	"hero_naga_spawn" {
		"soundIndex" "hero_naga_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/naga_siren/naga_spawn_01.vsnd
sounds/vo/naga_siren/naga_move_11.vsnd
sounds/vo/naga_siren/naga_move_16.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.63102"

	}
	"hero_naga_thanks" {
		"soundIndex" "hero_naga_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/naga_siren/naga_thanks_02.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.56"

	}
	"hero_naga_win" {
		"soundIndex" "hero_naga_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/naga_siren/naga_songofthesiren_01.vsnd
sounds/vo/naga_siren/naga_songofthesiren_02.vsnd
sounds/vo/naga_siren/naga_songofthesiren_03.vsnd
sounds/vo/naga_siren/naga_songofthesiren_04.vsnd
sounds/vo/naga_siren/naga_songofthesiren_05.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.821224"

	}
	"hero_oracle_merge" {
		"soundIndex" "hero_oracle_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/oracle/orac_randomprophecies_08.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.892245"

	}
	"hero_oracle_spawn" {
		"soundIndex" "hero_oracle_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/oracle/orac_purifyingflames_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.134694"

	}
	"hero_oracle_win" {
		"soundIndex" "hero_oracle_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/oracle/orac_levelup_11.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.093877"

	}
	"hero_pangolier_merge" {
		"soundIndex" "hero_pangolier_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/pangolin/pangolin_levelup_10.vsnd
sounds/vo/pangolin/pangolin_spawn_04.vsnd
sounds/vo/pangolin/pangolin_purch_04.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.474286"

	}
	"hero_pangolier_spawn" {
		"soundIndex" "hero_pangolier_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/pangolin/pangolin_spawn_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.474286"

	}
	"hero_pangolier_thanks" {
		"soundIndex" "hero_pangolier_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/pangolin/pangolin_thanks_04.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.776327"

	}
	"hero_pangolier_win" {
		"soundIndex" "hero_pangolier_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/pangolin/pangolin_spawn_22.vsnd
sounds/vo/pangolin/pangolin_spawn_06.vsnd
sounds/vo/pangolin/pangolin_levelup_09.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.773061"

	}
	"hero_pb_merge" {
		"soundIndex" "hero_pb_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/primal_beast/primal_spawn_01.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.896984"

	}
	"hero_pb_spawn" {
		"soundIndex" "hero_pb_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/primal_beast/primal_happy_04.vsnd"
		"volume" "2.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.434875"

	}
	"hero_pb_thanks" {
		"soundIndex" "hero_pb_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/primal_beast/primal_happy_07.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.223084"

	}
	"hero_pb_win" {
		"soundIndex" "hero_pb_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/primal_beast/primal_underattack_04.vsnd"
		"volume" "2.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.033356"

	}
	"hero_pom_spawn" {
		"soundIndex" "hero_pom_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/mirana/mira_per_kill_02.vsnd
sounds/vo/mirana/mira_per_spawn_01.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.355986"

	}
	"hero_pudge_merge" {
		"soundIndex" "hero_pudge_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/pudge/pud_arc_fresh_35_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.220408"

	}
	"hero_pudge_spawn" {
		"soundIndex" "hero_pudge_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/pudge/pud_arc_fresh_05_02.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.35102"

	}
	"hero_pudge_win" {
		"soundIndex" "hero_pudge_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/pudge/pud_arc_fresh_24_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.56"

	}
	"hero_rubick_merge" {
		"soundIndex" "hero_rubick_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/rubick/rub_arc_spellsteal_13.vsnd"
		"volume" "0.800000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.700046"

	}
	"hero_rubick_spawn" {
		"soundIndex" "hero_rubick_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/rubick/rub_arc_spellsteal_14.vsnd"
		"volume" "0.800000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.5"

	}
	"hero_rubick_win" {
		"soundIndex" "hero_rubick_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/rubick/rub_arc_spellsteal_05.vsnd"
		"volume" "0.800000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.6"

	}
	"hero_sb_merge" {
		"soundIndex" "hero_sb_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/spirit_breaker/spir_spawn_04.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.996735"

	}
	"hero_sb_spawn" {
		"soundIndex" "hero_sb_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/spirit_breaker/spir_spawn_01.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.567347"

	}
	"hero_sb_thanks" {
		"soundIndex" "hero_sb_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/spirit_breaker/spir_thanks_03.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.645714"

	}
	"hero_sb_win" {
		"soundIndex" "hero_sb_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/spirit_breaker/spir_kill_08.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.160816"

	}
	"hero_shaman_devolve" {
		"soundIndex" "hero_shaman_devolve"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/lion/lion_voodoo.vsnd"
		"volume" "0.800000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.889524"

	}
	"hero_shaman_evolve" {
		"soundIndex" "hero_shaman_evolve"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/addons/dungeon/boss_bar.vsnd"
		"volume" "0.800000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.217574"

	}
	"hero_snap_merge" {
		"soundIndex" "hero_snap_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/snapfire/snapfire_ability1_03.vsnd
sounds/vo/snapfire/snapfire_ability3_04.vsnd
sounds/vo/snapfire/snapfire_ability3_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.3"

	}
	"hero_snap_spawn" {
		"soundIndex" "hero_snap_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/snapfire/snapfire_spawn_03.vsnd
sounds/vo/snapfire/snapfire_spawn_02.vsnd
sounds/vo/snapfire/snapfire_spawn_03.vsnd
"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.565"

	}
	"hero_snap_thanks" {
		"soundIndex" "hero_snap_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/snapfire/snapfire_thanks_03.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.85"

	}
	"hero_snap_win" {
		"soundIndex" "hero_snap_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/snapfire/snapfire_win_06.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.799667"

	}
	"hero_spe_dota1" {
		"soundIndex" "hero_spe_dota1"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/spe_dota1.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.693469"

	}
	"hero_spe_merge" {
		"soundIndex" "hero_spe_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/spectre/spec_rare_01.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.918367"

	}
	"hero_spe_spawn" {
		"soundIndex" "hero_spe_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/spectre/spec_respawn_01.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.429388"

	}
	"hero_spe_thanks" {
		"soundIndex" "hero_spe_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/spectre/spec_thanks_02.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.089796"

	}
	"hero_spe_win" {
		"soundIndex" "hero_spe_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/spectre/spec_win_01.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.854694"

	}
	"hero_ss_ssr_wards" {
		"soundIndex" "hero_ss_ssr_wards"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/shadowshaman/serpent_ward.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.751837"

	}
	"hero_storm_fish" {
		"soundIndex" "hero_storm_fish"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/stormspirit/ss_ability_lightning_05.vsnd
sounds/vo/stormspirit/ss_ability_static_04.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.35102"

	}
	"hero_storm_merge" {
		"soundIndex" "hero_storm_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/stormspirit/ss_haste_03.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.395918"

	}
	"hero_storm_spawn" {
		"soundIndex" "hero_storm_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/stormspirit/ss_respawn_03.vsnd
sounds/vo/stormspirit/ss_rare_01.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.709388"

	}
	"hero_storm_thanks" {
		"soundIndex" "hero_storm_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/stormspirit/stormspirit_thanks_03.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.671837"

	}
	"hero_storm_win" {
		"soundIndex" "hero_storm_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/stormspirit/ss_inthebag_01.vsnd
sounds/vo/stormspirit/ss_ability_lightning_21.vsnd
sounds/vo/stormspirit/ss_kill_04.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.429388"

	}
	"hero_sven_merge" {
		"soundIndex" "hero_sven_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/sven/sven_rare_08.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.73551"

	}
	"hero_sven_spawn" {
		"soundIndex" "hero_sven_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/sven/sven_win_03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.873469"

	}
	"hero_sven_win" {
		"soundIndex" "hero_sven_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/sven/sven_ability_teleport_04.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.168163"

	}
	"hero_thd_merge" {
		"soundIndex" "hero_thd_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/jakiro/jak_respawn_10.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.657143"

	}
	"hero_thd_spawn" {
		"soundIndex" "hero_thd_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/jakiro/jak_spawn_04.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.787755"

	}
	"hero_thd_win" {
		"soundIndex" "hero_thd_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/jakiro/jak_win_03.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.314286"

	}
	"hero_troll_axe_hit" {
		"soundIndex" "hero_troll_axe_hit"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/beastmaster/attack03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.265147"

	}
	"hero_troll_merge" {
		"soundIndex" "hero_troll_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/troll_warlord/troll_ally_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.56"

	}
	"hero_troll_spawn" {
		"soundIndex" "hero_troll_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/troll_warlord/troll_levelup_06.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.004082"

	}
	"hero_troll_thanks" {
		"soundIndex" "hero_troll_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/troll_warlord/troll_thanks_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.35102"

	}
	"hero_troll_win" {
		"soundIndex" "hero_troll_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/troll_warlord/troll_ally_02.vsnd
sounds/vo/troll_warlord/troll_ally_09.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.008163"

	}
	"hero_visage_merge" {
		"soundIndex" "hero_visage_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/visage/visa_summon_04.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.220408"

	}
	"hero_visage_spawn" {
		"soundIndex" "hero_visage_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/visage/visa_spawn_04.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.388571"

	}
	"hero_visage_win" {
		"soundIndex" "hero_visage_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/visage/visa_win_04.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.683265"

	}
	"hero_void_fish" {
		"soundIndex" "hero_void_fish"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/void_spirit/voidspir_ability1_08.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.799917"

	}
	"hero_void_merge" {
		"soundIndex" "hero_void_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/void_spirit/voidspir_ability1_09.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.400083"

	}
	"hero_void_spawn" {
		"soundIndex" "hero_void_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/void_spirit/voidspir_spawn_02.vsnd
sounds/vo/void_spirit/voidspir_levelup_07_02.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.605"

	}
	"hero_void_thanks" {
		"soundIndex" "hero_void_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/void_spirit/voidspir_thanks_03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.5"

	}
	"hero_void_win" {
		"soundIndex" "hero_void_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/void_spirit/voidspir_win_04.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.5"

	}
	"hero_vs_merge" {
		"soundIndex" "hero_vs_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/vengefulspirit/vng_rare_09.vsnd
sounds/vo/vengefulspirit/vng_rare_01.vsnd
sounds/vo/vengefulspirit/vng_win_02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.448163"

	}
	"hero_vs_spawn" {
		"soundIndex" "hero_vs_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/vengefulspirit/vng_spawn_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.246531"

	}
	"hero_vs_thanks" {
		"soundIndex" "hero_vs_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/vengefulspirit/vng_thanks_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.115918"

	}
	"hero_vs_win" {
		"soundIndex" "hero_vs_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/vengefulspirit/vng_rival_03.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.186939"

	}
	"hero_warlock_brainsap" {
		"soundIndex" "hero_warlock_brainsap"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/bane/brain_sap_cast.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.661973"

	}
	"hero_wl_merge" {
		"soundIndex" "hero_wl_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/warlock/warl_doubdemon_01.vsnd
sounds/vo/warlock/warl_doubdemon_01.vsnd
sounds/vo/warlock/warl_doubdemon_01.vsnd
sounds/vo/warlock/warl_doubdemon_01.vsnd
sounds/vo/warlock/warl_doubdemon_03.vsnd
sounds/vo/warlock/warl_doubdemon_02.vsnd
sounds/vo/warlock/warl_doubdemon_04.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.213061"

	}
	"hero_wl_spawn" {
		"soundIndex" "hero_wl_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/warlock/warl_incant_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.937143"

	}
	"hero_wl_thanks" {
		"soundIndex" "hero_wl_thanks"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/warlock/warl_incant_24.vsnd
sounds/vo/warlock/warl_spawn_03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.68"

	}
	"hero_wl_win" {
		"soundIndex" "hero_wl_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/warlock/warl_incant_9.vsnd
sounds/vo/warlock/warl_incant_10.vsnd
sounds/vo/warlock/warl_incant_11.vsnd
sounds/vo/warlock/warl_incant_12.vsnd
sounds/vo/warlock/warl_incant_13.vsnd
sounds/vo/warlock/warl_incant_14.vsnd
sounds/vo/warlock/warl_incant_15.vsnd
sounds/vo/warlock/warl_incant_16.vsnd
sounds/vo/warlock/warl_incant_17.vsnd
sounds/vo/warlock/warl_incant_18.vsnd
sounds/vo/warlock/warl_incant_19.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.131429"

	}
	"hero_ww_merge" {
		"soundIndex" "hero_ww_merge"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/winter_wyvern/winwyv_levelup_08.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.91102"

	}
	"hero_ww_spawn" {
		"soundIndex" "hero_ww_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/winter_wyvern/winwyv_rare_01.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.552653"

	}
	"hero_ww_win" {
		"soundIndex" "hero_ww_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/winter_wyvern/winwyv_winterscurse_09.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.959184"

	}
	"is_human_magic" {
		"soundIndex" "is_human_magic"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/frostivus_magic.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.283877"

	}
	"item_atuosi" {
		"soundIndex" "item_atuosi"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/rod_of_atos.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.973288"

	}
	"item_destroy_piece" {
		"soundIndex" "item_destroy_piece"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/grimstroke/taunt_ti9.vsnd"
		"volume" "0.900000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.995714"

	}
	"item_diffusalblade" {
		"soundIndex" "item_diffusalblade"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/item_diffusalblade.vsnd"
		"volume" "0.600000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.843515"

	}
	"item_exp2" {
		"soundIndex" "item_exp2"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/tome_of_knowledge.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.662381"

	}
	"item_greatvault_spawn" {
		"soundIndex" "item_greatvault_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/addons/dungeon/boss_bar.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.217574"

	}
	"item_hide" {
		"soundIndex" "item_hide"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/music/valve_dota_001/music/smoke.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "43.781223"

	}
	"item_jixiezhixin_get" {
		"soundIndex" "item_jixiezhixin_get"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/techies/land_mine_primed.vsnd"
		"volume" "1.600000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.367982"

	}
	"item_jixiezhixin_open" {
		"soundIndex" "item_jixiezhixin_open"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/techies/remote_mine_plant.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.049819"

	}
	"item_jufengchangji" {
		"soundIndex" "item_jufengchangji"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/windrunner/windrun.vsnd"
		"volume" "0.700000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.000567"

	}
	"item_lianhua" {
		"soundIndex" "item_lianhua"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/lotus_activate.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.685125"

	}
	"item_lifesteal" {
		"soundIndex" "item_lifesteal"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/lifestealer/infest.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.652063"

	}
	"item_linken" {
		"soundIndex" "item_linken"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/linkens_sphere.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.746939"

	}
	"item_mangotree_break" {
		"soundIndex" "item_mangotree_break"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/monkey_king/tree03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.408005"

	}
	"item_mangotree_spawn" {
		"soundIndex" "item_mangotree_spawn"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/tree_transform.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.527982"

	}
	"item_meiken" {
		"soundIndex" "item_meiken"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/mek_cast.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.472381"

	}
	"item_multicast" {
		"soundIndex" "item_multicast"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/ogre_magi/multicast01.vsnd
sounds/weapons/hero/ogre_magi/multicast02.vsnd
sounds/weapons/hero/ogre_magi/multicast03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.343356"

	}
	"item_weishijingjia" {
		"soundIndex" "item_weishijingjia"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/guardian_greaves.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.484603"

	}
	"lvl_up" {
		"soundIndex" "lvl_up"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/omniknight/guardian01.vsnd
sounds/weapons/hero/omniknight/guardian02.vsnd
sounds/weapons/hero/omniknight/guardian03.vsnd
sounds/weapons/hero/omniknight/guardian04.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.013741"

	}
	"monk_duang" {
		"soundIndex" "monk_duang"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/axe/culling_blade_success.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.734558"

	}
	"monk_duang2" {
		"soundIndex" "monk_duang2"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/axe/culling_blade_fail.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.633878"

	}
	"ogre_fat" {
		"soundIndex" "ogre_fat"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/ogre_magi/bloodlust_cast.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.817143"

	}
	"om_multi_cast" {
		"soundIndex" "om_multi_cast"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/ogre_magi/multicast01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.993333"

	}
	"om_multi_cast2" {
		"soundIndex" "om_multi_cast2"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/ogre_magi/multicast03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.343356"

	}
	"projectile_hit_tower" {
		"soundIndex" "projectile_hit_1000"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/physics/damage/player/tower_projectile01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.150703"

	}
	"projectile_hit_tiannu" {
		"soundIndex" "projectile_hit_1001"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/skywrath/concussive_shot_target.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.584558"

	}
	"projectile_hit_duye" {
		"soundIndex" "projectile_hit_1002"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/viper/nethertoxin_cast.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.221905"

	}
	"projectile_hit_zhuore" {
		"soundIndex" "projectile_hit_1003"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/clinkz/searing_impact01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.994059"

	}
	"projectile_hit_yueren" {
		"soundIndex" "projectile_hit_1004"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/luna/glaives03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.162358"

	}
	"projectile_hit_chuizi" {
		"soundIndex" "projectile_hit_1005"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/sven/storm_bolt_impact.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.48254"

	}
	"projectile_hit_linghun" {
		"soundIndex" "projectile_hit_1006"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/nevermore/ros_flames.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.912676"

	}
	"projectile_hit_emeng" {
		"soundIndex" "projectile_hit_1007"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/bane/nightmare_end.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.833832"

	}
	"projectile_hit_snake" {
		"soundIndex" "projectile_hit_1008"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/medusa/snake_impact_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.887619"

	}
	"projectile_hit_snowball" {
		"soundIndex" "projectile_hit_1009"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/tusk/snowball_target.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.998481"

	}
	"projectile_hit_net" {
		"soundIndex" "projectile_hit_1010"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/naga_siren/ensnare_target.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.797279"

	}
	"projectile_hit_flare_explode" {
		"soundIndex" "projectile_hit_1011"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/rattletrap/flare_explode.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.661973"

	}
	"projectile_hit_frost_arrow" {
		"soundIndex" "projectile_hit_1012"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/drow_ranger/frost_arrow1.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.275601"

	}
	"projectile_hit_magic_missile" {
		"soundIndex" "projectile_hit_1013"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/vengeful_spirit/magic_missile_impact.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.835125"

	}
	"projectile_hit_unstable_concoction" {
		"soundIndex" "projectile_hit_1014"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/alchemist/unstable_concoction_stun02.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.186304"

	}
	"projectile_hit_lichking" {
		"soundIndex" "projectile_hit_1015"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/lich/frost_blast_immortal.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.96"

	}
	"projectile_hit_rainbow" {
		"soundIndex" "projectile_hit_1016"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/enchantress/enchant_cast.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.979796"

	}
	"projectile_hit_berserk_potion" {
		"soundIndex" "projectile_hit_1017"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/alchemist/berserk_potion_target.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.388594"

	}
	"projectile_hit_cookie" {
		"soundIndex" "projectile_hit_1018"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/snapfire/cookie_target.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.20102"

	}
	"projectile_hit_paintball" {
		"soundIndex" "projectile_hit_1019"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/paintball_target.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.288687"

	}
	"projectile_hit_pepper" {
		"soundIndex" "projectile_hit_1020"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/hot_potato/hot_pot_projectile.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.2475"

	}
	"projectile_hit_spark_wraith" {
		"soundIndex" "projectile_hit_1021"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/arc_warden/spark_wraith_damage.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.49"

	}
	"quick_lvl_up" {
		"soundIndex" "quick_lvl_up"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/economy/underdraft_levelup_1.vsnd
sounds/ui/economy/underdraft_levelup_2.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.833854"

	}
	"shenjingdun_cast" {
		"soundIndex" "shenjingdun_cast"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/lotus_cast.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.286576"

	}
	"shenjingdun_damage" {
		"soundIndex" "shenjingdun_damage"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/physics/damage/building/bd_protect.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.156735"

	}
	"shrink_meister_activate" {
		"soundIndex" "shrink_meister_activate"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/tinker/laser.vsnd"
		"volume" "0.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.95102"

	}
	"tauren_ward_laser" {
		"soundIndex" "tauren_ward_laser"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/tinker/laser.vsnd"
		"volume" "0.600000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.95102"

	}
	"tauren_ward_nether" {
		"soundIndex" "tauren_ward_nether"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/pugna/netherblast_ti9.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.859592"

	}
	"visage_baby" {
		"soundIndex" "visage_baby"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/visage/summon_familiars.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.027732"

	}
	"warning_qianjiaomonv" {
		"soundIndex" "warning_qianjiaomonv"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ambient/soundscapes/diretide/diretide_spirit_vx_01.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.15288"

	}
	"warning_tangyimaowang" {
		"soundIndex" "warning_tangyimaowang"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/diretide_black_cat.vsnd"
		"volume" "0.800000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.152834"

	}
	"warning_wolf" {
		"soundIndex" "warning_wolf"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ambient/soundscapes/diretide/diretide_wolf_03.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.625079"

	}
	"welcome_crystal_maiden" {
		"soundIndex" "welcome_crystal_maiden"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/announcer_dlc_monkey_king/mk_ann_welcome_01.vsnd
sounds/vo/announcer_dlc_monkey_king/mk_ann_unpause_01.vsnd
sounds/vo/announcer_dlc_monkey_king/mk_ann_battle_begins_01.vsnd
sounds/vo/announcer_dlc_monkey_king/mk_ann_battle_begins_04.vsnd
sounds/vo/announcer_dlc_monkey_king/mk_ann_ancient_attack_follow_up_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.056"

	}
	"wizard_buff" {
		"soundIndex" "wizard_buff"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/rubick/telekinesis_target.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.56644"

	}
	"xiyou_combine_3" {
		"soundIndex" "xiyou_combine_3"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/stingers/stinger_loot_02.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.990136"

	}
	"xiyou_combine_4" {
		"soundIndex" "xiyou_combine_4"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/music/stingers/dota2_music_stinger_009.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.157551"

	}
	"xiyou_combine_5" {
		"soundIndex" "xiyou_combine_5"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/music/stingers/dota2_music_stinger_008.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "8.228572"

	}
	"xiyou_combine_6" {
		"soundIndex" "xiyou_combine_6"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/music/stingers/dota2_music_stinger_003.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "8.85551"

	}
	"xiyou_combine_7" {
		"soundIndex" "xiyou_combine_7"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/music/stingers/greevil_stingers/loot_greevil_spawn.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.601633"

	}
	"xiyou_combine_8" {
		"soundIndex" "xiyou_combine_8"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/music/stingers/greevil_stingers/greevil_mega_spawn.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.47102"

	}
	"xiyou_combine_9" {
		"soundIndex" "xiyou_combine_9"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/stingers/arcana_loot.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "14.785306"

	}
	"xiyou_cpsound" {
		"soundIndex" "xiyou_cpsound"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/wisp/kill_arcana.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.791837"

	}
	"xiyou_disarm_chess" {
		"soundIndex" "xiyou_disarm_chess"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/speech_popup.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.614399"

	}
	"xiyou_emotion_1" {
		"soundIndex" "xiyou_emotion_1"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/legion_commander/legcom_win_07.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.201633"

	}
	"xiyou_emotion_10" {
		"soundIndex" "xiyou_emotion_10"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/zuus/taunt_jump.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.670748"

	}
	"xiyou_emotion_11" {
		"soundIndex" "xiyou_emotion_11"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/meepo/meepo_happy_07.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.200181"

	}
	"xiyou_emotion_12" {
		"soundIndex" "xiyou_emotion_12"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/skywrath/taunt_chicken.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.874875"

	}
	"xiyou_emotion_13" {
		"soundIndex" "xiyou_emotion_13"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/diretide_ghost.vsnd"
		"volume" "1.400000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.914104"

	}
	"xiyou_emotion_14" {
		"soundIndex" "xiyou_emotion_14"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/announcer_diretide_2012/announcer_welcome_05.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "5.172245"

	}
	"xiyou_emotion_15" {
		"soundIndex" "xiyou_emotion_15"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ambient/soundscapes/diretide/diretide_wolf_02.vsnd
sounds/ambient/soundscapes/diretide/diretide_wolf_03.vsnd
sounds/ambient/soundscapes/diretide/diretide_wolf_04.vsnd"
		"volume" "1.700000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "6.948072"

	}
	"xiyou_emotion_16" {
		"soundIndex" "xiyou_emotion_16"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/furion/furi_laugh_05.vsnd
sounds/vo/furion/furi_laugh_08.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.108572"

	}
	"xiyou_emotion_17" {
		"soundIndex" "xiyou_emotion_17"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/tusk/tusk_snowball_03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.619592"

	}
	"xiyou_emotion_18" {
		"soundIndex" "xiyou_emotion_18"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/keeper_of_the_light/keep_chakramagic_02.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.612245"

	}
	"xiyou_emotion_19" {
		"soundIndex" "xiyou_emotion_19"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/marci/marci_deny.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "0.606979"

	}
	"xiyou_emotion_2" {
		"soundIndex" "xiyou_emotion_2"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/troll_warlord/troll_lose_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.828571"

	}
	"xiyou_emotion_20" {
		"soundIndex" "xiyou_emotion_20"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/tusk/tusk_superpunch_ready_04.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.515102"

	}
	"xiyou_emotion_21" {
		"soundIndex" "xiyou_emotion_21"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/void_spirit/voidspir_kill_10.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.3"

	}
	"xiyou_emotion_22" {
		"soundIndex" "xiyou_emotion_22"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/hoodwink/hoodwink_acorn_en_08.vsnd
sounds/vo/hoodwink/hoodwink_acorn_en_06_02.vsnd
sounds/vo/hoodwink/hoodwink_acorn_en_07.vsnd"
		"volume" "1.100000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.465"

	}
	"xiyou_emotion_23" {
		"soundIndex" "xiyou_emotion_23"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/techies/tech_remotemines_23.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.900083"

	}
	"xiyou_emotion_24" {
		"soundIndex" "xiyou_emotion_24"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/rubick/rub_arc_spellsteal_05.vsnd"
		"volume" "0.900000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.6"

	}
	"xiyou_emotion_25" {
		"soundIndex" "xiyou_emotion_25"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/invoker/kidvoker_ability_sunstrike_05.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.297075"

	}
	"xiyou_emotion_26" {
		"soundIndex" "xiyou_emotion_26"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/templar_assassin/temp_lose_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.1"

	}
	"xiyou_emotion_27" {
		"soundIndex" "xiyou_emotion_27"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/charge.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.165351"

	}
	"xiyou_emotion_3" {
		"soundIndex" "xiyou_emotion_3"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/ogre_magi/ogmag_deny_03.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.48898"

	}
	"xiyou_emotion_32" {
		"soundIndex" "xiyou_emotion_32"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/luna/taunt_catdance.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.698231"

	}
	"xiyou_emotion_4" {
		"soundIndex" "xiyou_emotion_4"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/monkey_king/monkey_ability4_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.64"

	}
	"xiyou_emotion_5" {
		"soundIndex" "xiyou_emotion_5"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/snapfire/snapfire_happy_08.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.798333"

	}
	"xiyou_emotion_6" {
		"soundIndex" "xiyou_emotion_6"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/dark_willow/sylph_ally_201.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.45551"

	}
	"xiyou_emotion_7" {
		"soundIndex" "xiyou_emotion_7"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/mars/mars_ability4_09.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.717596"

	}
	"xiyou_emotion_8" {
		"soundIndex" "xiyou_emotion_8"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/undying/undying_death_08.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.76898"

	}
	"xiyou_emotion_9" {
		"soundIndex" "xiyou_emotion_9"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/vo/bounty_hunter/bount_lasthit_03.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.638367"

	}
	"xiyou_endboard" {
		"soundIndex" "xiyou_endboard"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/addons/conquest/pendulum.vsnd"
		"volume" "1.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "16.561632"

	}
	"xiyou_event_ti9" {
		"soundIndex" "xiyou_event_ti9"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/music/valve_ti9/music/ganked_lg.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "7.511814"

	}
	"xiyou_human_silence" {
		"soundIndex" "xiyou_human_silence"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/silence.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.045896"

	}
	"xiyou_loot_drop" {
		"soundIndex" "xiyou_loot_drop"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/stingers/stinger_loot_01.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.846984"

	}
	"xiyou_loot_open" {
		"soundIndex" "xiyou_loot_open"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/crafting/mech_open.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.250249"

	}
	"xiyou_popup" {
		"soundIndex" "xiyou_popup"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/addons/conquest/capture_point_timer.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.500068"

	}
	"xiyou_pudge_fresh_meat" {
		"soundIndex" "xiyou_pudge_fresh_meat"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/fresh_meat.vsnd"
		"volume" "3.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.246531"

	}
	"xiyou_remove_chess" {
		"soundIndex" "xiyou_remove_chess"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/item_handofmidas.vsnd"
		"volume" "0.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.999887"

	}
	"xiyou_round_lose" {
		"soundIndex" "xiyou_round_lose"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/ti9_crowd_groan.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.240726"

	}
	"xiyou_round_lose_pve" {
		"soundIndex" "xiyou_round_lose_pve"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/soundboard/ti9_head_bonk.vsnd"
		"volume" "0.750000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.104717"

	}
	"xiyou_round_win" {
		"soundIndex" "xiyou_round_win"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/misc/crowd_lv_01.vsnd"
		"volume" "1.500000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.57381"

	}
	"xiyou_shield" {
		"soundIndex" "xiyou_shield"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/pangolier/shield.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.448163"

	}
	"xiyou_tech_explode" {
		"soundIndex" "xiyou_tech_explode"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/techies/remote_mine05.vsnd"
		"volume" "2.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.186122"

	}
	"xiyou_tech_plantbomb" {
		"soundIndex" "xiyou_tech_plantbomb"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/techies/remote_mine_plant.vsnd"
		"volume" "1.000000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.049819"

	}
	"xiyou_teleport" {
		"soundIndex" "xiyou_teleport"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/weapons/hero/wisp/relocate.vsnd"
		"volume" "0.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "4.896667"

	}
	"xiyou_testerbox_start_battle" {
		"soundIndex" "xiyou_testerbox_start_battle"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/addons/conquest/capture_point_timer.vsnd"
		"volume" "1.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "1.500068"

	}
	"xiyou_tp" {
		"soundIndex" "xiyou_tp"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/ui/portal_appear.vsnd"
		"volume" "0.300000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "2.091995"

	}
	"xiyou_warlock_soul_ring" {
		"soundIndex" "xiyou_warlock_soul_ring"
		"type" "dota_src1_3d"
		"vsnd_files" "sounds/items/soul_ring.vsnd"
		"volume" "0.200000"
		"pitch_rand_min" "-0.050000"
		"pitch_rand_max" "0.050000"
		"pitch" "1.000000"
		"soundlevel" "100.000000"
		"distance_max" "1600.000000"
		"event_type" "1.000000"
		"vsnd_duration" "3.582517"

	}

}
