// generate with PIPIXIA's kv generator 
export namespace building_combination_ability { 
export interface OBJ_0_1 {
"building_combination_ability" :OBJ_1_1 ,
}
export interface OBJ_1_1 {
"phyarm_up_3_building_hero_ursa" :OBJ_2_1 ,
"phyarm_up_6_building_hero_ursa" :OBJ_2_1 ,
"phyarm_up_9_building_hero_ursa" :OBJ_2_1 ,
"phyarm_up_3_building_hero_kunkka" :OBJ_2_1 ,
"phyarm_up_6_building_hero_kunkka" :OBJ_2_1 ,
"phyarm_up_9_building_hero_kunkka" :OBJ_2_1 ,
"phyarm_up_3_building_hero_tusk" :OBJ_2_1 ,
"phyarm_up_6_building_hero_tusk" :OBJ_2_1 ,
"phyarm_up_9_building_hero_tusk" :OBJ_2_1 ,
"phyarm_up_3_building_hero_axe" :OBJ_2_1 ,
"phyarm_up_6_building_hero_axe" :OBJ_2_1 ,
"phyarm_up_9_building_hero_axe" :OBJ_2_1 ,
"phyarm_up_3_building_hero_juggernaut" :OBJ_2_1 ,
"phyarm_up_6_building_hero_juggernaut" :OBJ_2_1 ,
"phyarm_up_9_building_hero_juggernaut" :OBJ_2_1 ,
"phyarm_up_3_building_hero_troll_warlord" :OBJ_2_1 ,
"phyarm_up_6_building_hero_troll_warlord" :OBJ_2_1 ,
"phyarm_up_9_building_hero_troll_warlord" :OBJ_2_1 ,
"phyarm_up_3_building_hero_slardar" :OBJ_2_1 ,
"phyarm_up_6_building_hero_slardar" :OBJ_2_1 ,
"phyarm_up_9_building_hero_slardar" :OBJ_2_1 ,
"phyarm_up_3_building_hero_sven" :OBJ_2_1 ,
"phyarm_up_6_building_hero_sven" :OBJ_2_1 ,
"phyarm_up_9_building_hero_sven" :OBJ_2_1 ,
"phyarm_up_3_building_hero_mars" :OBJ_2_1 ,
"phyarm_up_6_building_hero_mars" :OBJ_2_1 ,
"phyarm_up_9_building_hero_mars" :OBJ_2_1 ,
"phyarm_up_3_building_hero_primal_beast" :OBJ_2_1 ,
"phyarm_up_6_building_hero_primal_beast" :OBJ_2_1 ,
"phyarm_up_9_building_hero_primal_beast" :OBJ_2_1 ,
"phyarm_up_3_building_hero_skeleton_king" :OBJ_2_1 ,
"phyarm_up_6_building_hero_skeleton_king" :OBJ_2_1 ,
"phyarm_up_9_building_hero_skeleton_king" :OBJ_2_1 ,
"phyarm_up_3_building_hero_pudge" :OBJ_2_1 ,
"phyarm_up_6_building_hero_pudge" :OBJ_2_1 ,
"phyarm_up_9_building_hero_pudge" :OBJ_2_1 ,
[k:string] : OBJ_2_1 }
export interface OBJ_2_1 {
"relation" :string ,
"relationicon" :string ,
"relationid" :string ,
"index" :string ,
"active_count" :string ,
"acitve_common_effect" :string ,
"Abilityid" :string ,
[k:string] : string }
}